### ISSUE TITLE
Feature request: All Fira Code Ligatures

### ISSUE THREAD

**Issue by F1LT3R** [MonoLisaFont/feedback#10]
Are there any plans to add the other ligatures found in Fira Code?

Eg: 
- `...`
- `www`

![Fira Code Ligatures](https://raw.githubusercontent.com/tonsky/FiraCode/master/showcases/all_ligatures.png)

**Comment by Eldair** [comment]
`||` as well

**Comment by waynehoover** [comment]
I second the www Ligatures.

**Comment by MarcusSterz** [comment]
• MonoLisa contains an ellipsis [...] already.
• Not sure about the www ligature. What is the advantage of such a symbol? Wouldn’t it look even more confusing when the w’s were connected?

**Comment by F1LT3R** [comment]
@MarcusSterz ...

### Connected WWW's

Connected WWW's look great, they are less confusing than three regular W's. It's a nice signifier that the parser will do something with that string. They should do the same for protocols imo, http, https, ftp, etc.

Fira Code:

<img width="394" alt="CleanShot 2020-05-05 at 00 32 35@2x" src="https://user-images.githubusercontent.com/1218446/81035190-f156e180-8e67-11ea-93d7-f2fd932250da.png">

MonoLisa:

<img width="418" alt="CleanShot 2020-05-05 at 00 33 39@2x" src="https://user-images.githubusercontent.com/1218446/81035232-177c8180-8e68-11ea-8849-8aa0d9c53afc.png">

## Ellipsis

The ellipsis is not working for me in VSCode, Mac.

Fira Code:

<img width="186" alt="CleanShot 2020-05-05 at 00 28 01@2x" src="https://user-images.githubusercontent.com/1218446/81035060-4cd49f80-8e67-11ea-9ad4-ee012b63bb12.png">

MonoLisa

<img width="196" alt="CleanShot 2020-05-05 at 00 25 12@2x" src="https://user-images.githubusercontent.com/1218446/81034964-e64f8180-8e66-11ea-83d5-4602f27338cf.png">

**Comment by okonet** [comment]
I disagree with `www` and believe it’s just a gimmick. I personally dislike it and would not add it.

**Comment by F1LT3R** [comment]
@okonet what are your thought's on the Ellipsis not working?

**Comment by F1LT3R** [comment]
@waynehoover - I'm interested to know why you seconded the www ligature, are you writing a lot of markdown documentation? (This is the reason I find it useful)

**Comment by MarcusSterz** [comment]
@F1LT3R 
Ellipsis: in what way ‘not working’? You mean you cannot type it (alt+period) or you mean it does not change automatically into an ellipsis?
MonoLisa has **A** the symbol ‘elipsis’ [...] which uses one space and **B** a triple period ligature which uses 3 spaces (same with Fira Code by the way). If all other ligatures work the triple period ligature will work, too.

www: I agree with @okonet here. To me it does look more confusing than simply writing ‘www’. I’d rather advocate for a symbol for ‘https://’ which is an abomination to my eye ;)

**Comment by waynehoover** [comment]
Yes, I write a lot of markdown and the www ligature would be useful there. As a community we could create our own ligatures to add too, like how https://github.com/kiliman/operator-mono-lig has.

**Comment by F1LT3R** [comment]
@MarcusSterz - what happens when you create a `.js` file with the following...

```js
const a = [...b];
```

... are ligatures used for the triple-dot with MonoLisa for you?

It does not work for me. It's a very common feature of the language that looks great in FiraCode and does nothing in MonoLisa. It's the single most dissappointing thing about MonoLisa to me.

**Comment by okonet** [comment]
It works for me but it's quite subtle I must admit.

![CleanShot 2020-05-06 at 21 17 55](https://user-images.githubusercontent.com/11071/81218813-1588fe80-8fdf-11ea-9ca4-f81f4b509331.gif)

Compared to FiraCode:

![CleanShot 2020-05-06 at 21 19 09](https://user-images.githubusercontent.com/11071/81218902-3f422580-8fdf-11ea-90f5-781d1a44e476.gif)

or JetBrains Mono:

![CleanShot 2020-05-06 at 21 19 56](https://user-images.githubusercontent.com/11071/81218979-5aad3080-8fdf-11ea-86ae-aa6df7501300.gif)

@MarcusSterz what about making it a bit more prominent? I like Jetbrains Mono more than Fira Code TBH.

**Comment by okonet** [comment]
I’d close this issue since it’s not a goal IMO.

**Comment by bebraw** [comment]
Ok, let's close.

If anyone has ligatures in mind to add, please open separate issues with the combinations and a reason for inclusion.
