### ISSUE TITLE
Vertical borders discontinuous

### ISSUE THREAD

**Issue by tiagovla** [MonoLisaFont/feedback#100]
### OS/Terminal/Editor
- Arch;
- Alacritty;
- Neovim.

### Problem
Vertical borders are discontinuous unlike other fonts.

![image](https://user-images.githubusercontent.com/30515389/136682774-4c01cdad-33ca-491b-bbdd-7d695d28d0d3.png)

#### Characters: 
"─", "│", "─", "│", "╭", "╮", "╯", "╰".

**Comment by bebraw** [comment]
Which OS and version of the font are you using?

**Comment by bebraw** [comment]
One more question, are you using otf or ttf? I would recommend otf on Linux/MacOS.

**Comment by tiagovla** [comment]
> Which OS and version of the font are you using?

Arch Linux, v1.8.  Tested with alacritty, but the same happens with xterm.

> One more question, are you using otf or ttf? I would recommend otf on Linux/MacOS.

otf

#### Firacode:
![image](https://user-images.githubusercontent.com/30515389/137042052-9b5455dc-3340-4dec-bc43-1aef5286a53c.png)

I ended up manually stretching the glyth ``u2502`` a little bit to solve it.

**Comment by MarcusSterz** [comment]
@tiagovla The box lines come with sufficient overlap per default. 
<img width="345" alt="Bildschirmfoto 2022-01-26 um 11 54 34" src="https://user-images.githubusercontent.com/51958720/151150879-0aed8b9c-c0bc-4b97-ab38-632ac7598f4a.png">

Which line height did you use?

**Comment by MarcusSterz** [comment]
I have now extended the vertical expansion of all border and block symbols (1500 units). Will be fixed in 1.806.

**Comment by bebraw** [comment]
Fixed and published in 1.806.

**Comment by tiagovla** [comment]
Perfect!
![image](https://user-images.githubusercontent.com/30515389/156135702-a8d98f44-eeb4-407c-af6c-f86a0f196636.png)
