### ISSUE TITLE
Unnecessarily Bold Font

### ISSUE THREAD

**Issue by Christian-Martinez1** [MonoLisaFont/feedback#101]
Does anyone else have the issue of the font being unnecessarily bold/blocky in VS Code?

VS Code Screenshot:
![Code_wcmmozWO3v](https://user-images.githubusercontent.com/43798323/137393612-fea30438-b906-45e1-bcd0-460383a31bff.png)

Screenshot from MonoLisa site:
![msedge_G0S86kcpGh](https://user-images.githubusercontent.com/43798323/137393692-aeca533a-94ee-467f-a066-60186dea4ff2.png)

Ignoring the stylistic italicizing that differs between the two, the font just looks a LOT more pleasing to me on the website playground preview, and just looks messy to me in VS Code. I have tried messing with the font weight, and with the light font, but it didn't really make much of a difference to me. I spent almost 3 hours from downloading of font to when I gave up trying to make the font more pleasing to the eye but couldn't get it to look as smooth or rather, as neat as it looks on the website. 

For example when comparing the first line, the $ basically looks like an S to me as you can't really see the middle line coming out the top, and the word initHighlight seems like it has less space between each letter. After trying to use it for a bit I had to disable the font as it just wasn't doing it for me, I found myself glossing over variables. Has anyone else came across this?

**Comment by bebraw** [comment]
@Christian-Martinez1 When you have time, can you provide the information I was requesting? Make sure to test against the newest version available through https://www.monolisa.dev/orders .

**Comment by Christian-Martinez1** [comment]
Apologies for not replying, I completely forgot to oof.. It was the OTF font, TTF cleared it right up. 

Thanks!
