### ISSUE TITLE
Italic Lowercase 'o' and 'a' Look Similar

### ISSUE THREAD

**Issue by aaronmbos** [MonoLisaFont/feedback#102]
OS: MacOS
Font Version: 1.802
Editor: VS Code
Font Size: 14px

I noticed that the lowercase italic `o` and `a` characters look similar when placed side by side. Wondering if it would be possible to add a "tail" on the lowercase `a` or some other way to make it more distinct when next to the italic `o`.

![Screen Shot 2021-10-14 at 10 39 49 PM](https://user-images.githubusercontent.com/24758740/137428670-67913745-79b3-4ba1-a869-28daa36e8a0f.png)

For example, the word "doable" in the screenshot below contains the `oa` letter combination. I think there is some distinction between the letters, but when reading it quickly or scanning over the words they can appear to be similar.

![Screen Shot 2021-10-14 at 10 32 25 PM](https://user-images.githubusercontent.com/24758740/137428329-8cb05010-8302-4866-9ddc-c144afb690b0.png)

**Comment by bebraw** [comment]
For reference, can you paste a couple of screenshots with different fonts on your system with the same font size? That might give some idea on how to solve this one. Thanks!

**Comment by aaronmbos** [comment]
Some fonts use a slanted version of the regular `a` for italic. I really like the way Operator Mono differentiates the `a` and `o` with a "tail" at the bottom.

![Screen Shot 2021-10-16 at 8 48 46 AM](https://user-images.githubusercontent.com/24758740/137590058-409f0e46-43bc-4bac-8c52-f782051c1741.png)
![Screen Shot 2021-10-16 at 8 50 02 AM](https://user-images.githubusercontent.com/24758740/137590064-94956111-e6a7-4085-8d76-51a90582013f.png)
![Screen Shot 2021-10-16 at 8 51 25 AM](https://user-images.githubusercontent.com/24758740/137590068-0b78b6e0-1a71-401c-8e33-3a6ec65e5046.png)

**Comment by MarcusSterz** [comment]
> Some fonts use a slanted version of the regular `a` for italic. I really like the way Operator Mono differentiates the `a` and `o` with a "tail" at the bottom.

MonoLisa offers this as well with our script variant. But with the upcoming update the italic lower case ‘a’ will be optimized, too.

**Comment by bebraw** [comment]
Published in 1.803.
