### ISSUE TITLE
pricing: non-commercial use with all font weights

### ISSUE THREAD

**Issue by mittalyashu** [MonoLisaFont/feedback#103]
Can you add a new plan non-commercial (usage) with all font-weights?

**Comment by okonet** [comment]
It's a Professional bundle still.

**Comment by mittalyashu** [comment]
"Commercial use" in professional plan increase the price a lot.

That's why I was looking for pricing plan with all options included in professional plan except for "commercial use".

**Comment by okonet** [comment]
It's actually the other way around. In order to make the type as affordable as possible we add restrictions to cheaper bundles.

**Comment by mittalyashu** [comment]
I understand that, I was just looking for all the features included in professional plan, with only personal use.

For example:  If the professional costs $330^ and commercial usage costs $200^. Then I can get the professional plan (only for personal use) for $130^

^ approx. converted to USD from my local currency as shown on monolisa website

**Comment by tnaseem** [comment]
Unless I'm missing something, isn't the Plus plan the one you want (ie. it's the same as Professional but without the commercial usage?

![image](https://user-images.githubusercontent.com/1317345/139832536-276f142b-846f-472a-b7b6-3d70cbfe0b0c.png)

**Comment by mittalyashu** [comment]
@tnaseem It's missing 6 font weights (include 3 italics version) which is not included in "Plus" plan.

**Comment by tnaseem** [comment]
Ah yeah. I misread the first two lines. Thanks for the heads up! :)

**Comment by mittalyashu** [comment]
Any update on this issue? 👀

**Comment by okonet** [comment]
We lowered the price of the professional and will remove the mention of commercial from the website later. Let's close the issue?
