### ISSUE TITLE
More powerline arrows 

### ISSUE THREAD

**Issue by emigdio821** [MonoLisaFont/feedback#104]
Hi, I recently purchased the font (plus variant). Is there any chance to add these arrows or similar ones?
Thanks in advance.

![image](https://user-images.githubusercontent.com/6751108/140669960-a69c6aa6-3bc4-4b8d-a9fb-68e084616ac9.png)

**Comment by okonet** [comment]
Thanks for your feedback! We will look into it. I don't see a reason why we shouldn't add those but I'll let @MarcusSterz investigate first.

**Comment by MarcusSterz** [comment]
Sure, no prob!

**Comment by bebraw** [comment]
Published in 1.803.
