### ISSUE TITLE
Expose older versions of your characters as stylistic variants

### ISSUE THREAD

**Issue by fabiochelly** [MonoLisaFont/feedback#105]
Hi,

Personally (and my whole team agrees with me), I really prefered the original glyphs for ≤ and ≥.
The new ones are stretched to the point that they became ugly and almost unreadable.

I understand that it can be a matter of taste. So is it possible to add old glyphs as stylistic variants so no update could become a regression?

Thanks,
Fabio Chelly

**Comment by emigdio821** [comment]
I second this.

**Comment by fabiochelly** [comment]
As a workaround, is it possible to download the previous version (1.801) without the "stretched" characters? I bought the pro package but I can only download the latest one.

**Comment by okonet** [comment]
We're looking into your suggestions. Meanwhile I'll try to provide links to all versions of the font so you can download the one you want. Sorry for the inconvenience.

**Comment by okonet** [comment]
We have released a new version of the website where you can download past versions of the font: https://www.monolisa.dev/orders

**Comment by fabiochelly** [comment]
Thanks a lot!
