### ISSUE TITLE
Ligature #(

### ISSUE THREAD

**Issue by rphii** [MonoLisaFont/feedback#106]
The ligature `#(` is broken (as in the parenthesis disappears) in vscode and looks as follows:
![image](https://user-images.githubusercontent.com/46871963/141690995-7a7303c1-8010-4e27-b578-fd034ad999a0.png)
(I typed `#()` and left my cursor in the middle to let vscode indicate there is indeed a parenthesis after the `#`)
When checking out the specimen it does not look like that.

I'm using version 1.802 on Windows

**Comment by okonet** [comment]
@MarcusSterz could you please check this out?

**Comment by MarcusSterz** [comment]
Looking into it.
@okonet Have you experienced the same?

**Comment by okonet** [comment]
Nope. I'm also wondering if TTF or OTF file format was installed.

**Comment by MarcusSterz** [comment]
Interestingly I can reproduce it. Still no clear what is hapening here since similar ligs work without a problem.

**Comment by MarcusSterz** [comment]
Alright, found the problem.

**Comment by rphii** [comment]
Weird, now the ligature works fine. (Which to me, it seems like it was a vscode issue...)

**Comment by MarcusSterz** [comment]
Well I did have problems in some apps. So I turned the bracket component into curves. Now it works at least for me. Will be available with the upcoming version.

**Comment by bebraw** [comment]
Published in 1.803.
