### ISSUE TITLE
Right arrows ligatures and ss02 not working in Sublime Text

### ISSUE THREAD

**Issue by sgigou** [MonoLisaFont/feedback#107]
In Sublime Text, I cannot manage to make those ligatures / stylistic sets working. Here is the result:

<img width="323" alt="Screenshot 2021-11-17 at 14 58 19" src="https://user-images.githubusercontent.com/33257100/142214407-8074513a-adc3-476c-9ed1-57f4c070ddc2.png">

My configuration is:

```
{
  "font_face": "MonoLisa",
  "font_size": 14,
  "font_options": [
    "dlig",
    "ss02",
  ],
}
```

Is there any trick? Is it Sublime Text's fault — once again?

**Comment by bebraw** [comment]
Sublime Text doesn't support all font features by design.

Here's a quote from the author ([source](https://forum.sublimetext.com/t/todo-ligatures-in-pragmata-pro-font-not-displaying/47940/7)):

> We don’t send runs of letters or numbers to the font engine, only symbols, so any ligatures involving alphanumerics won’t work.
>
> The reason for this is performance, in regards to caching text layout results from text shaping.

There's more info at the thread.

**Comment by sgigou** [comment]
Thanks for the link. Maybe it can explain the `ss02` problem.

But as written in [this documentation](https://www.sublimetext.com/docs/ligatures.html), it seems that `-`, `=` and `<` are supported characters.

Actually I just noticed that today, working ligatures are inverted… `->` now works, but no longer `<-`… 😞

**Comment by MarcusSterz** [comment]
Interesting. There is no reason why it should not behave accordingly from our side. Also replacing italics with ss02 should work and it does so in other apps.

**Comment by okonet** [comment]
I've just tested Sublime Text and those ligatures work just fine for me. As for font features, we just released a feature to customize your font download: https://twitter.com/monolisafont/status/1503709310915915781

Maybe give it a try? http://monolisa.dev/orders/customize

**Comment by sgigou** [comment]
After a retry, it seems to work now. Maybe it was a bug in SublimeText display.

By the way, thank you very much for the download customization tool, it is awesome!
