### ISSUE TITLE
Allow custom fonts in the website playground

### ISSUE THREAD

**Issue by glenjamin** [MonoLisaFont/feedback#108]
Hello, I just came across your font and I'm tempted by it - but I was hoping to do a side-by-side comparison with my existing font, which has been Monaco for years.

The playground on your site only offers a fixed comparison between 3 other popular fonts - would it be possible to get the option to modify one of the tabs to a local font of my choosing?

I suppose failing that my best bet is to download the free version and try it out in my actual editors?

**Comment by okonet** [comment]
Yeah we have been thinking about this kind of feature for a while. I think that comparing the Trial version locally is the best way for now since I'm not sure if we even can implement this feature for legal reasons (not all fonts are freely available) but we'll investigate later.

**Comment by glenjamin** [comment]
If you take whatever value is enterered and use it directly as the `font-family` CSS property, then it'll use the local font stack of whoever is visiting. This shouldn't affect your font licensing, as you're not distributing anything - just using whatever your visitor has installed.

**Comment by okonet** [comment]
Yes that's exactly how I thought we could solve it but it makes it a bit challenging UI wise :)

**Comment by bebraw** [comment]
We decided not to implement the feature. The tricky part is that even at the best case we could provide only an input field as we don't have access to user fonts in a simple way.

It's much better to download the trial for a better go.
