### ISSUE TITLE
Ligature <<<< and >>>>

### ISSUE THREAD

**Issue by rphii** [MonoLisaFont/feedback#109]
Hello again, I stumbled upon another set of ligatures that look a bit off. Any sequence of eigher < or > with at least 4 consecutive characters looks a bit broken.
![image](https://user-images.githubusercontent.com/46871963/144872316-d4581f9d-922f-4a1e-b324-93c688b098e9.png)

**Comment by okonet** [comment]
@MarcusSterz could you please take a look?

**Comment by dinhquochan** [comment]
@MarcusSterz  I can verify this issue.

![image](https://user-images.githubusercontent.com/9979458/148194160-d4ae42cb-2d98-4b73-a654-6a0c3b088bce.png)

**Comment by MarcusSterz** [comment]
We do not have a quadruple > ligature at this point so thats’s why this looks weird. WIll take a look.
Is ‘>>>>’ a common programming ligature?

**Comment by dinhquochan** [comment]
> We do not have a quadruple > ligature at this point so thats’s why this looks weird. WIll take a look.

I don't know, but i see it on 'conflict commit'

```
1. ======
2. >>>>> ff6df3435231fdff78fwsd83e7dffa0732eft554
```

**Comment by MarcusSterz** [comment]
@mekkablue Rainer, can you give us some advice? A quadruple : is no problem, for example.

**Comment by mekkablue** [comment]
Telling from the screenshot, it appears to be two triples, not a quadruple of greater-than signs. What did you type?

**Comment by MarcusSterz** [comment]
> Telling from the screenshot, it appears to be two triples, not a quadruple of greater-than signs. What did you type? This is what I get when I type sequences of `>`:
> 
> <img alt="image" width="287" src="https://user-images.githubusercontent.com/1103103/152449804-33e73f80-4fcd-4cf9-ad0f-54c4902c4d2f.png">
> 
> Only the double and triple appear to have a different shape.

Interesting. Which browser?
With Firefox I get this:

<img width="286" alt="Bildschirmfoto 2022-02-04 um 14 32 20" src="https://user-images.githubusercontent.com/51958720/152537488-8b9ce1fb-5c43-41b7-a6c7-bfcbcfdff5ca.png">

**Comment by bebraw** [comment]
1.806 is available now.
