### ISSUE TITLE
BoldItalic 6 & 9 don't render properly 1.803

### ISSUE THREAD

**Issue by deankarn** [MonoLisaFont/feedback#111]
I'm on macOS Montery and the 6 & 9 character in BoldItalic do not display properly.

![image](https://user-images.githubusercontent.com/8068371/145434351-32498e3e-cdc6-4060-aff1-9a3d334efbcb.png)

**Comment by bebraw** [comment]
Are you using otf or ttf?

**Comment by deankarn** [comment]
`otf`

**Comment by bebraw** [comment]
Ok, we found the issue. I'll publish a fixed version tomorrow.

**Comment by bebraw** [comment]
Fixed in 1.804 (available now).
