### ISSUE TITLE
The `<`, `>` are weird, low legibility on 13px (macOS with non-retina monitor)

### ISSUE THREAD

**Issue by dinhquochan** [MonoLisaFont/feedback#113]
Dear MonoLisa team,

Ref #38, i mention that in Monitor (1080x1920, non-retina), `<` and `>` is weird, low legibility on 13px, looks screenshot below:

![image](https://user-images.githubusercontent.com/9979458/145920489-a5fa0a4e-9717-4c33-929a-36a4f1a9a693.png)

On 14px, its seem fixed

![image](https://user-images.githubusercontent.com/9979458/145920567-88debe1e-7817-4db7-b2c3-c164f62c83cd.png)

I try another fonts with 13px: Hack, Jetbrains Mono, Iosevka,  Cartograph CF:

![image](https://user-images.githubusercontent.com/9979458/145920865-237176e9-802c-4c45-ae04-86a44108b077.png)
![image](https://user-images.githubusercontent.com/9979458/145920905-d873f119-2460-4107-bb00-2cec2bba8f95.png)
![image](https://user-images.githubusercontent.com/9979458/145920959-51143475-a934-4f0a-9405-fd2194426bea.png)
![image](https://user-images.githubusercontent.com/9979458/145920989-4fa77e4a-1c66-47bc-9b3d-9dd20f8ceba4.png)

I use v1.805 OTF version -  macOS 12

**Comment by MarcusSterz** [comment]
Looking into it. Out of interest: How do the other fonts render in 14 or 12?

**Comment by MarcusSterz** [comment]
@dinhquochan Honestly there is not much we can do. MacOS does Hinting on the fly which means whatever we change on our side, it won’t show. With older monitors there is always problems at some certain size. If we change the size or angle of the `>` we would have to change all of the connected ligatures as well which is a lot of hassle.
