### ISSUE TITLE
Release script version as a separate font

### ISSUE THREAD

**Issue by ms3056** [MonoLisaFont/feedback#114]
Please release the script version as a separate font - it would make things easier for tools such as Logseq.

**Comment by okonet** [comment]
We're about to release a feature that will solve this. Stay tuned!

**Comment by ms3056** [comment]
Awesome! Looking forward to it, thank you for your response!!!!

**Comment by ljdigital-control** [comment]
I would love to see what my website would look like with the script font. Please release this ASAP as I would love to try out. ITs the coolest font I have seen in many a year. It's an epic effort by you all. Keep up the good work ;)

**Comment by Venus007e** [comment]
Yes please, i actaully came to the github to ask the same question. Looking forward to the release!
