### ISSUE TITLE
Legibility of Greek lowercase letters

### ISSUE THREAD

**Issue by gterez** [MonoLisaFont/feedback#115]
![Screenshot of implementations in different monospace fonts](https://user-images.githubusercontent.com/118370/148079545-da60dcff-3d8b-4482-a4af-7f6cfcb55592.jpg)
I have a couple of niggles regarding the readability of some lowercase Greek characters (I’m Greek in case it's not obvious :-)):
- ψ (psi) is my biggest issue, the low stem is highly unusual and creates a situation where ψ looks like ω (omega) when scanning text. Many typefaces use an ascending stem here (or at a minimum have it go up to the mean line), some also choose the classic, more cursive, version of φ (phi) to go with it (vs the more modern form with just a circle and a vertical line) to accentuate the contrast between φ & ψ even more. See Anonymous Pro, Comic Code, Noto Mono & PragmataPro in the screenshot above for different implementations of this. I believe it's the best way to go.
- γ (gamma): the overall small descender height in MonoLisa makes it hard to distinguish γ from ν (nu). γ also looks kind of chopped at the bottom? Some typefaces move the crotch slightly above the baseline to overcome this issue (see Roboto Mono in screenshot). The only fully "correct" implementation here is the one in Comic Code (see screenshot above) but most typefaces (monospace or not!) steer clear of the looping tail design as the loop is quite narrow leaving a very small "eye" which doesn't look good in small sizes, and also the letter has quite a different form from most others messing up the rhythm.
- π (pi): the missing left terminal makes this harder to read, as π always has terminals in monospace fonts (there are sans serif fonts though where the π has no terminals at all, like an uppercase Π). Admittedly this is the least important of the issues and the missing left terminal gives it quite a quirky appearance which I like, I do find that it hinders legibility though. An example:
![words with many πs](https://user-images.githubusercontent.com/118370/148079611-b6b3223c-dcdd-45df-b241-4b0e5993fd03.jpg)

**Comment by okonet** [comment]
Thanks for such great feedback! @MarcusSterz let's take a look and consider it in further updates please.

**Comment by MarcusSterz** [comment]
Thank you @gterez for the insight. Will look into it asap.

**Comment by gterez** [comment]
Didn't expect such a quick response! 😃 Thank you so much, they look great! 
To be honest I'd like to see the new gamma in a block of text to tell how well it works though.

**Comment by gterez** [comment]
Looks good 👍, thanks again!

**Comment by bebraw** [comment]
Fixed and published in 1.806.
