### ISSUE TITLE
VS Code 

### ISSUE THREAD

**Issue by ankidoc** [MonoLisaFont/feedback#116]
MacOS Big Sur latest

Problem: Font not working completely on VS Code.
![CleanShot 2022-01-04CleanShotCleanShot at 21 46 17](https://user-images.githubusercontent.com/81517565/148122129-1eeb333e-6f4b-47c1-9308-f52d96b70d3a.png)
![CleanShot 2022-01-04CleanShotCleanShot at 21 46 48](https://user-images.githubusercontent.com/81517565/148122152-a9e76aeb-1b33-48a8-9279-b55b5c38a36e.png)

the font overall is working but the connecting feature like <> or ### are not working. 

Thanks!

**Comment by bebraw** [comment]
Can you paste your `"editor.fontLigatures"` as well? See https://www.monolisa.dev/faq and "How to enable stylistic sets and the script variant?" (sadly I cannot link directly).

**Comment by ankidoc** [comment]
ah thanks! 
I looked into the link and adding "editor.fontLigatures": true, into the settings.json made it work!
