### ISSUE TITLE
Line height trouble

### ISSUE THREAD

**Issue by rarodja** [MonoLisaFont/feedback#117]
Hi!
Using and evaluating MonoLisa I have seen errors in the line height only using this font, I have tried others fonts and it does not happen, my IDE (VSCode) is a clean installation without modifications, it also happens with any visual color theme, so I discarded the latter, attach two diferent example documents.

![Issue_One](https://user-images.githubusercontent.com/74628132/148988224-73338cb2-04bd-4920-ad06-5e22fbc41189.png)
![Issue_Two](https://user-images.githubusercontent.com/74628132/148988246-4b9612cc-a81f-46cd-a5ce-6eac44e0e1b8.png)

**Comment by bebraw** [comment]
@rarodja Which operating system are you using? Are you using otf or ttf?

@MarcusSterz Do you know what might be causing this?

**Comment by rarodja** [comment]
@bebraw I am using Windows 11, I think the error comes from the file that I had already installed, I have purchased and installed the new files and the error has disappeared, however which is better to install, OTF or TTF? many thanks for your help.

**Comment by bebraw** [comment]
For Windows, ttf is the better choice. Thanks.
