### ISSUE TITLE
Font is bold on Win10

### ISSUE THREAD

**Issue by mayureshs** [MonoLisaFont/feedback#118]
The font is very bold in VSCode on Win10 even with the fontWeight set to 100

![image](https://user-images.githubusercontent.com/1014702/149015566-254f5d7f-f83b-47cb-bdd3-8df4951b7776.png)

**Comment by rarodja** [comment]
That is the minimum weight of the font, I think it cannot be finer, that aspect is what makes it beautiful and improves reading, which is what I personally like the most about it, but each person has their own preferences 😊

**Comment by okonet** [comment]
No, I think it's a bug with the font on windows. Which version (TTF or OTF) have you installed? @MarcusSterz cc

**Comment by rarodja** [comment]
I have the TTF, I have installed the OTF and I see it the same, what is the difference? Could it have something to do with the error I reported? Thank you so much.

**Comment by mayureshs** [comment]
Is there a semi-light version of the font ?

**Comment by okonet** [comment]
@mayureshs What do you mean? There are 7 different weights available but it depends on the bundle you've got. Which did you install on your system? BTW we recommend TTF on windows. @bebraw cc

**Comment by bebraw** [comment]
@okonet It's the trial version based on email.

@mayureshs What's your display resolution? Can you paste a screenshot with another font with weight set to 400? Can you see the problem in other editors as well?

**Comment by MarcusSterz** [comment]
With the trial version it makes no sense to try change the weight since there is ony one available. The screenshot looks OK to me. No issue here from my point of view.

**Comment by mayureshs** [comment]
> @mayureshs What do you mean? There are 7 different weights available but it depends on the bundle you've got. Which did you install on your system? BTW we recommend TTF on windows. @bebraw cc

With Personal bundle how many weights do we get ?

**Comment by mayureshs** [comment]
@MarcusSterz, So to get the 7 different weights do I need to look for the feature "script variant" which is only included in Plus and Professional

**Comment by MarcusSterz** [comment]
@mayureshs 
With the Professional set you get all 7 weights.
