### ISSUE TITLE
Minus symbol (-) should be shorter than Dash (—)

### ISSUE THREAD

**Issue by ginkcode** [MonoLisaFont/feedback#120]
This font is for developer.
How come it can be a programming font when making mistake like this?

Version: 1.602

**Comment by bebraw** [comment]
Can you add a screenshot to illustrate?

**Comment by ginkcode** [comment]
I'm checking the latest version on the playground and the difference is still very small.
Can you detect any difference at `--heading-1:` if I remove the other one?
<img width="630" alt="monolisa" src="https://user-images.githubusercontent.com/9301098/152107871-3feba05e-c08a-47a3-bd7e-7de036db9987.png">

With JetbrainMono, it's much better:
<img width="629" alt="jetbrain" src="https://user-images.githubusercontent.com/9301098/152108460-e3e36d0e-ac15-4b32-84dc-d2b3bd9162ea.png">

**Comment by ginkcode** [comment]
I've made a mistake on SQL query and taken hours to detect the issue just because of the dash (—) where it should be the hyphen (-). 
So I have to come here to raise a feedback.

**Comment by MarcusSterz** [comment]
Before we go on, let’s talk about terminology first.
What @ginkcode calls a ‘minus’ is actually called ‘hyphen’. The real minus is a rarely used mathematical symbol.

<img width="543" alt="Bildschirmfoto 2022-02-02 um 11 00 51" src="https://user-images.githubusercontent.com/51958720/152132707-985d9057-72bd-4492-9272-44a9a66ae400.png">

Nonetheless minus AND hyphen are shorter than the ‘Endash (there are two kinds of dashes: Endash, and Emdash which needs to be even longer, restricted in length by the 640 units width though)

BUT: We can certainly shorten (and possibly thicken) the hyphen to emphasize the difference. What do you think @bebraw ?

**Comment by bebraw** [comment]
It's probably a worthwhile change esp. if all other typefaces are doing it.

**Comment by MarcusSterz** [comment]
Alright! Will be updated next version.

**Comment by okonet** [comment]
I would keep the stroke width intact, though, otherwise we'd need to update all related glyphs like `+` and `=` which are being often used in conjunction with `-`.

**Comment by MarcusSterz** [comment]
> I would keep the stroke width intact, though, otherwise we'd need to update all related glyphs like `+` and `=` which are being often used in conjunction with `-`.

Good point.

**Comment by ginkcode** [comment]
> I would keep the stroke width intact, though, otherwise we'd need to update all related glyphs like `+` and `=` which are being often used in conjunction with `-`.

Sorry I can't figure out how come updating on `+` and `=` can solve the issue I encountered where `1 — 2` is not a valid expression. Just because it's too similar to the hyphen `-`.
In most of IDE the operators are often highlighted by different color. But if we use it in a string like building SQL query it's definitely a potential bug when copy/paste from another rich text editor.

**Comment by krish-r** [comment]
Hello,

One request, please do not make the hyphen too short like JetBrains Mono or Dejavu Sans Mono (it is hard to notice esp. in Dejavu Sans Mono, as a standalone character or even when it is combined with other characters like `=` and numbers).

Attaching other popular monospace fonts (latest version) for comparison:
![image](https://user-images.githubusercontent.com/54745129/152482547-777c665c-e720-4141-a05f-9a36277ae3a7.png) ![image](https://user-images.githubusercontent.com/54745129/152483205-aa4f6118-a2cc-420c-ae1a-ae05354c1b92.png) ![image](https://user-images.githubusercontent.com/54745129/152484311-48c606de-dcab-49ce-8b00-e732f2d72813.png) ![image](https://user-images.githubusercontent.com/54745129/152482261-94d6867d-bac6-4ab2-9d6b-f7366c4c04aa.png) ![image](https://user-images.githubusercontent.com/54745129/152482636-6869c68c-c6a1-4311-b474-bc3b92f0ae7d.png) ![image](https://user-images.githubusercontent.com/54745129/152482767-82554675-3722-4d8c-bb1e-b07cd96bd3bd.png) 

(From the above screenshots, I personally like Fira Code's & MonoLisa's implementation)

**Comment by MarcusSterz** [comment]
> I would keep the stroke width intact, though, otherwise we'd need to update all related glyphs like `+` and `=` which are being often used in conjunction with `-`.

This is how it looks now. The decrease in width of the hyphen is visible though moderate enough so no other symbols will need a change to match it. 
<img width="219" alt="Bildschirmfoto 2022-02-04 um 14 15 44" src="https://user-images.githubusercontent.com/51958720/152535375-b8364ac8-4fc0-44f9-83c2-8d31f15c5025.png">

**Comment by okonet** [comment]
I like it! I'd keep the stroke width the same for all of them though including the emdash

**Comment by MarcusSterz** [comment]
> I like it! I'd keep the stroke width the same for all of them though including the emdash

The emdash is traditionally longer and thinner than the others. We better keep them different.

**Comment by bebraw** [comment]
Fixed and published in 1.806.
