### ISSUE TITLE
No difference in character width in Sublime Text

### ISSUE THREAD

**Issue by sylbru** [MonoLisaFont/feedback#121]
## Background information

* Font edition: Trial version
* Font version: 1.805
* The type of the font file you are using: OTF
* Operating system: Linux Mint
* Display resolution: 1920x1080
* Any other information that might be helpful: Sublime Text build 4126

## Issue

Trying out the trial version in Sublime Text 4, I see strictly no difference in the character width when switching between Fira Code and MonoLisa (as opposed to doing the same in the playground on the website). Yet other fonts do seem to have a different character width (see last screenshot).

On top of each other:
![firacode-monolisa-overlay](https://user-images.githubusercontent.com/3757523/152515422-8616abe9-1453-4cbb-b120-4db935cff53a.png)

Side-by-side:
![firacode-monolisa](https://user-images.githubusercontent.com/3757523/152515391-daad8354-9d57-4d8e-b7f8-8524de0f1d04.png)

Using Free Mono:
![image](https://user-images.githubusercontent.com/3757523/152516358-5496965f-8fc8-49d0-8de8-b92f4beccd80.png)

The font is looking great though, I’m hoping I’ll be able to use it as intended!

I also asked on the Sublime Text support Discord, waiting for answers there.

**Comment by sylbru** [comment]
But maybe it’s my Fira Code that is too wide. Do you have a way of telling from the screenshots if my MonoLisa seems to be the proper width? Please tell me if more info is needed (screenshots, FontForge info…).

**Comment by sylbru** [comment]
Ok so comparing the three fonts above in VS Code vs in Sublime Text, it looks like my Fira Code might be too wide in Sublime Text somehow, making it just as wide as MonoLisa. I guess my MonoLisa has the correct width then!

**Comment by okonet** [comment]
I've tested it as well and it looks like it depends on the font size. For me, setting font size to `16` results in almost identical width, but setting `15` or `17` produces very different line lengths. Check that out:
![CleanShot 2022-02-18 at 10 46 10](https://user-images.githubusercontent.com/11071/154658453-e4b0e7b6-c3e0-426d-802b-3e9c8a56a331.gif)

**Comment by sylbru** [comment]
Oh, interesting! Yeah I guess it’s a Sublime Text issue then, in any case I’m a happy MonoLisa user now :)
