### ISSUE TITLE
Cannot disable coding ligatures in Xcode

### ISSUE THREAD

**Issue by jaanus** [MonoLisaFont/feedback#122]
## Background information

* Font edition (i.e. trial, personal, plus, pro): Professional
* Font version (i.e. 1.805): Not sure. How do I find out? Bought on 2022-02-06. Whatever was current version then.
* The type of the font file you are using (i.e. otf, ttf): OTF
* Operating system (i.e. MacOS, Windows): macOS Monterey 12.2 (21D49)
* Hardware: iMac Retina 5K, 27-inch, 2019
* Display resolution: 5120 x 2880
* Xcode version: 13.2.1 (13C100)

## Issue

It is not possible to disable coding ligatures in Xcode. Specifically let’s talk about the character `->` that is turned into right-arrow with MonoLisa.

In Xcode font settings, there are some typography controls. On the screenshot, you see that I try disabling “common ligatures”. I am not sure if the right-arrow is from this “common ligatures” setting, or any other setting. Disabling the ligatures and changing any other typography settings in this control panel does not seem to do anything for me.

You can see on the screenshot that the right-arrow ligature is visible (which should actually be `->`), even though I have disabled the “common ligatures”. I tried restarting Xcode after changing the setting. The settings in typographic panel do not seem to have any effect.

<img width="1446" alt="Screenshot 2022-02-07 at 09 10 36" src="https://user-images.githubusercontent.com/184253/152745106-c8582bf9-de0b-4e71-96ac-0fe7635a44ef.png">

**Comment by bebraw** [comment]
You can use the font website to remove ligatures from the font now.

See https://twitter.com/monolisafont/status/1503709310915915781 for further info.
