### ISSUE TITLE
Script version doesn't load in sublime text.

### ISSUE THREAD

**Issue by dwhenson** [MonoLisaFont/feedback#123]
I cannot make the script version load naturally in Sublime using the font options. Apparently, it might be because Sublime is particular about character width? I can load it fine in VS Code. 

I have forced the script version to load in Sublime by essentially converting the italic version to the script version so it's not the ned of the world, but I couldn't see another mention of the issue here so thought I would flag it.

Thanks and love the typeface!!

**Comment by nicolaswendling** [comment]
Same issue!
It doesn't work even with VSCode settings from FAQ. 
Please fix it.

**Comment by nicolaswendling** [comment]
> @nicolaswendling What exactly doesn't work? What version and bundle of the font are you using?

@okonet I've just bought **MonoLisa Plus** with script variant feature.

Script variant doesn't display in Sublime.
I succeed to display it in VSCode but impossible to use it with Sublime.

I set up with these options in `preferences.sublime-settings` user file.

`font_options": [ "gray_antialias", "calt", "liga", "clig", "ss02", ]`

Italic font style is displayed but script variant isn't used while I've set up font-options with `ss02` as it's written in the FAQ.

 So maybe I forgot to do something.

**Comment by okonet** [comment]
I assume Sublime doesn't support some open type features. We will provide a separate download for the script version soon. Stay tuned.

**Comment by dwhenson** [comment]
I think Sublime does support open type features, in this case I think it should work in Sublime under the ss02 option. I think it might be because the script font is not strictly monospace?

**Comment by dwhenson** [comment]
Sounds good

**Comment by bebraw** [comment]
We just launched a service that lets you write script to the font itself as the default option. This avoids the trouble with Sublime Text in this case.

Also see https://twitter.com/monolisafont/status/1503709310915915781 .

**Comment by dwhenson** [comment]
Just came back to check for progress - this is perfect. Thank you!
