### ISSUE TITLE
May I have a license to your fonts so that I can get them to work in otfinst?

### ISSUE THREAD

**Issue by jowens** [MonoLisaFont/feedback#124]
Hi, I built a tool called [otfinst](https://ctan.org/pkg/otfinst?lang=en) for use in installing OpenType fonts into LaTeX. I have never tested such a tool with a monospace font with so many variants and I'd like to make sure the tool works with your variants. Would you consider issuing me a license for testing?

**Comment by bebraw** [comment]
I believe [the trial version](https://www.monolisa.dev/buy/661578) would be enough for testing as it includes the basic characteristics of the fonts while missing many of the characters and special features.

I recommend checking out open source alternatives like Fira Code, JetBrains Mono, Cascadia Code, or Victor Mono to further improve your test suite.
