### ISSUE TITLE
How to set alternative fonts in terminal on vscode

### ISSUE THREAD

**Issue by fz6m** [MonoLisaFont/feedback#125]
## Background information

* Font edition (i.e. trial, personal, plus, pro): `plus`
* Font version (i.e. 1.805): `1.805`
* The type of the font file you are using (i.e. otf, ttf): `otf`
* Operating system (i.e. MacOS, Windows): `MacOS`

* IDE：`vscode`

## Issue

How to use the alternative fonts of `ss01` ... `ss*` in the terminal ?
I don't seem to find a configurable way on vscode

<img width="70%" alt="image" src="https://user-images.githubusercontent.com/59400654/153989873-7eaaf540-439b-4c18-802e-11d001a5233f.png">

↑ I hope this `g` is `ss04` alternative font

**Comment by bebraw** [comment]
Please see https://www.monolisa.dev/faq .
