### ISSUE TITLE
Weird behaviour with multiple hyphens

### ISSUE THREAD

**Issue by leonbreedt** [MonoLisaFont/feedback#126]
We welcome any feedback regarding technical issues (broken letters, ligatures not working, bad spacing etc). We will have a look and try to implement the changes in future versions.

---

## Background information

To help debugging, fill the following information before describing the issue:

* Font edition (i.e. trial, personal, plus, pro): **Plus**
* Font version (i.e. 1.805): **1.805**
* The type of the font file you are using (i.e. otf, ttf): **otf**
* Operating system (i.e. MacOS, Windows): **macOS**
* Display resolution (i.e. 3072x1920): **1920x1080@2x** (display resolution is 3840x2160)

## Issue

Three or more hyphens (`-`) seem to have some rendering issue where some of the hyphens are rendered really small.

Terminal is Kitty.

**Two hyphens (OK)**

<img width="220" alt="Screen Shot 2022-02-17 at 11 16 17 AM" src="https://user-images.githubusercontent.com/167841/154366699-c0e9e72d-0f29-413b-8426-cf07eff5f4c9.png">

**Three hyphens (Not OK, looks like four?)**

<img width="195" alt="Screen Shot 2022-02-17 at 11 16 23 AM" src="https://user-images.githubusercontent.com/167841/154366694-8fca7ba3-4565-48ba-b30a-f481e5ebc02b.png">

**Many hyphens (Hmm)**

<img width="331" alt="Screen Shot 2022-02-17 at 11 16 27 AM" src="https://user-images.githubusercontent.com/167841/154366688-bb605a77-2700-4953-908d-240b5cf5433e.png">

**Comment by leonbreedt** [comment]
Closing, looks like it will be fixed soon by a new build of Kitty as mentioned in https://github.com/MonoLisaFont/feedback/issues/15.

**Comment by tiagovla** [comment]
@leonbreedt did you manage to solve it? That's the only thing keeping me from using kitty.

**Comment by leonbreedt** [comment]
@tiagovla i only got it working by disabling ligatures (`disable_ligatures always`). latest release of Kitty didn't fix it without this config :( would prefer not to lose ligatures, but oh well.

**Comment by tiagovla** [comment]
> @tiagovla i only got it working by disabling ligatures (`disable_ligatures always`). latest release of Kitty didn't fix it without this config :( would prefer not to lose ligatures, but oh well.

I tried to change the size of that ligature to the same size of the arrow ligature, but it still breaks. I ended up removing it (hyphen_hyphen.liga) with [FontForge](https://fontforge.org/en-US/) till it gets fixed.
![image](https://user-images.githubusercontent.com/30515389/159105811-d4e3f984-9c39-433e-b0e0-515a387647b5.png)
