### ISSUE TITLE
No ligatures for trial version on (M1) Mac 

### ISSUE THREAD

**Issue by codecapitano** [MonoLisaFont/feedback#127]
Hi MonoLisa team,

currently using the trial version of the Font on a M1 Mac but Ligatures won't show.
Apps I tested: VsCode, Intellij, Terminal. 

---

## Background information
* Font edition: trial
* Font version: ? (latest trial as of Feb. 19.)
* The type of the font file you are using: otf
* Operating system: MacOS Montery 12.2.1 / Apple M1 Pro
* Display resolution: 16-inch (3456 × 2234)
~* Any other information that might be helpful: TODO~

## Issue

currently using the trial version of the Font on a M1 Mac but Ligatures won't show.
Apps I tested: VsCode, Intellij, Terminal. 

To double check my setup I installed Fira Code where ligatures showed up. 

## Screenshots

Each with a Fira Code / MonoLisa

### Terminal  
<img width="650" alt="Screen Shot 2022-02-19 at 09 54 30" src="https://user-images.githubusercontent.com/47627413/154794198-8cfaa6e2-c4e2-42b8-b2b6-193474cd504f.png">
<img width="655" alt="Screen Shot 2022-02-19 at 09 54 00" src="https://user-images.githubusercontent.com/47627413/154794200-3f8af61f-32b3-4b3a-983d-d8967216df3a.png">

### VsCode
<img width="635" alt="Screen Shot 2022-02-19 at 09 55 53" src="https://user-images.githubusercontent.com/47627413/154794216-8fda4a3c-bdfc-4fa1-b08e-f7da82fe54a8.png">
<img width="614" alt="Screen Shot 2022-02-19 at 09 56 09" src="https://user-images.githubusercontent.com/47627413/154794217-68eb096d-dfed-475f-b004-73bb4f51029e.png">

### Installed fonts
<img width="711" alt="Screen Shot 2022-02-19 at 09 57 15" src="https://user-images.githubusercontent.com/47627413/154794231-964a9441-a06f-4e33-b058-36fb17abd993.png">

**Comment by okonet** [comment]
Ligatures aren't included in the trial version.
