### ISSUE TITLE
Upgrade Pricing Option?

### ISSUE THREAD

**Issue by F1LT3R** [MonoLisaFont/feedback#13]
It would be wonderful to see an upgrade option for customers who purchased the basic option and wanted to purchase the other weights.

I would like to buy the basic as a trial, and then upgrade if I find I like the font.

I mostly program with the thinest version of fonts, because I find them easier to scan. If it was possible to buy the weights individually, you may find more people buy the font. There can be a lot of value in a larger user-base over a greater gain per user.

**Comment by okonet** [comment]
We can offer that on per-request basis by giving you a discount for the second purchase. Please write us an email from/with the email you used to purchase and I'll issue a discount code for you.
