### ISSUE TITLE
Unlisted ligature &>

### ISSUE THREAD

**Issue by jsngalloway** [MonoLisaFont/feedback#134]
## Unlisted ligature ( &> )
When ligatures are enabled the symbols & and > combine to form 
![image](https://user-images.githubusercontent.com/41742410/157901928-87eaab70-8275-4b0c-90bb-fc316862cc5c.png)

This is not documented on the website under: https://www.monolisa.dev/specimen (liga or calt)

#### Usage
While this specific ligature has advantages when writing shell code, redirecting i/o for example, it does not play as well with c++ where templates are often declared with a reference.
✅ Bash script:
![image](https://user-images.githubusercontent.com/41742410/157903055-f476f5f9-4be5-40ad-8f03-61f91fd2e728.png)

😟 Cpp Template param:
![image](https://user-images.githubusercontent.com/41742410/157903220-ffb0147c-1e68-4253-81e4-c06710eab9ca.png)

Is this ligature intentional? Should it be added to the website? Should it be removed from the font?

---

## Background information

To help debugging, fill the following information before describing the issue:

* Font version (i.e. 1.805): 1.805
* The type of the font file you are using (i.e. otf, ttf): ttf
* Operating system (i.e. MacOS, Windows): windows/linux

**Comment by bebraw** [comment]
@jsngalloway Do you know how other fonts like Fira Code handle this one? I wonder if the bash specific ligatures should live behind something like a `bash` set. I can see how it's tricky for the cpp case.

**Comment by lovelymono** [comment]
@bebraw Fira Code handles that one by simply not having this ligature.

**Comment by jsngalloway** [comment]
No matter how this is handled it needs to be documented. This character isn't currently included in the set of ligatures detailed on the monolisa website

**Comment by bebraw** [comment]
Yup, agreed. It's missing from the specimen page. I think it was introduced when the Bash characters were added.

**Comment by okonet** [comment]
This will be fixed in https://github.com/MonoLisaFont/website/issues/532

**Comment by bebraw** [comment]
This has been done. Please see the redesigned https://www.monolisa.dev/specimen .
