### ISSUE TITLE
Custom Font download does not seem to work 

### ISSUE THREAD

**Issue by vikky49** [MonoLisaFont/feedback#135]
I have a paid version of the code alt ligatures. I can email you my order number if you want. I am trying to customize it and download it. The UI says "Requesting Font" but fails with a cross mark. 

This is how I configured

<img width="915" alt="1" src="https://user-images.githubusercontent.com/180512/158409711-c3188c43-7f26-4bd7-b944-e36a411d4b77.png">

This is the error message
<img width="532" alt="MonoLisa - Customize your font 2022-03-15 08-10-40" src="https://user-images.githubusercontent.com/180512/158409290-2c0cd111-5985-4c79-b75a-9401dc87900f.png">
png">

When I got to my orders I see a different order number like 

b7459525420240ea9d89b56282ffa607

I think the system is getting confused may be probably with the very first order I purchased before upgrading it to Plus

**Comment by vikky49** [comment]
Here are my orders from my email
<img width="638" alt="Spark - vikky49@gmail com 2022-03-15 08-24-59" src="https://user-images.githubusercontent.com/180512/158412249-2be41f66-e89b-4bda-ad94-5eefdad43c6c.png">


My email id is - vikky49@gmail.com

Please let me know

**Comment by okonet** [comment]
Just a FYI: I removed redacted your email so it's not exposed in public. I'm also seeing something wrong on our end and I'm investigating it now. I'll close the issue when it's resolved. Thanks for reporting!

**Comment by okonet** [comment]
PR is in the review. We will release the fix very soon.

**Comment by okonet** [comment]
@vikky49 please try again. The issue should be fixed now.
