### ISSUE TITLE
Ligature <> is broken after adding a brace 

### ISSUE THREAD

**Issue by vikky49** [MonoLisaFont/feedback#136]
Ligature <> is broken when there is a bracket added in Java code. Here are the examples

This is how it looks when there is a brace added.

<img width="442" alt="1" src="https://user-images.githubusercontent.com/180512/158468333-a4d1399f-aaee-462d-8eef-40a626d5003c.png">

This is how it looks when the brace is moved by a space.

<img width="401" alt="2" src="https://user-images.githubusercontent.com/180512/158468437-6fc0b3c5-2f3a-492d-94d3-0c8e60cc034e.png">

Expected: 
It should still work with the brace next to the ligature. Here is the example from JetBrains Mono font 

<img width="443" alt="3" src="https://user-images.githubusercontent.com/180512/158468574-7424301a-a5b2-492c-9987-b536b211a33f.png">

**Comment by MarcusSterz** [comment]
@mekkablue Can you have a look?

**Comment by MarcusSterz** [comment]
These two ligatures are in conflict when written subsequently. 
<img width="158" alt="Bildschirmfoto 2022-04-04 um 12 45 03" src="https://user-images.githubusercontent.com/51958720/161528201-7e1b79b9-403c-4616-b5a4-8a156faf6a82.png">
Both are `calt` ligatures.
If we move `<>` to `liga`(which makes sense by appearance) this would help since you could at least chose to have only one activated.
What do you think @okonet @bebraw ?

**Comment by okonet** [comment]
I think a more appropriate solution would be to introduce a third ligature `<>(` or drop `>(`

**Comment by MarcusSterz** [comment]
> I think a more appropriate solution would be to introduce a third ligature `<>(` or drop `>(`

Both no problem. Let me know. But remember we have `<(` as well so we would have to delete that one, too.

**Comment by bebraw** [comment]
I would drop `>(` from `calt` as I could imagine constructs like `<>{` or `<>[` or something else depending on `<>` (common syntax for a template) and then you would have to accommodate for these if and when reports come.

What's the original reasoning for supporting `>(`? If it's still good to have, then it feels like a character variant to enable separately.

**Comment by vikky49** [comment]
Any idea on when this would be fixed. just asking out of curiosity

**Comment by okonet** [comment]
I'd suggest we go with adding `<>(` and other bracket combinations to `calt` to make a non-breaking change. 

We can re-consider removal later. 

WYT @MarcusSterz?

**Comment by MarcusSterz** [comment]
Yes let’s try that.

**Comment by MarcusSterz** [comment]
Delaying this for now.

**Comment by MarcusSterz** [comment]
@okonet @bebraw We have `<(` , too. for reasons of consistency we should delete this lig as well.

**Comment by bebraw** [comment]
@MarcusSterz Ok, makes sense.

**Comment by MarcusSterz** [comment]
Ligatures  `<(`  and `>(` will be not available in the upcoming version due to conflicts with `<>`.

**Comment by vikky49** [comment]
Just curious , is this fixed ?

**Comment by bebraw** [comment]
It will be fixed in the next release (under preparation).
