### ISSUE TITLE
Download link from order page failing with 500 error

### ISSUE THREAD

**Issue by tje** [MonoLisaFont/feedback#137]
## Background information

To help debugging, fill the following information before describing the issue:

* Font edition (i.e. trial, personal, plus, pro): pro
* Font version (i.e. 1.805): 1.7 (I'm a bit behind)

## Issue

Ahoy! I'm having trouble downloading a later version of the font from the orders page. Clicking the general "download" button spins for a few seconds before propping up a notification at the top of the page with nothing more than a red "X" in it. The customize tool seems to work though.

Also tried requesting specific versions: 1.807, 1.806, same error

Response body reads something along these lines:

> This Serverless Function has crashed.
> 
> Your connection is working correctly.
> 
> Vercel is working correctly.
> 
> 500: INTERNAL_SERVER_ERROR
> Code: FUNCTION_INVOCATION_FAILED
> ID: sfo1::6bv6l-1647989465188-04a6c4246665

**Comment by bebraw** [comment]
@tje Can you try it now? As far as I understand, GitHub had serious downtime and that might have affected the downloads since they are hosted on their infrastructure.

**Comment by tje** [comment]
Hey! I tried it again this morning, also tried purging my session and logging back in first, but still getting the same red "X" toaster / 500 `FUNCTION_INVOCATION_FAILED` response

Could it be something related to my account maybe?

**Comment by okonet** [comment]
Can you please email me your email and order id to info@monolisa.dev and I'll take a look. Thanks!

**Comment by okonet** [comment]
@tje we just released a new UI for downloading the font that fixes this problem. Please try it out and let us know if you have any issues. Thanks!
