### ISSUE TITLE
Trouble understanding availability of font customization with Personal bundle

### ISSUE THREAD

**Issue by zakora** [MonoLisaFont/feedback#139]
## Background information

To help debugging, fill the following information before describing the issue:

* Font edition (i.e. trial, personal, plus, pro): personal
* Font version (i.e. 1.805): –
* The type of the font file you are using (i.e. otf, ttf): –
* Operating system (i.e. MacOS, Windows): –
* Display resolution (i.e. 3072x1920): –
* Any other information that might be helpful: –

## Issue
I am interested in buying Monolisa Personal edition, I haven't bought it yet.
I'd like to use it with the slashed zero version. However, I will be using the font in software that doesn't support OpenType features. The "customize font build" is marked as not available for the Personal edition, which leads me to think only 1 font file is provided in this bundle, as opposed to being able to get one with the slashed zero for example.

Is it correct that in my particular case it will not be possible to use Monolisa with slash zero?

**Comment by bebraw** [comment]
The customize tool is limited to plus/pro packages at the moment.

You could try using https://github.com/twardoch/fonttools-opentype-feature-freezer to apply the alternate zero to the font files.

**Comment by zakora** [comment]
Thanks, that clarify things a bit 😃 !

Do I understand correctly that the Personal edition contains exactly 1 OTF file and 1 TTF file?
The TTF file being "freezed" with the default Monolisa variants. Whereas the OTF would make the slashed zero available either in application that support OpenType features, or alternatively with https://github.com/twardoch/fonttools-opentype-feature-freezer.
And on the other hand, the Plus and Pro editions give access to an easy to use tool to bake the font with the user selected variants.

**Comment by bebraw** [comment]
The personal edition contains regular and bold weights in separate files for each format (otf, ttf, woff, woff2).

Feature freezing works even with ttf and it's not limited to otf as far as I understand.

Plus and pro provide a simple UI for font modifications, yup, but the freezer tool I linked can do more or less the same.

**Comment by zakora** [comment]
Thanks, I have all the info I need then 😃 !

<hr>

Here is a small suggestion of what could be added in the Monolisa FAQ:

**What files are included in the Personal edition?**
The Personal edition comes with the following files:
- 1 TTF file for Monolisa Regular
- 1 TTF file for Monolisa Bold
- 1 OTF file for Monolisa Regular
- 1 OTF file for Monolisa Bold
- 1 WOFF file for Monolisa Regular
- 1 WOFF file for Monolisa Bold
- 1 WOFF2 file for Monolisa Regular
- 1 WOFF2 file for Monolisa Bold
