### ISSUE TITLE
Ligatures in intellij idea appear distorted.

### ISSUE THREAD

**Issue by eduardo-valenzuela** [MonoLisaFont/feedback#14]
Ligatures like the triple equal appear distorted in intellij idea, the editor shows a thick line at the top and two thin lines at the bottom instead of showing them with equal thickness.

**Comment by okonet** [comment]
Please provide a screenshots and versions of OS and Idea.

**Comment by mattdkerr** [comment]
duplicate of issue https://github.com/MonoLisaFont/feedback/issues/19

**Comment by bebraw** [comment]
Let's close as duplicate of #19 (assuming it's Windows).
