### ISSUE TITLE
Easier way to request a student discount

### ISSUE THREAD

**Issue by jahirfiquitiva** [MonoLisaFont/feedback#140]
Hello,

I wanted to ask if you could add an easier way to request a student discount. Last week I sent an email and haven't got any response.

Additionally I wanted to ask if it's possible to add parity / location-based discounts.

Thanks in advance!

**Comment by bebraw** [comment]
> I wanted to ask if you could add an easier way to request a student discount. Last week I sent an email and haven't got any response.

Can you send a request to students@monolisa.dev ?

> Additionally I wanted to ask if it's possible to add parity / location-based discounts.

This has been done already.

**Comment by bebraw** [comment]
@jahirfiquitiva I see you requested discount already. Did you check your spam? I also sent another message just in case.

How would you simplify the process?

**Comment by bebraw** [comment]
> Probably something where we can submit our education email and receive the code directly to that email, without requiring human interaction, or at least mentioning explicitly that your emails might fall in spam, so that we are aware and don't accidentally miss them.

There was some configuration issue in mail so they shouldn't go to the spam anymore.

> Has it? How can I view the discount applied to my country? How can I know if the price shown is a promo or a location-based discount?

This depends on [Paddle](https://www.paddle.com/). They have their limitations and technically it's per currency. It's a technical limitation we cannot solve without changing the entire payment flow.

> Why is that? Any chance of allowing it for the Plus option at least? The Personal option does not include the script variant 😕

It's limited to personal due to historical reasons and this is unlikely to change. This also keeps the price point of the student version very affordable.

**Comment by jahirfiquitiva** [comment]
> They have their limitations and technically it's per currency. It's a technical limitation we cannot solve without changing the entire payment flow.

Then would you be open to offer the additional discounts for countries upon request, similar to the student discounts? Because based on the currency seems like not a significative discount for Colombia, compared to the ones offered by Wes Bos 🤔 

And also, does it mean, should it show my currency (COP - Colombian Pesos) as I'm in Colombia? if so, why is it showing dollars? 🤔

**Comment by bebraw** [comment]
> Then would you be open to offer the additional discounts for countries upon request, similar to the student discounts? Because based on the currency seems like not a significative discount for Colombia, compared to the ones offered by Wes Bos 🤔
>
> And also, does it mean, should it show my currency (COP - Colombian Pesos) as I'm in Colombia? if so, why is it showing dollars? 🤔

This might be a limitation on Paddle side as they support only a fraction of all currencies available. When a currency isn't supported by their system, they use a fallback currency instead.

**Comment by bebraw** [comment]
> Then would you be open to offer the additional discounts for countries upon request, similar to the student discounts?

It would be too much work to support this.
