### ISSUE TITLE
Allow alternate >= and <=

### ISSUE THREAD

**Issue by bebraw** [MonoLisaFont/feedback#141]
Since #85 was fixed and => width was tweaked to be consistent with other combinations, there have been several requests to restore the previous solution. This might be a good spot for a character variant or a stylistic set to be enabled through the customization UI.

**Comment by okonet** [comment]
I'd prefer going back to the previous variant TBH. I don't like the current look at all. We can add what we have now as a variant and allow freezing. This will increase the amount of features to choose from too.

**Comment by bebraw** [comment]
Yeah, that would be a good way to go.

**Comment by MarcusSterz** [comment]
Will be available as discussed in the next version.

**Comment by josh-collinsworth** [comment]
Just a suggestion, but: if a ligature that's two characters wide is desired, a whole new symbol might be better. Maybe something that still mimics the original characters (similar to, for example, the `=>` or `>-` ligatures, which closely resemble the original glyphs, but joined).

I can't speak for anyone else, but for me personally, how the ligature looks stretched is what's bothersome. A _different_ ligature that's two characters wide could still be cool, if a wide ligature is a priority.

I also like the old, one-character-wide ligature, too. Just tossing out the suggestion.

**Comment by bebraw** [comment]
Fixed in 2.0 prerelease.
