### ISSUE TITLE
Allow disabling `#{`, `#(`, `#[` and `]#` ligatures

### ISSUE THREAD

**Issue by lovelymono** [MonoLisaFont/feedback#142]
## Background information

To help debugging, fill the following information before describing the issue:

* Font edition (i.e. trial, personal, plus, pro): Personal
* Font version (i.e. 1.805): 1.808
* The type of the font file you are using (i.e. otf, ttf): OTF
* Operating system (i.e. MacOS, Windows): Linux
* Display resolution (i.e. 3072x1920): 2560x1440@2x
* Any other information that might be helpful: N/A

## Issue

Currently MonoLisa has ligatures for `#{`, `#(`, `#[` and `]#` in the `liga` set, which means that they get enabled if I want to use ligatures at all. I just don't really like how they look, and they aren't really helpful to me, so it could be nice if there was an option to disable them:

![grim_1649171128](https://user-images.githubusercontent.com/99364286/161785100-302a1005-6e42-422c-9536-eaad982af511.png)
![grim_1649171140](https://user-images.githubusercontent.com/99364286/161785107-a34ac3e9-9a0c-4cc6-b8f6-d8051f204ddb.png)

I tried patching the font in FontLab, moving these ligatures substitution tables responsible for these ligatures to a `dlig` set, which *worked*, but it also broke some other ligatures (such as `>>(`, for some reason).

It would be nice if they could be moved to a stylistic set (`ss##`) or to a `dlig` set, which isn't enabled by default in most contexts.

**Comment by okonet** [comment]
Yeah I agree, let's drop them from `calt` and move to a special set.

**Comment by bebraw** [comment]
We discussed this further and agreed to remove `#{,` `#(`, `#[` and `]#` from the typeface.

**Comment by MarcusSterz** [comment]
Will be removed in the upcoming version.

**Comment by numbpad1** [comment]
It turned out to be a font issue, I thought it was an editor issue. 

I agree to remove it.😂😂😂

**Comment by bebraw** [comment]
This has been done in 2.0 prerelease.
