### ISSUE TITLE
student discount upgrade

### ISSUE THREAD

**Issue by HuaDeity** [MonoLisaFont/feedback#148]
Can't student discount order upgrade to plus or professional version?It shows me that.
<img width="552" alt="截屏2022-04-28 21 18 16" src="https://user-images.githubusercontent.com/64831499/165761127-a5247c77-1808-4a16-868e-43d9068249a5.png">

**Comment by bebraw** [comment]
What's your order id?

**Comment by bebraw** [comment]
This is getting handled elsewhere so I'm closing it here.
