### ISSUE TITLE
At least one latin letter not properly implemented ( æ )

### ISSUE THREAD

**Issue by aakast** [MonoLisaFont/feedback#149]
We welcome any feedback regarding technical issues (broken letters, ligatures not working, bad spacing etc). We will have a look and try to implement the changes in future versions.

---

## Background information

To help debugging, fill the following information before describing the issue:

* Font edition (i.e. trial, personal, plus, pro): trail
* Font version (i.e. 1.805): Newest as of writing, maaan. Where do I find that?
* The type of the font file you are using (i.e. otf, ttf): otf
* Operating system (i.e. MacOS, Windows): Arch - Linux
* Display resolution (i.e. 3072x1920): 1920x1080
* Any other information that might be helpful: TODO

## Issue

![2022-04-28-14:38:11-screenshot](https://user-images.githubusercontent.com/9084464/165776021-34769439-c552-46ee-861a-0d7dcd16f608.png)

**Comment by MarcusSterz** [comment]
The trial version has a reduced character set. The `ae` shown is a fallback font.
