### ISSUE TITLE
Feature Request: Adding the previous version of curly braces {} as a character variant

### ISSUE THREAD

**Issue by krish-r** [MonoLisaFont/feedback#150]
Hello,

Could you please consider adding back the previous version of the curly braces `{}` (i.e. the variant prior to v1.700) as a character variant? 
(As mentioned in #141, we'll have more than one variant to choose from)

Previous version (prior to v1.700):
![image](https://user-images.githubusercontent.com/54745129/166135285-8622ba50-57e2-4c0d-807c-d0cea98b7778.png)

Current version:
![image](https://user-images.githubusercontent.com/54745129/166135295-b8edf8a7-dc58-4973-aece-70f551dcee54.png)

Thanks

**Comment by MarcusSterz** [comment]
Will be available as `cv` in the upcoming version.

**Comment by bebraw** [comment]
Published and included to 2.0.
