### ISSUE TITLE
Ligature '///' on Linux might be broken

### ISSUE THREAD

**Issue by mbuczko** [MonoLisaFont/feedback#151]
Hey, I'm using `///` ligature for Rust docstrings and it behaves really weird (at least on Linux with Emacs). Hard to describe  it with words (triple slashes somehow get replaced by double ones), so please have a look at attached recording :)

https://user-images.githubusercontent.com/586537/168492893-62e25f41-dc2b-4faf-a7dd-c7e1f15713d2.mp4

This does not happen with other fonts (like JetBrains Mono or FiraCode) so, I guess, it might be related directly to MonoLisa.

(edit: MonoLisa version 1.808)

**Comment by okonet** [comment]
@mekkablue any idea what could cause this?

**Comment by bebraw** [comment]
@mbuczko I cannot guarantee it will fix it but out of curiosity you could try 2.0 prerelease available through [the orders page](https://www.monolisa.dev/orders).

I wonder if it's an issue related to ligatures somehow.

**Comment by mbuczko** [comment]
Unfortunately, 2.0-prelease behaves the same. And yes, it's definitely a ligature problem. What's interesting, it happens only for 3 characters-based ligatures (like `///` or `-->`). In all these cases a most-right character is erased as on recording above.

**Comment by bebraw** [comment]
@MarcusSterz Do you think removing these two three character ligatures would be an option?

**Comment by mbuczko** [comment]
Honestly, having no 3-character ligatures would be a big loss for MonoLisa, I think - I'd rather keep them, even if they're buggy on emacs (which is probably 0.0001% of use-case).

Out of my curiosity (and by all means I'm not an expert in fonts), how eg. FiraCode deals internally with this kind of ligatures? It all works perfectly for this font.

**Comment by bebraw** [comment]
@mbuczko Yeah, it would be a bummer.

I was reading up on Emacs and it seems at least in 2020 getting ligatures to work there was somehow tricky.

I wonder what's the difference with Fira Code as it works there. I know both are authored with the same app so I imagine it's some setting that's wrong somewhere.

**Comment by okonet** [comment]
I agree we shouldn't remove something if we can fix it.

**Comment by bebraw** [comment]
@MarcusSterz It's worth checking if the LIGSPACE (ordering) fix will deal with this one as well. Just CC'ing you so we won't forget.

**Comment by MarcusSterz** [comment]
> @MarcusSterz It's worth checking if the LIGSPACE (ordering) fix will deal with this one as well. Just CC'ing you so we won't forget.

I have put `///` before `//` in the script. Often this does the trick.

**Comment by bebraw** [comment]
This has been done in 2.004.
