### ISSUE TITLE
Fonts are not mono-spaced (i.e. equal width across ALL characters)

### ISSUE THREAD

**Issue by vinorodrigues** [MonoLisaFont/feedback#152]
## Background information

Playing around with your font at https://www.monolisa.dev/playground and disappointed that the characters do not align for the following code block in the "Java" code sampler.  *(The other fonts do.)*

```txt
// ┌───┬───┬───┬───┐
// │XXX│AAA│BBB│CCC│
// ├───┼───┼───┼───┤
// │---│---│---│---│
// │   │   │   │   │
// └───┴───┴───┴───┘
```

To help debugging, fill the following information before describing the issue:

* Font edition (i.e. trial, personal, plus, pro): Your website
* Font version (i.e. 1.805): 1.808 (?)
* The type of the font file you are using (i.e. otf, ttf): WOFF (?)
* Operating system (i.e. MacOS, Windows): macOS
* Display resolution (i.e. 3072x1920): 2560x1440
* Any other information that might be helpful: nil

## Issue

Fonts are not mono-space (i.e. equal width across ALL characters)

![image](https://user-images.githubusercontent.com/366673/168924960-69ae4ed6-8fc0-4f01-bc5f-1206843b63b0.png)
![image](https://user-images.githubusercontent.com/366673/168924997-90cb64fb-dd6a-4e75-9bd8-8a2234408ea8.png)

**Comment by bebraw** [comment]
I think the issue is restricted to the playground. Here's a render from VS code with ligatures enabled:

<img width="196" alt="Screen Shot 2022-05-18 at 7 22 13" src="https://user-images.githubusercontent.com/166921/168956662-ad1dc609-ecd2-4f29-961a-adae6a0e388c.png">

Did you try with the trial as well on your computer?

**Comment by vinorodrigues** [comment]
is it the same in italics?  i have italics comment style in my editor.

**Comment by bebraw** [comment]
Ok, I can confirm the issue now. Screenshot below:

<img width="189" alt="Screen Shot 2022-05-18 at 9 24 20" src="https://user-images.githubusercontent.com/166921/168971397-55eabc14-0c4a-4220-839c-a75ba814ce02.png">

For future reference, I use `"editor.fontFamily": "MonoLisa-RegularItalic",` in VS Code to test as it sets it to italic globally (easy to test).

**Comment by MarcusSterz** [comment]
After looking into it I can say this: 
– It is not broken in Glyphs, looks just fine (no matter if `liga` or `calt` are activated or not) – also share the same width of 640 units.

<img width="962" alt="Bildschirmfoto 2022-05-23 um 12 38 21" src="https://user-images.githubusercontent.com/51958720/169801758-9a334d33-9e7f-4b27-b926-083e6808725b.png">


– Other fonts (Fira Code, Source Code, Jetrbains Mono) show the same issue  in Playground:

<img width="792" alt="Bildschirmfoto 2022-05-23 um 12 30 31" src="https://user-images.githubusercontent.com/51958720/169800510-465afca4-6073-460c-b403-9fe32ff8ada7.png">

**Comment by MarcusSterz** [comment]
Found some rogue letter space in hyphen in one italic master. Will be fixed in upcoming version.
This does not explain the other phenomena though.

**Comment by okonet** [comment]
@MarcusSterz are you using italics when checking it out in Glyphs?

**Comment by MarcusSterz** [comment]
> @MarcusSterz are you using italics when checking it out in Glyphs?

As I wrote: I found a rogue spacing in one italic master. Will be fixed. 
This does not explain why Fira Code et al are looking in Firefox, too, though.

**Comment by vinorodrigues** [comment]
this is a known issue with FF - see https://stackoverflow.com/questions/54718201/unicode-box-drawing-does-not-render-correctly-in-browsers

**Comment by vinorodrigues** [comment]
interesting link in that sof link is the "historical doc" mentioned.  it has a unicode test page ... and right at the bottom you get:

```
                                        █
                                                                      ▉
  ╔══╦══╗  ┌──┬──┐  ╭──┬──╮  ╭──┬──╮  ┏━━┳━━┓  ┎┒┏┑   ╷  ╻ ┏┯┓ ┌┰┐    ▊ ╱╲╱╲╳╳╳
  ║┌─╨─┐║  │╔═╧═╗│  │╒═╪═╕│  │╓─╁─╖│  ┃┌─╂─┐┃  ┗╃╄┙  ╶┼╴╺╋╸┠┼┨ ┝╋┥    ▋ ╲╱╲╱╳╳╳
  ║│╲ ╱│║  │║   ║│  ││ │ ││  │║ ┃ ║│  ┃│ ╿ │┃  ┍╅╆┓   ╵  ╹ ┗┷┛ └┸┘    ▌ ╱╲╱╲╳╳╳
  ╠╡ ╳ ╞╣  ├╢   ╟┤  ├┼─┼─┼┤  ├╫─╂─╫┤  ┣┿╾┼╼┿┫  ┕┛┖┚     ┌┄┄┐ ╎ ┏┅┅┓ ┋ ▍ ╲╱╲╱╳╳╳
  ║│╱ ╲│║  │║   ║│  ││ │ ││  │║ ┃ ║│  ┃│ ╽ │┃  ░░▒▒▓▓██ ┊  ┆ ╎ ╏  ┇ ┋ ▎
  ║└─╥─┘║  │╚═╤═╝│  │╘═╪═╛│  │╙─╀─╜│  ┃└─╂─┘┃  ░░▒▒▓▓██ ┊  ┆ ╎ ╏  ┇ ┋ ▏
  ╚══╩══╝  └──┴──┘  ╰──┴──╯  ╰──┴──╯  ┗━━┻━━┛           └╌╌┘ ╎ ┗╍╍┛ ┋  ▁▂▃▄▅▆▇█

```

and this renders as 

![image](https://user-images.githubusercontent.com/366673/169942253-8c5c4453-2741-40ac-b22f-8d3dec82bb96.png)

(on mac, with chrome)

note the not so perfect alignment - and this is NOT italics ... and the other 3 fonts align ok

**Comment by vinorodrigues** [comment]
interested to know is char U+0020 (space) ***and*** char U+00A0 (nbsp) are defined as actual chars and not left to the font engine to aggregate ... because is that is the case it's going to aggregate with the wider 2x & 3x ligatures in play so the average will be wider than 640.

**Comment by MarcusSterz** [comment]
@vinorodrigues THX for this test. Looking just fine in Glyphs and other apps.
Both `space` and `nbspace` are defined as characters and share the same width as the other glyphs.

@bebraw Mind testing the latest ‘develop’ version in VS Code?

**Comment by bebraw** [comment]
Here's a render from the fixed version in VS Code:

<img width="177" alt="Screen Shot 2022-05-24 at 14 02 45" src="https://user-images.githubusercontent.com/166921/170020242-6449ef18-c202-44da-b7b2-edf75bc749d9.png">

The more complex case looks like this:

<img width="641" alt="Screen Shot 2022-05-24 at 14 03 11" src="https://user-images.githubusercontent.com/166921/170020331-1a01053f-5ef0-4753-b378-84262f0cc651.png">

It seems safe to say the next version will fix the problem.

**Comment by vinorodrigues** [comment]
awesome!  I'll close this as concluded then.  ty.
