### ISSUE TITLE
How do we enable slashed zero with "Personal" package?

### ISSUE THREAD

**Issue by sudotliu** [MonoLisaFont/feedback#153]
## Background information

To help debugging, fill the following information before describing the issue:

* Font edition (i.e. trial, personal, plus, pro): personal
* Font version (i.e. 1.805): 1.808
* The type of the font file you are using (i.e. otf, ttf): otf
* Operating system (i.e. MacOS, Windows): MacOS
* Display resolution (i.e. 3072x1920): irrelevant
* Any other information that might be helpful: 
<img width="962" alt="Screen Shot 2022-05-28 at 5 24 31 PM" src="https://user-images.githubusercontent.com/4766414/170846975-e23993e9-8da5-456a-be7b-4e0950c059cc.png">

## Issue

Where do we enable slashed zero from for Personal package?
<img width="396" alt="Screen Shot 2022-05-28 at 5 29 29 PM" src="https://user-images.githubusercontent.com/4766414/170846991-8fe17e34-8492-49e1-abf5-bc5b54328b83.png">

It seems a little misleading to say it's included when one has to do extra work after purchasing to figure out how to even try or enable this feature. Why can't customization for "personal" tier include the slashed zero at least? Either that or remove it as a listed feature for the "personal" tier package.

**Comment by bebraw** [comment]
It's explained at https://www.monolisa.dev/faq#how-to-enable-stylistic-sets-and-the-script-variant .

The alternate zero is behind `zero`.

Depending on your editor, you might have to use https://github.com/twardoch/fonttools-opentype-feature-freezer to freeze it to the font itself.

**Comment by sudotliu** [comment]
Thanks, that works for VS code - it's unfortunate that other editors require extra work though. Basically means features like slashed zero are only partially supported (without extra work) since we can't customize it into the font before download without upgrading.
