### ISSUE TITLE
Question about Script Variant styling

### ISSUE THREAD

**Issue by Christian-Martinez1** [MonoLisaFont/feedback#155]
## Background information

To help debugging, fill the following information before describing the issue:

* Font edition (i.e. trial, personal, plus, pro): Pro
* Font version (i.e. 1.805): 1.808
* The type of the font file you are using (i.e. otf, ttf): ttf
* Operating system (i.e. MacOS, Windows): Windows
* Display resolution (i.e. 3072x1920): 2560x1080
* Any other information that might be helpful: 

## Issue

More of a question (and possible issue), but is the script variant/italic font supposed to be applied to only comments?

As seen in my screenshot below, in a standard HTML boiler plate the elements are being caught by the script variant styling for some reason. Is this intended or should this styling be exclusively for comments?
![Code_4Nq6VUbOZ4](https://user-images.githubusercontent.com/43798323/172942657-4660033d-5ba5-4cf6-8673-f87951b968cf.png)

Here is the settings.json, I believe it should be targeting comments only?
![image](https://user-images.githubusercontent.com/43798323/172942771-4f8f253c-02c3-4007-8572-593f8a5c30ba.png)

Thanks anyone in advance for any input y'all have.

**Comment by bebraw** [comment]
Likely the additional styling is caused by the theme or language you are using.

This is something we cannot fix at the font and you would have to adjust the theme or language definition itself to make it look the way you prefer.

There's a bit more here: https://stackoverflow.com/questions/55054156/how-to-customise-the-textmaterules-for-multiple-themes-in-vs-code . To undo the change, you would have to match the attributes and set fontStyle to regular I think.

**Comment by Christian-Martinez1** [comment]
Thank you for that; what was weird was even after removing all script variant styling the italics was kept on elements. I made no other theme changes aside from adding your snippet to turn on script variant for comments (the one below)
![image](https://user-images.githubusercontent.com/43798323/173021999-0c2699e8-59dc-4a1d-9219-9bef43edcd27.png)
and after removing that it still stayed.

Had to end up overriding entity.other.attribute-name like so to get it to go away:
![image](https://user-images.githubusercontent.com/43798323/173022192-9acd30ec-44bb-45d5-914d-d7bee722609d.png)
Which again is weird since I never styled that scope. But oh well, in case this helps someone else.

**Comment by bebraw** [comment]
Note that technically the script variant **replaces** italic as far as I understand so that might explain a thing or two.

The override you did seems like the way to go for your use case. 👍

**Comment by okonet** [comment]
I think you could generate 2 different fonts using "Customize font" feature on the website where one version would have a `script` feature enabled by default. This way you could setup your editor to use this version in the specific scope (not 100% sure it's possible though).
