### ISSUE TITLE
Good but expensive

### ISSUE THREAD

**Issue by psadi** [MonoLisaFont/feedback#159]
The font is sleek and the well rendered,
But coming from India with a student background the asking price is too high.

Will use FiraCode Nerdfont till the price is reasonable or if a free version is available in future.

**Comment by okonet** [comment]
We have a 50% student discounts and parity pricing so I don’t really understand this sentiment.

**Comment by cmarincia** [comment]
AFAIK the student discounts only apply to the personal license which isn't providing the full font.

**Comment by psadi** [comment]
@cmarincia  i eventually ended up getting the personal license with student discount. Basic font support with ligatures is there. It is expensive for folks at india, but considering that it's a one time purchase we can look past it.
