### ISSUE TITLE
Single-line PHP comment ligatures not right

### ISSUE THREAD

**Issue by dwightwatson** [MonoLisaFont/feedback#16]
This is in Sublime Text. When using the single-line php comment (used by PHPUnit for test annotations) the second asterisk doesn't look quite right.

![image](https://user-images.githubusercontent.com/1100408/77137023-35607380-6ac0-11ea-9148-5fb57fc7693f.png)

The text is literally `/** @test */`

Interestingly it works fine for multi-line PHP comments.

![image](https://user-images.githubusercontent.com/1100408/77137057-6345b800-6ac0-11ea-9692-c1908df3b7d0.png)

**Comment by MarcusSterz** [comment]
Sorry, for replying late. This happens because it renders the first 2 symbols as one ligature and simply adds the second asterisk which lokks slightly different to match normal text size.
THX for the feedback!

**Comment by okonet** [comment]
@MarcusSterz maybe we should move all asterisks closer to the baseline and make them bigger by default? Look how it’s also look wrong on the line with

```markdown
* Example 
```

In markdown it’s used as a bullet point and it makes sense to vertically align it with the text. Also it’s used to emphasize when used inline `*italics*`. 

Another example is multiple: `5 * 8` where it should also be placed in the middle of the line. 

So pretty much every usage but right after a literal should be placed in the middle IMO.

**Comment by MarcusSterz** [comment]
@okonet I will make the regular asterisk as big as the ones in the ligature if that is required.
Also I will make the smaller asterisk a stylistic set, so users have a choice.

**Comment by okonet** [comment]
Yeah I think that should work.

**Comment by bebraw** [comment]
There's an alternate asterisk in 1.6 (use the original download link). More info: https://www.monolisa.dev/releases .

**Comment by dinhquochan** [comment]
@bebraw It's fixed. I confirm.

![image](https://user-images.githubusercontent.com/9979458/102803481-e054e380-43ea-11eb-8085-b57d2b42b54f.png)

**Comment by bebraw** [comment]
Yeah, this has been fixed. We also improved the following case in 1.601:

```javascript
/**
 * demo
 */
```

The *'s align now as you might expect.
