### ISSUE TITLE
Bold style not showing in IDE in Windows 11

### ISSUE THREAD

**Issue by freyjasasi** [MonoLisaFont/feedback#161]
## Background information

To help debugging, fill the following information before describing the issue:

* Font edition (i.e. trial, personal, plus, pro): **personal**
* Font version (i.e. 1.805): **2.000**
* The type of the font file you are using (i.e. otf, ttf): **ttf**
* Operating system (i.e. MacOS, Windows): **Windows**
* Display resolution (i.e. 3072x1920): **1920x1080**

**## Issue**
I am using IDE IntelliJ Idea. Font bold style is not showing inside IDE even though its installed and showing in system settings. see below screenshot for reference. Please help is anything need to do from my side or its ttf issue
<img width="943" alt="image" src="https://user-images.githubusercontent.com/25368842/182034486-37d07ef0-d51e-4a3a-9ae2-f0013756af10.png">

**Comment by bebraw** [comment]
Thanks for the heads up.

The problem was that the font weight range had changed (there are more weights now) so I had to extend the range on my side.

Can you try downloading again to see how it goes now?

**Comment by freyjasasi** [comment]
Ok, I will try and update you. Thanks

**Comment by freyjasasi** [comment]
Now, i can see Bold weight but its not reflecting in IDE, see screenshot below 
<img width="928" alt="image" src="https://user-images.githubusercontent.com/25368842/182078139-52ddf591-9b31-44c9-b2eb-4bc10ab02ff6.png">

**Comment by bebraw** [comment]
Thanks, that's valuable info. Maybe I have to include separate ttf files per weight to the build for this reason.

Out of curiosity, can you try with VS Code?

**Comment by freyjasasi** [comment]
Yes, may be separate ttf for weights will work like last versions. I have vs code installed. Will try and update you

**Comment by freyjasasi** [comment]
See below images for VS Code
**400**
<img width="391" alt="image" src="https://user-images.githubusercontent.com/25368842/182092823-e68297c4-10ba-4171-b6e0-c7822c992940.png">
**500**
<img width="354" alt="image" src="https://user-images.githubusercontent.com/25368842/182092869-4c87e458-4b9a-4435-8576-608e117e4bad.png">
**600**
<img width="426" alt="image" src="https://user-images.githubusercontent.com/25368842/182092901-8468c581-6c2e-4ccf-8f04-480cfd1647c6.png">
**700**
<img width="318" alt="image" src="https://user-images.githubusercontent.com/25368842/182092931-4e4e9f43-f0ec-4fc3-b6de-f180b43a88c9.png">

**Comment by freyjasasi** [comment]
update here once separate ttf for weights are added, i will check it

**Comment by bebraw** [comment]
VS Code looks correct to me.

I'll ping you once the separate ttfs are included so you can test.

**Comment by freyjasasi** [comment]
Ok, thanks

**Comment by bebraw** [comment]
@freyjasasi I made the preview version include separate files for ttf.

Note that the version metadata is off (not pointing to 2.0) but apart from that it should be correct. I can get this fixed in two weeks earliest due to a Summer break.

**Comment by freyjasasi** [comment]
I confirm metadata not updated 
<img width="480" alt="image" src="https://user-images.githubusercontent.com/25368842/182109209-09026169-0dbe-4dc3-9429-b73f09127056.png">

but now its working in IDE
<img width="517" alt="image" src="https://user-images.githubusercontent.com/25368842/182109129-2c87857b-1bc6-4e87-84d2-4c77477fec7a.png">

but the fixes made for #131 and #141 are missing in separate ttfs but in variable its there

**Comment by bebraw** [comment]
The font author isn't available for two weeks so I cannot update the separate version until he is back since only he can build the font.

I think we're stuck with the current version until then.

**Comment by freyjasasi** [comment]
Ok, thanks for the update. No problem 😊

**Comment by freyjasasi** [comment]
Hi, found some workaround, installing both individual ttfs and variable ttfs giving the options to choose old weight also and #131 and #141 fixes 
<img width="507" alt="image" src="https://user-images.githubusercontent.com/25368842/182153875-d2bf1978-4d6b-412e-89db-0288c27456e2.png">

<img width="280" alt="image" src="https://user-images.githubusercontent.com/25368842/182153969-b62b3ab9-1df3-4eab-922c-7c4fdf806297.png">

**Comment by freyjasasi** [comment]
Cool, thanks

**Comment by bebraw** [comment]
I pushed updated versions for the separate ttfs so it's safe to close this now.
