### ISSUE TITLE
Italic dashes aren't monospace

### ISSUE THREAD

**Issue by KingQuarter** [MonoLisaFont/feedback#162]
## Background information

* Font edition: trial
* Font version: 1.808
* The type of the font file you are using: otf and ttf (both were tested by deleting one then installing the other)
* Operating system: Windows 11
* Display resolution: 1366x768
* IDE: VS Code

## Issue
Italic dashes aren't monospace; they're longer than they should be.
### Non-italic:
![image](https://user-images.githubusercontent.com/92368853/184263015-0dd17544-f820-4f8f-8459-fffa77556fcc.png)
### Italic:
![image](https://user-images.githubusercontent.com/92368853/184262593-04d61635-fbfb-464d-a3ce-98b4caec956a.png)
Each line contains 10 characters.
## Notes
I am applying the italics by inserting this into my settings.json file.
![image](https://user-images.githubusercontent.com/92368853/184263621-cf8a81fe-46a0-4a8e-9128-2659b8c34081.png)
I have not experienced this issue with any other font I have downloaded.

**Comment by bebraw** [comment]
Can you try the prerelease version (2.0)? Use the variable one as it works with VS Code.

I believe the issue has been fixed there.

**Comment by KingQuarter** [comment]
Is it possible to download the prelease version if I chose the trial version?

**Comment by bebraw** [comment]
@KingQuarter The prerelease isn't available as a trial.

**Comment by KingQuarter** [comment]
Closing for now until I try out v2.0.

**Comment by bebraw** [comment]
FYI, I updated trial to use 2.0 prerelease so it should have the fix now.

**Comment by KingQuarter** [comment]
It works! Thanks so much.

**Comment by KingQuarter** [comment]
When I download the prerelease, it's still v1.808.

**Comment by bebraw** [comment]
@KingQuarter I assume you used the Paddle link to download. I forgot the trial there so I pushed the version there as well. We use a separate end point for the rest. For some reason trial is delivered differently than the rest.

**Comment by KingQuarter** [comment]
Is this the Paddle link you're referring to?
![image](https://user-images.githubusercontent.com/92368853/185771935-ecee805a-2464-453c-8c82-4dc68e34d529.png)

Just now, I entered my email, verified that I was a human, and downloaded the trial, but it's still v1.808.

**Comment by bebraw** [comment]
Ok, the issue will be fixed in the next stable release.

There's likely something I missed in the pipeline. Probably the trial download is pointing to the stable version still and I don't want to rewrite that portion as prerelease can have other faults etc.

**Comment by KingQuarter** [comment]
Is there a way I can be notified on new stable releases?

**Comment by bebraw** [comment]
@KingQuarter We announce them at Twitter (@Monolisafont) and RSS (available through the site).

**Comment by KingQuarter** [comment]
I don't think [@MonoLisaFont](https://twitter.com/monolisafont) announced v2, but I have now subscribed to the MonoLisa Releases RSS feed. Thanks.

**Comment by bebraw** [comment]
@KingQuarter Yup, it's in prerelease mode as we're testing things. Correct.
