### ISSUE TITLE
please add u2714 u2715 u2716 u2717 u2718 glyphs

### ISSUE THREAD

**Issue by zhimoe** [MonoLisaFont/feedback#163]
the checkmark  and crossing  sign  are very common glyph in terminal, wish can have them in personal plan version

![FFAEE177-A690-49CC-A7FB-E0AFE0D86221](https://user-images.githubusercontent.com/24514012/185026759-8baf002e-f9f9-469a-bb9a-73c7112754dd.png)

**Comment by bebraw** [comment]
Can you give examples of usages in the wild? The issue would benefit from more context so we understand which tools use the feature.

**Comment by MarcusSterz** [comment]
@bebraw Won’t that collide with our emoji-free policy?

**Comment by okonet** [comment]
These aren’t emoji. I’m still not sure we need all of them so I’d wait for a reply.

**Comment by bebraw** [comment]
https://www.nerdfonts.com/ tends to cover terminal specific glyphs well (1000+ glyphs) and patching/usage has been covered at https://www.monolisa.dev/faq#how-to-enable-nerd-fonts-with-monolisa .

**Comment by bebraw** [comment]
We decided it's a good idea to add these.

Good reference: https://symbl.cc/en/unicode/blocks/dingbats/ .

**Comment by bebraw** [comment]
Implemented and published in 2.006.
