### ISSUE TITLE
[praise] easily the best monospaced font

### ISSUE THREAD

**Issue by philiparvidsson** [MonoLisaFont/feedback#164]
Hey everyone. I bought MonoLisa a while back. I've been into both software programming and typographic (writing academic papers) for a couple of decades. I have been through so many fonts, always looking for a better one. Rarely do the fonts stick for more than a few weeks or sometimes days - always finding my pet peeves that make the font unusable.

That changed with MonoLisa for me. I never need to think about what monospace font to use ever again (ok, stylizing texts for some particular design context excluded).

There is not one single character that looks off. The only two things I've noticed (and to provide more than just praise here) is that

1. The font sometimes renders a bit too thinly in my browser (Firefox). Unsure what is causing it.
2. There are cases when my editor (Emacs) doesn't render MonoLisa as monospaced. It's only happened in a couple of files, so it might be a fallback font to cover up for some missing character, but I've only had this happen in my setup with MonoLisa (although the phenomenon itself is not unheard of).

THANK YOU for an absolutely amazing font. :-)

**Comment by bebraw** [comment]
For 2., make sure to try out 2.0 prerelease as it has a related fix for a special case. You can access it through the orders page at the website.

**Comment by philiparvidsson** [comment]
Interestingly, I am using the 2.0 prerelease. Here's a screenshot:

![image](https://user-images.githubusercontent.com/1163299/186978096-d9e9a31c-29b7-4bf2-80cd-e803e941ea50.png)

As you might be able to tell, everything is misaligned. This only happens here, though.

**Comment by bebraw** [comment]
@philiparvidsson Are you using the variable version or the separate font files?

Can you paste the ASCII here so it's easier to test?

Can you see the issue in other editors as well or is it specific to emacs?

**Comment by philiparvidsson** [comment]
I am using the /ttf/ fonts from MonoLisa-Plus-2.000.zip.

Pasted ASCII:

```
=================     ===============     ===============   ========  ========
 \\ . . . . . . .\\   //. . . . . . .\\   //. . . . . . .\\  \\. . .\\// . . //
 ||. . ._____. . .|| ||. . ._____. . .|| ||. . ._____. . .|| || . . .\/ . . .||
 || . .||   ||. . || || . .||   ||. . || || . .||   ||. . || ||. . . . . . . ||
 ||. . ||   || . .|| ||. . ||   || . .|| ||. . ||   || . .|| || . | . . . . .||
 || . .||   ||. _-|| ||-_ .||   ||. . || || . .||   ||. _-|| ||-_.|\ . . . . ||
 ||. . ||   ||-'  || ||  `-||   || . .|| ||. . ||   ||-'  || ||  `|\_ . .|. .||
 || . _||   ||    || ||    ||   ||_ . || || . _||   ||    || ||   |\ `-_/| . ||
 ||_-' ||  .|/    || ||    \|.  || `-_|| ||_-' ||  .|/    || ||   | \  / |-_.||
 ||    ||_-'      || ||      `-_||    || ||    ||_-'      || ||   | \  / |  `||
 ||    `'         || ||         `'    || ||    `'         || ||   | \  / |   ||
 ||            .===' `===.         .==='.`===.         .===' /==. |  \/  |   ||
 ||         .=='   \_|-_ `===. .==='   _|_   `===. .===' _-|/   `==  \/  |   ||
 ||      .=='    _-'    `-_  `='    _-'   `-_    `='  _-'   `-_  /|  \/  |   ||
 ||   .=='    _-'          '-__\._-'         '-_./__-'         `' |. /|  |   ||
 ||.=='    _-'                                                     `' |  /==.||
 =='    _-'                         E M A C S                          \/   `==
 \   _-'                                                                `-_   /
  `''                                                                      ``' 

                	
```

I'm only using it in Emacs so I haven't seen it anywhere else.

**Comment by dinhquochan** [comment]
FYI: Below is v2.00-pre, emacs on macOS

<img width="828" alt="image" src="https://user-images.githubusercontent.com/9979458/187038931-5013b4ff-9653-48e7-9ea0-9822dbeff506.png">

**Comment by bebraw** [comment]
@dinhquochan Are you using the variable version? Can you try with it?

**Comment by dinhquochan** [comment]
@bebraw yes, I try variable version!

**Comment by bebraw** [comment]
I think I'm missing something. I tried with both variable and separate build on MacOS with iTerm 2 and both rendered perfectly:

<img width="590" alt="Screen Shot 2022-08-30 at 10 59 04" src="https://user-images.githubusercontent.com/166921/187382768-d9d724c9-c558-4616-b9f7-fef6203ba5f1.png">

**Comment by bebraw** [comment]
@philiparvidsson Which operating system are you using? I wonder if we could reduce this to OS/Emacs combination as it seems to render as expected on MacOS/Emacs at least.

**Comment by bebraw** [comment]
@philiparvidsson Also make sure to download the prerelease again as there was a subtle fix to the version with separate ttfs a while ago. One option is that you are using the one that doesn't have all the fixes in it.

**Comment by philiparvidsson** [comment]
I downloaded the .zip again and it now looks as it should:

![image](https://user-images.githubusercontent.com/1163299/187859555-a1444085-e294-4027-8100-7e4ee988334b.png)

It's still called 2.000 pre-release (please be mindful of versioning!). Thank you so much.

**Comment by bebraw** [comment]
@philiparvidsson Ok, I guess that was it.

Good point on versioning. Next prerelease could be 2.001 or so as that would avoid the confusion.

**Comment by okonet** [comment]
I think we won't be doing proper semantic versioning until the final release since it will complicate things quite a lot on our end. Right @bebraw?

**Comment by bebraw** [comment]
@okonet There's value in bumping version when a new prerelease is published as otherwise reports will be confusing. Doing that would have saved effort here. When a release is stable, it becomes the version the last prerelease was.

**Comment by bebraw** [comment]
@okonet Only gotcha is that @MarcusSterz needs to bump the version slightly if he changes something in the prerelease before building.

**Comment by dinhquochan** [comment]
Off-topic: @bebraw Before, if new version is release, it has a newsletter to email. Recently, its doesn't. I must go to homepage and access to changelog to known that. How I know when a new version release?

**Comment by bebraw** [comment]
@dinhquochan We'll send email for stable releases. We haven't done a mail on the prerelease yet as it's still a new thing. Basically we want to change the process a little bit so that people can try out new releases before they go stable to catch issues earlier. 2.0 is a big change so it made sense to start there.

**Comment by bebraw** [comment]
I guess we can close this now.

@philiparvidsson Feel free to open an issue about "The font sometimes renders a bit too thinly in my browser (Firefox). Unsure what is causing it." with some screenshots and thanks for the praise.
