### ISSUE TITLE
Feature Request for more glyphs for github and branching

### ISSUE THREAD

**Issue by JustBarnt** [MonoLisaFont/feedback#165]
We welcome any feedback regarding technical issues (broken letters, ligatures not working, bad spacing etc). We will have a look and try to implement the changes in future versions.

---

## Background information

To help debugging, fill the following information before describing the issue:

* Font edition (i.e. trial, personal, plus, pro): Plus
* Font version (i.e. 1.805): 2.00
* The type of the font file you are using (i.e. otf, ttf): otf
* Operating system (i.e. MacOS, Windows): windows
* Display resolution (i.e. 3072x1920): 1920x1080
* Any other information that might be helpful: 

## Feature Request
More glyphs relating to GitHub, SVN, and branches. I love this font, it is easily the best font I have ever used for programming, its just that there aren't as many glyphs available for how custom I have my powershell script. It would be awesome if it was possible to include some glyphs like the github logo, a glyph for branches, etc.

**Comment by bebraw** [comment]
Does [Nerd Fonts](https://www.nerdfonts.com/) contain these?

**Comment by JustBarnt** [comment]
@bebraw I believe so yes. I used to use Cascadia Cove NF (Nerd Fonts version of MS Cascadia Code)  which had probably hundreds of those glyphs.

**Comment by bebraw** [comment]
Ok, let's close in favor of #57 then.

I have a Nerd Fonts build in the latest 2.0 prerelease (only pro version).

I recommend using their Docker based solution for patching. It's covered here: https://github.com/MonoLisaFont/feedback/issues/57#issuecomment-949724000 .

**Comment by JustBarnt** [comment]
Gotcha, so I can use docker to patch- or I have a professional use license I can just download it in per-release (2.0) build? I would be against purchasing an upgraded license, I bought plus. But I know designing fonts is very hard, and I am all for pay fair amounts for work.

**Comment by bebraw** [comment]
@JustBarnt You can apply the tool easily against any version. No problem with that. 👍

**Comment by JustBarnt** [comment]
@bebraw Okay, thank you!
