### ISSUE TITLE
Request: greater/less-than-or-equal "unslanted" variant

### ISSUE THREAD

**Issue by arempe93** [MonoLisaFont/feedback#167]
It would be nice to have a "unslanted" variant of the greater/less-than-or-equal programming ligatures similar to Fira Code's stylistic set 02.

<img width="612" alt="fira_code_ss02" src="https://user-images.githubusercontent.com/4637120/194787229-691c669c-6be9-449f-98a0-3d8f25203864.png">

**Comment by bebraw** [comment]
This has been done in 2.004.
