### ISSUE TITLE
feature: escape and hexadecimal ligatures

### ISSUE THREAD

**Issue by pdobrovolny** [MonoLisaFont/feedback#169]
Please be so kind and add ligatures according to the attachment, following the FiraCode font pattern. Thank You.

<img width="235" alt="Snímek obrazovky 2022-10-26 v 21 20 28" src="https://user-images.githubusercontent.com/39558363/198120489-2dfa4b9d-4c46-4d70-89ea-060188e34ee1.png">
<img width="319" alt="Snímek obrazovky 2022-10-26 v 21 25 21" src="https://user-images.githubusercontent.com/39558363/198120494-3a6c1b62-85c2-4083-82d4-c69b40400db5.png">

**Comment by bebraw** [comment]
@MarcusSterz The combinations for escaped characters are `\n` and `\\`. For hexadecimal, the first pattern is `0x<0-9A-F>` and for latter `<0-9>x<0-9>`. It's a normal "x" in both cases.

As I don't know how specific you can be with ligatures and what kind of patterns they support, I would check the Glyphs definition from https://github.com/tonsky/FiraCode .

**Comment by MarcusSterz** [comment]
@bebraw It seems Fira Code is not using a ligature for `\\` but a replacement of the first backslash, so that’s easy.

Regarding x I haven’t found the OpenType feature yet. Is it default in Fira?

**Comment by bebraw** [comment]
> Regarding x I haven’t found the OpenType feature yet. Is it default in Fira?

They claim it's behind `liga` by default, yes.

**Comment by MarcusSterz** [comment]
> > Regarding x I haven’t found the OpenType feature yet. Is it default in Fira?
> 
> They claim it's behind `liga` by default, yes.

It appears to be a `calt` feature in Fira and I can put it behind there as well.

**Comment by bebraw** [comment]
@MarcusSterz Ah, ok. That makes sense.

**Comment by pdobrovolny** [comment]
> @MarcusSterz The combinations for escaped characters are `\n` and `\\`. For hexadecimal, the first pattern is `0x<0-9A-F>` and for latter `<0-9>x<0-9>`. It's a normal "x" in both cases.
> 
> As I don't know how specific you can be with ligatures and what kind of patterns they support, I would check the Glyphs definition from https://github.com/tonsky/FiraCode .

Hey guys, I'm sending a screenshot with escape examples.  In the case of regular expressions, the backslash can probably be before any non-alphanumeric character. Hopefully the information will help you.
<img width="677" alt="Snímek obrazovky 2023-01-09 v 21 13 14" src="https://user-images.githubusercontent.com/39558363/211399451-15411a28-93b7-49f3-a303-79355c54193b.png">
<img width="444" alt="Snímek obrazovky 2023-01-09 v 21 24 32" src="https://user-images.githubusercontent.com/39558363/211401322-4ab8c042-745e-40b3-a4fb-f6345053838f.png">

**Comment by MarcusSterz** [comment]
The thinner backslash `\` will be available as stylistic set (ss10) and appear if followed by a second backslash.
ss10 will also provide a thinner backslash when used in `\n`.

**Comment by MarcusSterz** [comment]
The multiply `×` in requested situations will be available as ss11 in the next version.

**Comment by okonet** [comment]
@MarcusSterz I think we want both ligatures be available on `calt`.

**Comment by MarcusSterz** [comment]
@okonet They are not ligatures but replacements via styslistic sets. Putting them into `calt` would cause trouble elsewhere.

**Comment by bebraw** [comment]
This has been done in 2.004.
