### ISSUE TITLE
Support Vietnamese characters 

### ISSUE THREAD

**Issue by dinhquochan** [MonoLisaFont/feedback#17]
Dear,
I hope the font has support Vietnamese characters soon.

### Vietnamese Characters:

* a á à ả ã ạ ă ắ ằ ẵ ẳ ặ â ấ ầ ẫ ẩ ậ
* A Á À Ả Ã Ạ Ă Ắ Ằ Ẵ Ẳ Ặ Â Ấ Ầ Ẫ Ẩ Ậ
* i í ì ỉ ĩ ị
* I Í Ì Ỉ Ĩ
* u ú ù ũ ủ ụ ư ứ ừ ữ ử ự
* U Ú Ù Ũ Ủ Ụ Ư Ứ Ừ Ữ Ử Ự
* o ó ò õ ỏ ọ ô ố ồ ỗ ổ ộ ơ ớ ờ ỡ ở ợ
* O Ó Ò Õ Ỏ Ọ Ô Ố Ồ Ỗ Ổ Ộ Ơ Ớ Ờ Ỡ Ở Ợ
* y ý ỳ ỷ ỹ ỵ
* Y Ý Ỳ Ỷ Ỹ Ỵ

Src: https://vietnamesetypography.com/ (maybe helpful)

**Comment by bebraw** [comment]
Let's keep this one open for future reference.

**Comment by dinhquochan** [comment]
Thanks @bebraw

**Comment by bebraw** [comment]
Support for Vietnamese has been added in 1.500 available now.

**Comment by dinhquochan** [comment]
Wow, thanks @bebraw
