### ISSUE TITLE
2.0 - ss07 doesn't apply to braceleft_bar and bar_braceright

### ISSUE THREAD

**Issue by bebraw** [MonoLisaFont/feedback#170]
## Background information

To help debugging, fill the following information before describing the issue:

* Font edition (i.e. trial, personal, plus, pro): Pro
* Font version (i.e. 1.805): 2.002
* The type of the font file you are using (i.e. otf, ttf): TTF
* Operating system (i.e. MacOS, Windows): MacOS
* Display resolution (i.e. 3072x1920): 3072x1920
* Any other information that might be helpful: None

## Issue

Looking at the specimen, it seems `ss07` (alternative `{` and `}`) doesn't apply to combinations like `{|` and `|}` leading to inconstencies in rendering when both `calt` and `ss07` are enabled.

**Comment by MarcusSterz** [comment]
It does not because there is no reason to do so. The endings of the braces are prolongued to match the bar. I would not change anything here.

**Comment by bebraw** [comment]
Ok, closing as wontfix.
