### ISSUE TITLE
Download and Custom options

### ISSUE THREAD

**Issue by vendy0308** [MonoLisaFont/feedback#174]
## Background information

To help debugging, fill the following information before describing the issue:

* Font edition (i.e. trial, personal, plus, pro): Complete
* Font version (i.e. 1.805): 2.003
* The type of the font file you are using (i.e. otf, ttf): ttf
* Operating system (i.e. MacOS, Windows): MacOS
* Display resolution (i.e. 3072x1920): 2K
* Any other information that might be helpful: 

## Issue

1. I downloaded the font and unzipped only a README.MD file
2. Why these SS08 & SS09 options can not be selected

 
<img width="1082" alt="CleanShot 2022-12-05 at 09 36 09@2x" src="https://user-images.githubusercontent.com/75200716/205530427-d2c81145-0462-4fbc-86b1-40554d940f6b.png">
<img width="376" alt="CleanShot 2022-12-05 at 09 38 03@2x" src="https://user-images.githubusercontent.com/75200716/205530719-ed6ac97d-43e5-43a5-82a1-f312e7708b33.png">

**Comment by bebraw** [comment]
It's a temporary limitation as our tooling doesn't allow replacing ligatures yet. We hope to resolve this in the near future.

You can still access the features in editors like VS Code and potentially other editor allow you to toggle OpenType features.

**Comment by vendy0308** [comment]
Thank you for your answer!
But about the first question
the static option has fonts but the variable option is no fonts only READNE.md file
Is this a bug?

**Comment by bebraw** [comment]
> the static option has fonts but the variable option is no fonts only READNE.md file
> Is this a bug?

This should be fixed now, thanks for the heads up.

We'll try to resolve the rest at a later time as it's bigger problem to figure out ligature replacements.

**Comment by vendy0308** [comment]
Variable option is work.
Thanks!

**Comment by jayeshbhoot** [comment]
For those using kitty terminal (https://sw.kovidgoyal.net/kitty/), the stylistic sets can be enabled as follows:

```
# in kitty.conf
# ref: https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.font_features
font_features MonoLisa-Medium +zero +ss04 +ss07 +ss08 +ss09
font_features MonoLisa-MediumItalic +zero +ss04 +ss07 +ss08 +ss09
```

**Comment by bebraw** [comment]
Let's use #179 for tracking ss08 and ss09 UI. Note that the features are included to the font but you cannot **freeze** them through the UI yet.

@jayeshbhoot Thanks for the good info. I added that to the FAQ.
