### ISSUE TITLE
Comments in VSCode do not look like script variants

### ISSUE THREAD

**Issue by decisivedevops** [MonoLisaFont/feedback#175]
## Background information

To help to debug, fill in the following information before describing the issue:

* Font edition (i.e. trial, personal, plus, pro): Complete
* Font version (i.e. 1.805): 2.003
* The type of the font file you are using (i.e. otf, ttf): ttf
* Operating system (i.e. MacOS, Windows): MacOS Ventura
* Display resolution (i.e. 3072x1920): 3440 * 1440
* Any other information that might be helpful: Using font mainly on VSCode (Version: 1.73.1)

## Issue

Comments in VSCode do not look like script variants.

On previous versions, comments were script versions.

I have the below config in VSCode.

```
    "editor.fontFamily": "MonoLisa",
    "editor.fontLigatures": "'ss02' on",
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": [
                    "comment",
                ],
                "settings": {
                    "fontStyle": "italic"
                }
            }
        ]
    },

```

I am using https://fontdrop.info/ for validation, and the Italics version shows the scripted variant correctly.

I tried all of your suggestions.

With the first link download,
1. Either my complete code is getting scripted.

![image](https://user-images.githubusercontent.com/95153836/206641495-6289f57f-3017-4291-8f1a-24c1b22db9b3.png)

2. Or the change is temporary. Once I restart the VSCode, the complete code gets scripted.

**Before restart**

![image](https://user-images.githubusercontent.com/95153836/206642066-38b183c1-d002-409d-a04e-f968e737c1f8.png)

**After restart**

![image](https://user-images.githubusercontent.com/95153836/206642184-f1b0c891-ce82-4b12-ad7e-df9cc4f14340.png)

**Installed fonts:**

![image](https://user-images.githubusercontent.com/95153836/206641682-98e2e14a-d77c-41af-ba66-0cca0d0ab61d.png)

**Comment by bebraw** [comment]
> Either my complete code is getting scripted.

I'm on VS Code 1.74.0 and I'm using the first download on MacOS Ventura and I simply cannot reproduce the issue. Everything looks as expected even after restarting. Here's my configuration:

```json
{
  "editor.fontFamily": "MonoLisa",
  "editor.fontVariations": true,
  "editor.fontWeight": 400,
  "editor.lineHeight": 16,
  "editor.fontLigatures": "'ss02' on",
  "editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": "comment",
        "settings": {
          "fontStyle": "italic"
        }
      }
    ]
  },
}
```

Most likely you can drop some lines from that without losing anything of value.

To debug locally, you could try `Help -> Toggle Developer Tools` and then locate the view with the settings to see what it's applying exactly. You could also try to start dropping bits like `editor.tokenColorCustomizations` to simplify configuration to see if it still applies script on everything.

It could be some cache issue or something weird. I would try upgrading VS Code at least.

**Comment by decisivedevops** [comment]
> > Either my complete code is getting scripted.
> 
> I'm on VS Code 1.74.0 and I'm using the first download on MacOS Ventura and I simply cannot reproduce the issue. Everything looks as expected even after restarting. Here's my configuration:
> 
> ```json
> {
>   "editor.fontFamily": "MonoLisa",
>   "editor.fontVariations": true,
>   "editor.fontWeight": 400,
>   "editor.lineHeight": 16,
>   "editor.fontLigatures": "'ss02' on",
>   "editor.tokenColorCustomizations": {
>     "textMateRules": [
>       {
>         "scope": "comment",
>         "settings": {
>           "fontStyle": "italic"
>         }
>       }
>     ]
>   },
> }
> ```
> 
> Most likely you can drop some lines from that without losing anything of value.
> 
> To debug locally, you could try `Help -> Toggle Developer Tools` and then locate the view with the settings to see what it's applying exactly. You could also try to start dropping bits like `editor.tokenColorCustomizations` to simplify configuration to see if it still applies script on everything.
> 
> It could be some cache issue or something weird. I would try upgrading VS Code at least.

any other IDE/ text editor this can be checked?
I have PyCharm.

**Comment by decisivedevops** [comment]
> 1. If you download the font with the script enabled, it will apply script _to all italics_. This also means, `ss02` won't be of any use since it will be already toggled on by default and removed from the font.
> 2. VSCode is probably the only editor that supports OpenType features, so you should use a normal download (without selecting any OpenType features) and enable the `ss02` only for comments. Not 100% sure how to do so though.
> 3. PyCharm nor any other IntelliJ IDE has support for OpenType feautures. To use script variant there you should download a customized version of the font with `ss02` enabled. I'd suggest naming it differently so you can install multiple fonts on your computer and choose them in different editors.
> 4. If the VSCode config doesn't work for you, you can still try using two fonts one with `ss02` enabled and one without. Choose the one with `ss02` for the scope.

Tried all the suggestions.

**Comment by bebraw** [comment]
To proceed with debugging, we would need a clear reproduction on MacOS since I cannot reproduce the issue on my system.

The weird point is that VS Code settings should render using regular, not italic, so it's hard to understand why it would apply script to it.

**Comment by bebraw** [comment]
To have a clean slate, I would remove any MonoLisa font you have installed at your Fonts directory and reinstall the default one (first download).

**Comment by decisivedevops** [comment]
Finally managed to fix this using extension - https://github.com/iocave/customize-ui

This is what I added to make comments using the ss02 variant font.

![image](https://user-images.githubusercontent.com/95153836/206770741-158f5315-b931-40f5-a357-9e9e61c37935.png)
