### ISSUE TITLE
Can't install monolisa on mac

### ISSUE THREAD

**Issue by edgentry** [MonoLisaFont/feedback#177]
I just switched to a Mac and downloaded the lastest version TTF version of monolisa but the mac does not recognize these as fonts and won't install them.

**Comment by bebraw** [comment]
Can you provide more information? Which version of MacOS are you using? How did you install? Which variant (basic, plus, complete) are you trying to install?

We would need full information to help.

**Comment by bebraw** [comment]
I set up a form for capturing the information. Can you please [open a new issue](https://github.com/MonoLisaFont/feedback/issues/new/choose) using the template? I'll close this one in favor of that.

On MacOS, make sure to inspect the font with Font Book before installing as it also lets you install it.
