### ISSUE TITLE
Download font with all style sets

### ISSUE THREAD

**Issue by bundgaard** [MonoLisaFont/feedback#178]
### What feature are you proposing?

Hello,

It would be nice if I could use one font for with all style sets.
As it is now I have to download with specifics activated which makes it more cumbersome.

**Comment by bebraw** [comment]
The first download link at the UI on top of the customize tool is exactly this but maybe it's not completely clear at the UI that it's for this purpose.

**Comment by bundgaard** [comment]
Thank you for your answer, will download the font from that and suggest that we could change the description to make it more clear.
Closing.
