### ISSUE TITLE
[Bug]:  ss08 and ss09 is not available

### ISSUE THREAD

**Issue by bundgaard** [MonoLisaFont/feedback#179]
### Edition

Complete (Pro)

### What version are you using?

latest

### What type of weights are you using?

Variable (customized)

### Operating system

Windows 10

### Display resolution

1920x1200

### What happened?

When downloading the fonts I can not select Ss08 and ss09.

**Comment by bebraw** [comment]
We are working on this one. The features are disabled because the tooling cannot replace ligatures yet.

Note that they are included to the font so you can still access them in editors like VS Code.

**Comment by marlonjames71** [comment]
This is the same for me. I'm on a Mac, MonoLisa V2 (latest), ss08 & ss09 are not available when building custom font. I too have selected variable, TTF, and I have the Complete license.

**Comment by bebraw** [comment]
The options should be available now.

**Comment by marlonjames71** [comment]
It indeed works now. Thank you!
