### ISSUE TITLE
Lambda  λ is missing

### ISSUE THREAD

**Issue by kfollesdal** [MonoLisaFont/feedback#18]
The symbol λ (Lambda) is missing. Had been nice if it was implemented. 

https://en.wikipedia.org/wiki/Lambda

**Comment by MarcusSterz** [comment]
Of course many symbols could be implemented. A version including greek is around the corner!

**Comment by okonet** [comment]
@kfollesdal we do have a greek alphabet support. Are you missing: a glyph or a specific ligature? If the later, what kind of combination it is suppose to be applied to?

**Comment by kfollesdal** [comment]
@okonet thank you for following up :-) Greek letters and then lambda is added after I write my issue. I close the issue since I now have what i need.
