### ISSUE TITLE
[Bug]: Freeze doesn't work anymore with Emacs

### ISSUE THREAD

**Issue by neurolit** [MonoLisaFont/feedback#186]
### Edition

Basic (Personal)

### What version are you using?

2.003

### What type of weights are you using?

Default (non-customized)

### Operating system

Linux

### Program

Emacs

### What happened?

Hi!

I tried to use MonoLisa 2.003 with some frozen variants (ss07  for parenthesis, and ss08). Whereas it works with VS Code without a specific configuration:

![2023-01-09_19-59](https://user-images.githubusercontent.com/1727830/211475884-76cf066a-3ab4-4997-9c7e-fcc35aedd388.png)

it doesn't work with Emacs (look at the parenthesis):

![2023-01-09_20-02](https://user-images.githubusercontent.com/1727830/211475954-630e6b78-ad11-4f63-86cf-a24e3cbc50ba.png)
Frozen variants were working in Emacs before 2nd version of MonoLisa. According to https://github.com/MonoLisaFont/feedback/issues/182#issuecomment-1364132974, the way freeze works was changed, and this new way doesn't work anymore with Emacs. It worked a few months ago, for ss03 for example.

Is there a way on your side to fix this behavior? The only way I found on my way was to manually exchange the glyphs with FontForge after each download of a new MonoLisa version, but it's tedious.

**Comment by neurolit** [comment]
Maybe related to #184 too

**Comment by okonet** [comment]
Yea looks like these are the same issue. I’ll dig into it soon.

**Comment by neurolit** [comment]
It works perfectly now, thank you!

**Comment by okonet** [comment]
Glad to hear that!
