### ISSUE TITLE
[Bug]: default Complete download doesn't seem to include the ss02 OpenType feature

### ISSUE THREAD

**Issue by thebengeu** [MonoLisaFont/feedback#187]
### Edition

Complete (Pro)

### What version are you using?

2.003

### What type of weights are you using?

Default (non-customized)

### Operating system

Ubuntu 22.10

### Program

WezTerm

### What happened?

The default Complete download doesn't seem to include the ss02 OpenType feature.

I was able to tweak other OpenType features in WezTerm except ss02. I tried various other options such as static, enabling the script variant by default, and none seemed to include the script variant.

So I checked using FontDrop, and the ss02 feature doesn't seem to be included at all:

![Screenshot from 2023-01-10 18-29-20](https://user-images.githubusercontent.com/1154867/211530177-265db118-2f57-43a8-aa78-cc77ab0aa959.png)

**Comment by bebraw** [comment]
Can you check against the Italic version as Regular doesn't include ss02 by design?

**Comment by thebengeu** [comment]
The Italic version indeed includes ss02, thanks!

Per email communication, @bebraw will add note to the FAQ.

**Comment by bebraw** [comment]
Here's the FAQ entry: https://www.monolisa.dev/faq#where-can-i-find-the-script-glyphs-ss02.
