### ISSUE TITLE
Taller Capital Characters Option

### ISSUE THREAD

**Issue by marlonjames71** [MonoLisaFont/feedback#188]
### Request
Would love to have an option when configuring the font to opt in for slightly taller capital characters.

### Reason
I'm a software developer who's been using MonoLisa for a while now. I code in Swift mostly and we use camelCase all over the place. I know MonoLisa is all about lessening the fatigue for developers. I also know that MonoLisa has this nice flow within the font that has characters flowing into the next and so on. Recently, I tried the JetBrains font again because I wanted to see if I was noticing something about MonoLisa. What I was noticing with MonoLisa is that sometimes it's a bit hard to tell where each word begins within a name. 

**Some examples that I had to do a double take to make sure I was using the correct one:**

```swift
let displayedLocationUpdatePublisher: PassthroughSubject<WBLocation, Never>()
let displayedLocationWeatherUpdatePublisher: PassthroughSubject<WBWeather, Never>()

appendingPathComponent
appendingPathExtension

getDisplayedLocation()
getDeviceLocation()
```

Sometimes those longer properties can be hard to pick out. Naming is tough and I always try to name my properties the best that I can, and I also try to not make things look so similar. But sometimes this is hard to avoid before the name starts to not accurately reflect what it is.

So, because I know JetBrains is more condensed and I also remembered on your website where you show that JetBrains is slightly taller, I wanted to see if it made any sort of difference. And it actually did. A lot of the longer named properties that may start out the same became a little easier to read and differentiate from each other hence my request.

### Summary
It would be fantastic if there was a configuration that offered slightly taller capital characters for folks like me who could benefit from that. When you have names that are naturally similar to others, being able to quickly spot each word within the camel cased name to identify where the difference is, is really important get to what you need accurately and quickly.

Thanks for hearing me out. I hope this can be something that gets serious consideration and that doesn't detract from MonoLisa, but rather offers an optional enhancement for those who'd benefit as I think it would lessen fatigue even more. I'm a huge fan of MonoLisa and I tell everyone about it. I think this could possibly give more folks a reason to jump on board if they haven't already. Cheers!

**Comment by MarcusSterz** [comment]
Thanks for your kind words! 
Longer text is easier to read when you have a significant difference between lower case ascenders and capitals in combination with a high x-height. Imho the ascenders of Jetbrains are not high enough to make that difference. 
While we see what you mean the possible benefit of having slightly taller capitals would probably be outweighed by the negative effects regarding reading speed and legibility.
Also adjusting all capitals (and related glyphs) and offering them as a stylistic set would be an immense amount of work which as this late stage is not a desirable perspective.

**Comment by GraphicOwls** [comment]
@MarcusSterz I don't quite understand what you're saying here. I agree with @marlonjames71 on this, and I too wish there was a much more discernible difference between lowercase and capital letters. It's the one thing that makes MonoLisa hard to use for me. Lowercase and uppercase letters are practically the same height, and makes skimming much much harder.

When you say something like "probably be outweighed by the negative effects regarding reading speed and legibility," I don't get how that could be possible. The whole point of making the Capitol letters taller is so _**it would be**_ much faster to read and more legible.

Again, I agree with Marlon here, and wish there was an option for taller capital letters.

**Comment by MarcusSterz** [comment]
@GraphicOwls I understand that for you a greater difference between capital height and x-height would be preferable. My statement does not change, though, I can only try to elaborate more. Looking at Fira Code and Source Code MonoLisa’s ratio is in that range. Here is a comparison between MonoLisa and Jetbrains Mono. Even in this size the difference is noticable but not big at all.

![Bildschirmfoto 2023-10-25 um 19 20 30](https://github.com/MonoLisaFont/feedback/assets/51958720/245d4603-05e0-4f56-9abb-390fb264f17d)

Please have in mind that while some wishes are easily fulfilled (like adding an alternative `&` just recently), slightly reshaping all capital letters as an option would be an enormous amount of work.
