### ISSUE TITLE
[Question]: Upgrade from "Plus v1" to "Complete v2"

### ISSUE THREAD

**Issue by timlar** [MonoLisaFont/feedback#190]
Hey everyone!

I apologize if I left the question in the wrong place, but I did not find how to write to the developers through the site.

Is there a way to upgrade the font from "Plus v1" to "Complete v2"? I only have the option to upgrade to "Plus v2". And how much does it cost?

Thanks in advance.

**Comment by bebraw** [comment]
https://www.monolisa.dev/faq#how-to-upgrade-to-a-higher-tier-bundle

**Comment by bebraw** [comment]
You would have to upgrade to v2 before upgrade to complete is possible.

**Comment by timlar** [comment]
Got it. Thanks for the information.
