### ISSUE TITLE
[Bug]: Wrong link in FAQ

### ISSUE THREAD

**Issue by CalaW** [MonoLisaFont/feedback#192]
### Edition

Basic (Personal)

### What version are you using?

2.003

### What type of weights are you using?

Default (non-customized)

### Operating system

MacOS

### What happened?

In [this FAQ section](https://www.monolisa.dev/faq#how-to-enable-nerd-fonts-with-monolisa), the link to betatoon/nerd-fonts-patcher is mistakenly pointed to [daylinmorgan/monolisa-nerdfonts-patch](https://github.com/daylinmorgan/monolisa-nerdfont-patch).

**Comment by bebraw** [comment]
Thanks, fixed. It should be online within an hour.
