### ISSUE TITLE
[Bug]: Medium and Bold 'x' are broken

### ISSUE THREAD

**Issue by thethreeonee** [MonoLisaFont/feedback#194]
### Edition

Plus

### What version are you using?

2.004

### What type of weights are you using?

Default (non-customized)

### Operating system

macOS 13.2

### Program

Microsoft Edge, VSCode, Hyper, iTerm2

### Display resolution

3960x1080

### What happened?

The bold and medium weight of charactor 'x' is broken, even on offical website.

<img width="343" alt="image" src="https://user-images.githubusercontent.com/4125903/219284000-ede9ec00-a6e3-4050-b7da-46c40660ef83.png">

**Comment by okonet** [comment]
Sorry for the inconvenience. We’re looking into fixing it asap. We’ll keep this issue updated.

**Comment by bebraw** [comment]
The web UI gives access to 2.003 now (previous version) so you have a working version until there's a fix in place.

**Comment by thethreeonee** [comment]
> The web UI gives access to 2.003 now (previous version) so you have a working version until there's a fix in place.

OK, thanks

**Comment by bebraw** [comment]
There's a fixed version available now. Release notes are at https://www.monolisa.dev/releases .
