### ISSUE TITLE
[Bug]: Variable Italics with `ss02` doesnt show the cursive script

### ISSUE THREAD

**Issue by maraisr** [MonoLisaFont/feedback#195]
### Edition

Complete (Personal)

### What version are you using?

2.003

### What type of weights are you using?

TTF ~ Static (non-customized) / Variable (non-customized)

### Operating system

MacOS Ventura 13.2 M1 Pro

### Program

VS Code

### Display resolution

3840 x 1600

### What happened?

In both scenarios the same fontLigatures set to: `'zero','ss02','ss03','ss08','ss10','ss11'`.

❌ Using the Variable TTF (default settings) `fontFamily: MonoLisa Variable` I do not get the cursive script. 

![image](https://user-images.githubusercontent.com/599459/219644182-70a78766-787d-4d01-878c-6288157a1f8a.png)

✅ But using the Static TTF (default settings) and all variables installed with `fontFamily: MonoLisa` I successfully get the cursive script.

![image](https://user-images.githubusercontent.com/599459/219644312-595c4bec-646c-4963-a369-ab0208bb14df.png)

> Please take note of the commented block right-hand-side underneath.

---

![image](https://user-images.githubusercontent.com/599459/219644475-ea5c9798-2a90-41ad-8f3b-3ade8ea725ca.png)

![image](https://user-images.githubusercontent.com/599459/219644886-20f421c5-2d7a-4d23-a5d9-3fca45ba0bf4.png)

![image](https://user-images.githubusercontent.com/599459/219645114-d43d8a54-d21b-485d-931f-16a245371fea.png)
> 2.003;FCP;MonoLisa-Regular, 2.003;FCTP;MonoLisa-RegularItalic, ...

**Comment by okonet** [comment]
From screenshots it looks like the italics weren’t installed properly. The italics you see in the first screenshot aren’t italics but a slanted upright variant. Also the font book screenshot shows 9 styles but it should be 18. Please double check that the MonoLisa Italic is installed on your computer. 

Also, for VSCode there is no need to use our customization tool so you can just download the variable font with default settings and apply the flags in VSCode like you do now.

**Comment by maraisr** [comment]
Ahh i see, the Italic ttf file also needs to be installed. Thanks for this.
