### ISSUE TITLE
how to find the ss04 `g` with the fontforge

### ISSUE THREAD

**Issue by scottming** [MonoLisaFont/feedback#196]
### What feature are you proposing?

Many terminals don't support fontLigatures, so I had to replace `g` manually, as I did with f in the image below, but I couldn't find ss04 in MonoLisaTrial-Regular.

<img width="175" alt="image" src="https://user-images.githubusercontent.com/12830256/219946854-81669438-228e-4f0d-aeac-636ec4bd80d2.png">

I don't like the original `g`

<img width="702" alt="image" src="https://user-images.githubusercontent.com/12830256/219946876-71452afb-dfde-442c-8b94-6485634d441c.png">

**Comment by bebraw** [comment]
The trial does not include any of the ss. It contains only a limited set of latin characters.

To have access to the alternate g, you would have to purchase the plus version.
