### ISSUE TITLE
[Bug]: "ri" are somewhat hard to read in the italic font

### ISSUE THREAD

**Issue by april** [MonoLisaFont/feedback#197]
### Edition

Plus

### What version are you using?

2.005

### What type of weights are you using?

Default (non-customized)

### Operating system

macOS Ventura 12.2.1

### Program

PyCharm

### Display resolution

3456 × 2234

### What happened?

Hey there! I'm using PyCharm CE, with MonoLisa set to size 11.5 (although it's also hard to read at 11), line height 1.0.

When using the normal italics, the consecutive letters "ri" are pretty difficult to read. Here is an example of "string", where the stem of the "r" runs into the "i". Overall, it's a pretty minor thing but I figured I'd file a bug since it's the only italic glyph combination I've found that is even remotely difficult to read (which is amazing).

<img width="52" alt="Screenshot 2023-02-24 at 3 33 06 PM" src="https://user-images.githubusercontent.com/230528/221298281-0ea32202-7352-4884-8900-6092cdcffc3f.png">

No worries if you want to close it out, but thought I'd bring it up just in case.  :)

**Comment by bebraw** [comment]
Could you check with 2.006? We applied a related fix for this combination.

**Comment by april** [comment]
2.005 (PyCharm):

<img width="55" alt="Screenshot 2023-04-12 at 11 03 22 AM" src="https://user-images.githubusercontent.com/230528/231516298-2d3f98a7-fa9b-4d3d-a653-1a291057edd3.png">

2.006 (PyCharm):

<img width="55" src="https://user-images.githubusercontent.com/230528/231497986-dbfc38fd-274a-4fbe-94b4-a00f9b331a21.png">

2.005 (iTerm):

<img width="55" alt="Screenshot 2023-04-12 at 11 14 55 AM" src="https://user-images.githubusercontent.com/230528/231519046-742c1d85-b674-4ee2-b4f5-a3f2d4bcb806.png">

2.006 (iTerm):

<img width="55" alt="Screenshot 2023-04-12 at 11 13 55 AM" src="https://user-images.githubusercontent.com/230528/231519128-168527b5-f792-4c9f-a50d-2bc01c4692de.png">

After looking at for a while it does seem like the spacing is a tiny bit larger? My 42-year-old eyes aren't made for this anymore. 😅

**Comment by bebraw** [comment]
Ok, maybe this one needs another pass. Thanks for the heads up.

**Comment by april** [comment]
Of course! And thank you for doing everything you do to make MonoLisa the most legible and accessible monospaced font I have used in my lifetime.  :)

**Comment by MarcusSterz** [comment]
We tweak `r`and `i` a bit so the distance gets a bit bigger. Hopefully that does the trick.

**Comment by bebraw** [comment]
Included in 2.007.

**Comment by april** [comment]
that definitely did it, it's super subtle but definitely easier to scan. hopefully it's not some placebo effect. 😂

<img width="63" alt="image" src="https://github.com/MonoLisaFont/feedback/assets/230528/5981d59a-5ad7-48c0-a0de-4bc6c1d4cd3a">

thanks again for all your hard work!

**Comment by MarcusSterz** [comment]
Happy to help!
