### ISSUE TITLE
[Bug]: The number 0 are still displayed as dotted 0.

### ISSUE THREAD

**Issue by zihluwang** [MonoLisaFont/feedback#198]
### Edition

Basic (Personal)

### What version are you using?

2.005

### What type of weights are you using?

Default (non-customized)

### Operating system

macOS Ventura 13.1

### Program

IntelliJ IDEA 2022.3.2

### Display resolution

1920*1200

### What happened?

The display of number 0 is still dotted, not slashed as you mentioned on you website.

The screenshot:
<img width="154" alt="image" src="https://user-images.githubusercontent.com/47817169/221825750-4473c7eb-865c-46be-acac-9e24dec0f808.png">

**Comment by okonet** [comment]
The font contains an open type flag `zero` that you should enable in the editor you’re using. Unfortunately not so many editors support that. Here is a longer answer: https://www.monolisa.dev/faq#how-to-enable-alternate-zero-stylistic-sets-and-the-script-variant

JetBrains product currently do not support open type features so you’d need to customize the font like we suggest in the FAQ (or upgrade to Plus to get the customization from us).
