### ISSUE TITLE
Python Ligatures to consider

### ISSUE THREAD

**Issue by mitsuhiko** [MonoLisaFont/feedback#2]
Now that I'm actually trying ligatures a bit I figured there might be some potential to make things look nicer in some more languages.

Python has triple quotes to start and end doc strings:

```python
def foo():
    """This is a comment"""

def foo():
    '''This is a comment'''
```

This might be interesting to explore as a ligature considering how prevalent this is in python code and how little the accidental chance is that this shows up somewhere else. I'm not aware of a font that does that yet.

Another ligature potential is the emacs/python file cookie marker `-*-`:

```
#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
print("Testing")
```

**Comment by bebraw** [comment]
That's a cool idea, yeah. Thanks for bringing this up! Let's see what our designer thinks.

**Comment by MarcusSterz** [comment]
> That's a cool idea, yeah. Thanks for bringing this up! Let's see what our designer thinks.

Triple quotes as ligs do not make much sense since they would not change much in appearance. I could only adjust the space between a bit. 

-*- on the other hand would be nice to make a lig of.

**Comment by okonet** [comment]
@mitsuhiko do you have any idea how triple quote ligature could look like?

We decided to implement the `-*-` one

**Comment by bebraw** [comment]
Both `"""` and `'''` have been added.

@MarcusSterz @okonet What's the deal with `-*-`? Would it make sense to support it in a Python specific stylistic set?

**Comment by MarcusSterz** [comment]
> Both `"""` and `'''` have been added in 1.500.
> 
> @MarcusSterz @okonet What's the deal with `-*-`? Would it make sense to support it in a Python specific stylistic set?

@bebraw 
We discussed that in Slack recently. I tried it out and making it a ligature does not really change how it looks so it makes no sense to create one.
https://component-driven.slack.com/archives/CSHAXUV19/p1592393667015000

**Comment by bebraw** [comment]
@MarcusSterz Ok, thanks for confirmation.

@mitsuhiko As discussed above, we won't implement `-*-` as it's not going to change the way it's rendered. `"""` and `'''` are in place.
