### ISSUE TITLE
[Bug]: vscode use light style invalid

### ISSUE THREAD

**Issue by shaodahong** [MonoLisaFont/feedback#200]
### Edition

Plus

### What version are you using?

2003

### What type of weights are you using?

Default (non-customized)

### Operating system

macos 13.0.1

### Program

vscode

### What happened?

![image](https://user-images.githubusercontent.com/14831261/224591285-6ca995c9-7d5f-4f15-9be1-bb933e0d8646.png)

when i use
```
 "editor.fontFamily": "MonoLisa light",
```
or
```
 "editor.fontFamily": "MonoLisa-light",
```
not valid,

**Comment by bebraw** [comment]
Can you try "MonoLisa Light" and match the naming of Font Book exactly as it is case sensitive?

**Comment by bebraw** [comment]
Another option would be to refer by number as in https://www.monolisa.dev/faq#how-to-change-the-font-weight-how-to-enable-variable-weight .

**Comment by shaodahong** [comment]
> Can you try "MonoLisa Light" and match the naming of Font Book exactly as it is case sensitive?

I try, and still invalid

**Comment by shaodahong** [comment]
> Another option would be to refer by number as in https://www.monolisa.dev/faq#how-to-change-the-font-weight-how-to-enable-variable-weight .

And `Plus version` not support `font-weight`?

**Comment by bebraw** [comment]
> And Plus version not support font-weight?

That's coming from the standard. Each font has a weight associated by a number.

To follow CSS spec, you would need ` "editor.fontFamily": "'MonoLisa Light'",` to match the name visible at Font Book. Is this what you tried exactly? Note the '.

**Comment by bebraw** [comment]
Another option would be

```
 "editor.fontFamily": "MonoLisa",
 "editor.fontWeight": 300
```

**Comment by bebraw** [comment]
Based on system information, the name is `MonoLisa Light Regular` so based on that `"editor.fontFamily": "'MonoLisa Light Regular'"` might do the trick if you don't want to use `fontWeight` number.

**Comment by bebraw** [comment]
Another thing to note is that the name changed between 2.003 and 2.005 for some reason. In 2.003 it was `MonoLisa Light` and in 2.005 it is `MonoLisa Light Regular`.

**Comment by bebraw** [comment]
I tested it against plus. As instructed in the FAQ, the minimal configuration for VS Code is the following:

```
  "editor.fontFamily": "MonoLisa",
  "editor.fontWeight": 300,
```

It is important **not** to set `"editor.fontVariations": true,` unless you are using a variable version.
