### ISSUE TITLE
[Bug]: Ligatures for `<(` and `>)` appeared again

### ISSUE THREAD

**Issue by gixim** [MonoLisaFont/feedback#203]
### Edition

Basic (Personal)

### What version are you using?

2.005

### What type of weights are you using?

Default (non-customized)

### Operating system

Windows 10 Home (22H2)

### Program

VSCode

### Display resolution

1920 x 1080

### What happened?

The ligatures for `<(` and `>)`, which is removed in version 2.003, is enabled again.
I think this is a regression of #136.

Expected: `<>()` and others related to `<(` and `>)` are ligatured the same way as version 2.003.

![Screenshot 2023-03-27 183118](https://user-images.githubusercontent.com/83961834/227906120-f5da8b71-7eca-4842-a094-a1fa7c46a010.png)
![Screenshot 2023-03-27 183449](https://user-images.githubusercontent.com/83961834/227906125-e33f321d-d5ef-4573-94ed-8b4bc6d3c426.png)

This can also be found on the Playground.

![image](https://user-images.githubusercontent.com/83961834/227910418-67063ef6-3ce5-41e1-8642-bd7f66e5b1d0.png)

**Comment by bebraw** [comment]
Can you try font size 11 or 14? The current version is optimized for those on low resolutions. Which font size are you using?

**Comment by gixim** [comment]
> Which font size are you using?

I'm using 20 on VSCode.

> Can you try font size 11 or 14?

Here's the screenshots. The first one is 11, and the second one is 14.

![Screenshot 2023-04-03 224930](https://user-images.githubusercontent.com/83961834/229530176-38c8d7f8-9ac8-4533-aa43-a1ca8811051c.png)
![Screenshot 2023-04-03 225005](https://user-images.githubusercontent.com/83961834/229530185-376ad11d-4e1f-4081-be89-9e3abfb258c2.png)

In my opinion, if `<(` and `>(` won't be removed, at least they shouldn't be prioritized than `<>`, `>>`, `<<`, etc. because prioritized `<(` and `>(` will produce weird syntax highlighting.

**Comment by MarcusSterz** [comment]
@bebraw This issue is not related to the font size.

**Comment by bebraw** [comment]
Yeah, I commented on the wrong issue by accident.

**Comment by bebraw** [comment]
Implemented and published in 2.006.
