### ISSUE TITLE
[Bug]: ss11 (hexadecimal x) doesn't apply smaller 'x' in conjunction with ss02 (script variant)

### ISSUE THREAD

**Issue by ericvw** [MonoLisaFont/feedback#205]
### Edition

Plus

### What version are you using?

2.005

### What type of weights are you using?

Default (non-customized)

### Operating system

macOS  Ventura 13.2.1

### Program

kitty

### Display resolution

1440x900

### What happened?

In my `kitty.conf`, I set 

```
font_family   MonoLisa
font_size     16.0
font_features MonoLisa-Regular               +ss10 +ss11 +ss12
font_features MonoLisaSemiBold-Regular       +ss10 +ss11 +ss12
font_features MonoLisa-RegularItalic   +ss02 +ss10 +ss11 +ss12
font_features MonoLisaSemiBold-Italic  +ss02 +ss10 +ss11 +ss12
```
and was expecting the `0xf` to have a hexadecimal script `x` variant. 

Instead, it shows the normal script `x` variant, as seen in the screenshot below.

<img width="680" alt="Screenshot 2023-04-03 at 10 41 54 PM" src="https://user-images.githubusercontent.com/1284017/229674012-cca17b12-6bb3-433d-b3a9-1991fc733591.png">

**Comment by bebraw** [comment]
Implemented and published in 2.006.

**Comment by ericvw** [comment]
@bebraw, this doesn't appear fixed in the 2.006 release. I just downloaded the latest release and `0xff` in the script variant is the same as `text with an x`.

![Screenshot 2023-04-12 at 09 02 06](https://user-images.githubusercontent.com/1284017/231465667-9e5b2b9c-d2ab-42d7-93c2-8ea2dd8944f4.png)

**Comment by bebraw** [comment]
Ok, maybe something went wrong with the fix. cc @MarcusSterz.

**Comment by MarcusSterz** [comment]
Appears I have forgotten to include a.ss02 d.ss02 f.ss02  in `@digits`. Will be fixed.

**Comment by bebraw** [comment]
Included in 2.007.

**Comment by ericvw** [comment]
Thank you for fixing this! 🤗

**Comment by MarcusSterz** [comment]
You are welcome!
