### ISSUE TITLE
[Feature request]: Version 2 paid upgrade.

### ISSUE THREAD

**Issue by mpedrojr** [MonoLisaFont/feedback#206]
### What feature are you proposing?

I paid $62 USD about a year ago so now they created a version 2 just to charge a little extra to the ones supported the product/project by paying for a paid license. If the basic is the new personal plan why no to upgrade the users automatically?

When I paid for my plan there was not a version number so it was a Monolisa font personal plan only and now I got the surprise.

If you buy the version 2, tomorrow they will charge you for the version 3 and then the version 4 and so on.

**Comment by sonulohani** [comment]
FYI, there was always the version number. Here is the link: https://www.monolisa.dev/releases

**Comment by bebraw** [comment]
The upgrade scheme is explained at https://www.monolisa.dev/faq#how-can-i-upgrade-from-version-1-to-version-2 .
