### ISSUE TITLE
[Feature request]: Dong Currency Character “₫” (U+20AB)

### ISSUE THREAD

**Issue by dinhquochan** [MonoLisaFont/feedback#207]
### What feature are you proposing?

Hi team,

I request you this character. It's in Vietnamese set - VND - Dong sign: “₫” (U+20AB)

![image](https://user-images.githubusercontent.com/9979458/231536307-389f9023-3bc0-42ba-b81f-a6ee1e08da3f.png)

Thanks.

**Comment by MarcusSterz** [comment]
Will be in the upcoming version :)

**Comment by dinhquochan** [comment]
Thank @MarcusSterz

**Comment by bebraw** [comment]
Included in 2.007.
