### ISSUE TITLE
Characters/glyphs size inconsistent 13/14px vscode windows

### ISSUE THREAD

**Issue by Eldair** [MonoLisaFont/feedback#21]
Hello,

Some of the characters are not rendering correctly on some font sizes
using vscode on windows 10 (1920*1080)

13px:
![image](https://user-images.githubusercontent.com/470003/79994213-f3a75c00-84b5-11ea-8513-34d4dc6c5cde.png)

14px:
![image](https://user-images.githubusercontent.com/470003/79994271-0588ff00-84b6-11ea-87f5-b9117bfe858b.png)

It's larger (normal) on 13px

**Comment by bebraw** [comment]
This is related to #19. Likely when that's solved, then this one is as well.

**Comment by bebraw** [comment]
Closing in favor of #24.
