### ISSUE TITLE
[Feature request]: Implement U+2010 HYPHEN glyph

### ISSUE THREAD

**Issue by ericvw** [MonoLisaFont/feedback#211]
### Edition

Plus

### What version are you using?

2.006

### What type of weights are you using?

Static (customized)

### Operating system

macOS Ventura 13.3.1

### Program

kitty Terminal Emulator

### Display resolution

3840x2160

### What happened?

When running `man dot`, the [groff `\(hy`](https://www.gnu.org/software/groff/manual/html_node/Manipulating-Hyphenation.html) used in manpages does not render the Unicode codepoint U+2010 HYPHON because the glyph doesn't exist.

![Screenshot 2023-05-09 at 12 47 51](https://github.com/MonoLisaFont/feedback/assets/1284017/204582c1-1d4c-4fbc-877f-1ff078a9b773)

Alternatively, you can run `python -c "print('a\u2010b')"` to reproduce.

**Comment by ericvw** [comment]
The issue does not occur with the "MonoLisa Trial" Regular font.

**Comment by ericvw** [comment]
Ahh, the Trial doesn't specify `.notdef`. I bet the font renderer is falling back to some other font for U+2010 that I didn't notice. I checked https://www.monolisa.dev/specimen, and it appears U+2010 is not present.

Instead of this being a bug, please feel free to change this issue to be an enhancement request to provide U+2010, please 😄.

**Comment by MarcusSterz** [comment]
No problem, it will be included in the next update.

**Comment by bebraw** [comment]
Included in 2.007.

**Comment by ericvw** [comment]
Thank you for the quick turnaround on this! 🤗

**Comment by MarcusSterz** [comment]
No prob 👍
