### ISSUE TITLE
[Bug]: Vietnamese characters break after upgrade to version 2.007 (on playground)

### ISSUE THREAD

**Issue by dinhquochan** [MonoLisaFont/feedback#212]
### Edition

Plus (Personal)

### What version are you using?

2.007

### What type of weights are you using?

Default (non-customized)

### Operating system

macOS 13.3.1

### Program

VS Code

### Display resolution

4K

### What happened?

Dear MonoLisa team,

When I upgrade the typeface to v2.007, I got some problems with Vietnamese characters:

Before:

<img width="1100" alt="image" src="https://github.com/MonoLisaFont/feedback/assets/9979458/0f1c11e8-04db-4b1e-8ec8-2c1995c80a6b">

After:

<img width="1170" alt="image" src="https://github.com/MonoLisaFont/feedback/assets/9979458/4e7fd9c0-1aaf-4a32-b032-53d9c81eae4b">

```
a á à ả ã ạ ă ắ ằ ẵ ẳ ặ â ấ ầ ẫ ẩ ậ
A Á À Ả Ã Ạ Ă Ắ Ằ Ẵ Ẳ Ặ Â Ấ Ầ Ẫ Ẩ Ậ
i í ì ỉ ĩ ị
I Í Ì Ỉ Ĩ
u ú ù ũ ủ ụ ư ứ ừ ữ ử ự
U Ú Ù Ũ Ủ Ụ Ư Ứ Ừ Ữ Ử Ự
o ó ò õ ỏ ọ ô ố ồ ỗ ổ ộ ơ ớ ờ ỡ ở ợ
O Ó Ò Õ Ỏ Ọ Ô Ố Ồ Ỗ Ổ Ộ Ơ Ớ Ờ Ỡ Ở Ợ
y ý ỳ ỷ ỹ ỵ
Y Ý Ỳ Ỷ Ỹ Ỵ
```

**Comment by dinhquochan** [comment]
It's ok in VS Code.

<img width="639" alt="image" src="https://github.com/MonoLisaFont/feedback/assets/9979458/9cab6af2-393f-4b12-96b3-83b6956c0023">

**Comment by MarcusSterz** [comment]
Interesting, I will have a look asap.
