### ISSUE TITLE
[Bug]: Shows bold font weight no matter what weight selected in Windows Terminal, no ligatures in Sublime Text [FIXED]

### ISSUE THREAD

**Issue by diopsidedesign** [MonoLisaFont/feedback#213]
### Edition

Complete (Pro)

### What version are you using?

2.007

### What type of weights are you using?

Static (customized)

### Operating system

Windows 10 latest feature update

### Program

Windows Terminal, Sublime Text 4, maybe others

### What happened?

I'm not sure if this is actually a 'bug' or simply user error, but since I could find no other way to ask a question , bug report it is. 

I just bought and installed the newest version of Mono Lisa (the complete package). I used the 'static' package since I read that Sublime Text doesn't have good variable font support. I made sure to add the 'new' prefix when downloading the zip on your site so that I could have the new version installed alongside the old version. I installed the fonts via the usual process (drag-dropping into the newer windows font page in the settings menu) and everything seemed fine there. I went into Windows Terminal to change over to the new version and though the font appears in the menu fine, it seems like no matter what font weight I select for the new version of Mono Lisa, it only shows the bold or black weights. You can see here I have the 'light' weight selected and it still is showing the bold weight (I think). It shows that same weight for nearly all the listed weights except for black, which, weirdly, it does seem to display correctly. So I can have either bold or bolder in my terminal, currently. Which isn't really gonna work. I understand that windows terminal is sort of a "beta" software but I have observed this behavior with no fonts other than this one so I thought I would ask. The font seems to work OK in Sublime Text 4, but it defaults to the Bold weight (which again, is a behavior I've observed in no other font) so you have to explicitly tell it to use the medium weight to have it look right. Maybe that is related to this issue? 

<img width="966" alt="terminalfontweight" src="https://github.com/MonoLisaFont/feedback/assets/29055020/5c2a6b69-47ab-46dc-8378-18ac2b399ed8">

keep up the good work! I love your font so much that trying to code without it feels like a handicap now :P

**Comment by bebraw** [comment]
That sounds weird.

Can you see the same problem with an editor like VS Code or in other terminals?

Can you see the same behavior with the variable version? The OS should detect the different weights included automatically in that case.

It's also worth checking the `Fonts` section at system preferences.

You can also try dropping a font file at https://fontdrop.info/ as it's able to give a nice statistics related to the file.

**Comment by diopsidedesign** [comment]
hey thanks for the quick response. I just updated the report w/ a little more info. In Sublime Text it seems to work just fine but i have to explicitly tell it to use the medium weight (or anything other than bold) weight. If I just use the typical syntax  "font_face: MonoLisa new"  it will show the same bold weight that is seen in the screenshot in the OP. 

I just thought of something else that may be relevant. When I was installing these, I opened up the zip and installed a few from the top of the list via a different process (double clicking them to open the TTF font preview, and then clicking the install button from that window). Once i remembered that the new font dialog allowed installing a bunch of fonts at once via drag and drop, i installed the rest of the weights via that method. It seems like an odd coincidence that the font weights i installed "manually" using the older ctrl-panel style interface were the BOLD and BLACK weights that seem to be giving me issues. Hmmmmmm

**Comment by bebraw** [comment]
> I just thought of something else that may be relevant. When I was installing these, I opened up the zip and installed a few from the top of the list via a different process (double clicking them to open the TTF font preview, and then clicking the install button from that window). Once i remembered that the new font dialog allowed installing a bunch of fonts at once via drag and drop, i installed the rest of the weights via that method. It seems like an odd coincidence that the font weights i installed "manually" using the older ctrl-panel style interface were the BOLD and BLACK weights that seem to be giving me issues. Hmmmmmm

If there's an older version in place, it could be a conflict somewhere. Maybe the safest bet would be to remove the font (all versions of it), clear font cache (if possible on Windows), and re-install the way you described.

[Here are Microsoft's official instructions for reference.](https://support.microsoft.com/en-us/windows/how-to-install-or-remove-a-font-in-windows-f12d0657-2fc8-7613-c76f-88d043b334b8)

**Comment by diopsidedesign** [comment]
yeah that definitely seems likely. I will try the nuke-from-orbit-and-reinstall approach and report back

**Comment by diopsidedesign** [comment]
All seems good now.

I wiped both the old and new versions of MonoLisa and reinstalled only the new version. I tried the variable weight version first. It works great in Windows Terminal - all weights appear and display correctly. As the internet suggested, the variable weight version didn't work great in Sublime Text 4 (Sublime will apparently recognize and allow you to select variable weight fonts, but there's no way to specify what weight to use, so I was stuck w/ the very thin weight that it defaulted to). Bummer, but not yalls problem. I installed the static version of the new font alongside the variable weight version but using a different prefix. And that version works perfect in Sublime. 

I'm still not sure what caused the original issue. In addition to the quirks indicated in the OP, I also noticed that my issue seemed to be causing a reduction in line spacing on the terminal...? In Windows Terminal, even the old version of MonoLisa was suddenly displaying w/ like 50-70% of the expected inter-line padding, causing it to look quite crowded. This all seems to be corrected w/ a delete and reinstall (I did not bother trying to clear the Font Cache).

**Comment by bebraw** [comment]
Ok, cool to hear it works now. Let's close.

**Comment by diopsidedesign** [comment]
Well, perhaps I spoke too soon. Now I am encountering a different but possibly still related issue.   ligatures no longer work in my text editor on the static weight version. Its not a syntax-specific problem because even on a plain text file the ligatures do not show up w/ the new MonoLisa selected as a font. Weirdly, they DO work with the variable weight version selected, but that is not really a solution since as i mentioned previously it is stuck on the thinnest weight. 

I thought maybe the issue was from having both of them installed side-by-side, so I tried uninstalling the variable weight version (since Windows Terminal now appeared to be working normally with both versions of the font). 

When I uninstalled the variable weight version, suddenly I'm back to my original problem. In both Sublime and in Windows terminal, no matter what the font weight selection, it only will show bold or extra bold weights. I tried deleting my font cache and that seemed to have no effect.

I'm pretty frustrated that i just spent so much on a font only to discover that it can't fit into my workflow without sacrificing ligatures or the ability choose which weight i'd like to use. :-I

**Comment by bebraw** [comment]
> Well, perhaps I spoke too soon. Now I am encountering a different but possibly still related issue. ligatures no longer work in my text editor on the static weight version. Its not a syntax-specific problem because even on a plain text file the ligatures do not show up w/ the new MonoLisa selected as a font. Weirdly, they DO work with the variable weight version selected, but that is not really a solution since as i mentioned previously it is stuck on the thinnest weight.

Which text editor are you using? Can you provide exact steps on how to reproduce this one?

**Comment by diopsidedesign** [comment]
the newest build of Sublime Text (ver 4143). 

Not sure if it will be possible to reproduce since it still seems related to something like a name collision that's specific to my system, but in general: 

- Have the old version of mono lisa installed
- install a static weight version of the new MonoLisa (2.007) with the prefix "new". Before installing, replace the hyphens in the file name w/ underscores ( could this be my issue??? I wouldn't think the actual name of the file itself would matter but I truly have no idea, i do this almost out of compulsion for most things). And For full reproducibility, I guess use the old windows control-panel-like interface to install some of the weights, and the more modern font settings UI to install the rest. 
- Try to use the font in Windows Terminal, only see bold weights
- Uninstall the old version of MonoLisa, problem persists
- Uninstall all versions, reinstall ONLY new version in the variable weight form, this time without any special prefix
- Notice that the variable version works perfectly in Windows Terminal but not in my text editor (where ligatures do work, but the weight is stuck on the thinnest weight)
- Try installing the static weight version again, this time with the prefix "Static" 
- Now, all the weights of both versions appear to display correctly in Windows Terminal. But Sublime has the same issues w displaying no ligatures (or bolded text - though it does show italics) on the static weight versions.
- Uninstall the variable weight version to see if the static and variable versions are somehow interfering

I think that's everything. Each time I downloaded my package of the font I did select a few customization options w.r.t the ligatures. I think I selected the alternate @ symbol and hexadecimal x every time.

**Comment by bebraw** [comment]
Ok, I have something in mind we can potentially try. We changed the build process so it's possible it affected something on Windows. There could be some subtle difference in font metadata for example.

I will ping once there is an alternative build to test against. Esp. if everything worked on 2.006, this would likely do the trick.

**Comment by diopsidedesign** [comment]
ok cool. 2.007 is the only version of the new release I've had a chance to try.  If there is a way to try older versions it isn't obvious to me on the website, but its no issue to keep using ver 1 release in the meantime. always happy to test

**Comment by bebraw** [comment]
@diopsidedesign There's a new build to test. To try it, set the download to **prerelease** at the orders page. Take your time.

**Comment by diopsidedesign** [comment]
heck yeah this seems to immediately resolve all the problems. Windows Terminal and Sublime Text all look and behave as expected, and its happily working alongside the old version w/ the 'New' prefix.

Thanks so much.

P.S - not sure how I only JUST NOW realized that i filed this issue without a title   ......  -_-

**Comment by bebraw** [comment]
Published as 2.008. Thanks for the report.
