### ISSUE TITLE
[Bug]: Custom font name is being lowercased on Windows

### ISSUE THREAD

**Issue by brettcannon** [MonoLisaFont/feedback#216]
### Edition

Plus

### What version are you using?

2.008

### What type of weights are you using?

Static (customized)

### Operating system

Windows 11

### Program

Windows Terminal

### What happened?

I downloaded my normal custom font family of MonoLisa based on 2.008 for my terminal, but then Windows Terminal told me my font disappeared. Looking in the font settings in Windows itself it looks like my "Terminal" name for my font name suffix is now being considered lowercase by Windows. That caused Windows Terminal to no longer find "MonoLisa Terminal", so I had to change the settings to use "MonoLisa terminal" (notice the lowercase "t" on "terminal").

![image](https://github.com/MonoLisaFont/feedback/assets/54418/5c506166-cb7e-455a-aea6-5597a4de3c00)

This was working fine with 2.007 and before.

**Comment by bebraw** [comment]
I cannot reproduce this. You can find my test screenshots below:

<img width="715" alt="Screenshot 2023-06-22 at 14 47 49" src="https://github.com/MonoLisaFont/feedback/assets/166921/85f97957-b0d6-4a00-bb73-1e08ada4f70d">

<img width="1126" alt="Screenshot 2023-06-22 at 14 47 34" src="https://github.com/MonoLisaFont/feedback/assets/166921/e72c38c1-9bef-4ad4-b409-e4602a44a162">

<img width="337" alt="Screenshot 2023-06-22 at 14 48 19" src="https://github.com/MonoLisaFont/feedback/assets/166921/7a737d75-4559-4bc2-9ae1-1cd6a71c2d3c">

**Comment by brettcannon** [comment]
Looks like it may have been a weird Windows bug as I also cannot reproduce.

Thanks for looking into this!
