### ISSUE TITLE
Licensing Question

### ISSUE THREAD

**Issue by F1LT3R** [MonoLisaFont/feedback#22]
I purchased the basic package. Are we allowed to use the font in tutorial videos?

Generally, if we have a video, screenshot, etc. using the MonoLisa font, are we legally ok to share such images/videos?

**Comment by bebraw** [comment]
Hi Alistair,

For the personal edition, it’s enough if you attribute somewhere and mention which font was used. In YouTube you would use the description field for example and/or mention at the end with other acknowledgments.

**Comment by F1LT3R** [comment]
Thanks @bebraw - I will definitely give attribution and provide a link. Also happy to personally recommend the font for readability. It's a great font.

**Comment by F1LT3R** [comment]
It might be worth updating the page here: https://www.monolisa.dev/license

It's not entirely clear to me. (Perhaps it would be clear to someone who understood legal terms.)

**Comment by bebraw** [comment]
We've updated the license page so it's more clear about the usage. Feel free to open another issue if there's still something that's not quite right.
