### ISSUE TITLE
[Bug]:  Script Variant Issue

### ISSUE THREAD

**Issue by mnco25** [MonoLisaFont/feedback#220]
### Edition

Plus

### What version are you using?

2.008

### What type of weights are you using?

Default (non-customized)

### Operating system

Windows 11, 22H2, 22631.1835

### Program

VS Code

### Display resolution

1920 x 1080

### What happened?

I have included an image of my VS Code interface showing the Java program and the settings.json file. I'm experiencing difficulties in applying a script variant from my IDE, and I would greatly appreciate any assistance with this matter. Thank you so much!

![image](https://github.com/MonoLisaFont/feedback/assets/75378716/5c2014d4-c228-40b0-a73f-7ffe7ebe1b1d)

Additionally, I would like to have the same font format as the one used on the MonoLisa website for my ID.

![image](https://github.com/MonoLisaFont/feedback/assets/75378716/7080e2fb-e866-4c61-8ea4-96196149b862)

And this is my installed font styles:

![image](https://github.com/MonoLisaFont/feedback/assets/75378716/52fbf524-9846-4c48-83e0-4b5abfc44220)

This is my custom installed zip file:

![image](https://github.com/MonoLisaFont/feedback/assets/75378716/013b9d06-fd38-48cb-a1ea-f8563357661a)

**Comment by bebraw** [comment]
VS Code supports opentype features out of the box so you should use a **non-customized** version with it and enable script variant through settings as below:

```json
{
  "editor.fontLigatures": "'ss02' on",
  "editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": "comment",
        "settings": {
          "fontStyle": "italic"
        }
      }
    ]
  }
}
```

See also https://www.monolisa.dev/faq#how-to-enable-the-script-variant-for-comments-or-function-names .

**Comment by Mac-25** [comment]
> VS Code supports opentype features out of the box so you should use a **non-customized** version with it and enable script variant through settings as below:
> 
> {
>   "editor.fontLigatures": "'ss02' on",
>   "editor.tokenColorCustomizations": {
>     "textMateRules": [
>       {
>         "scope": "comment",
>         "settings": {
>           "fontStyle": "italic"
>         }
>       }
>     ]
>   }
> }
> ![](https://storage.googleapis.com/pieces-web-extensions-cdn/pieces.png)
> Copy and Save
> ![](https://storage.googleapis.com/pieces-web-extensions-cdn/link.png)
> Share
> See also https://www.monolisa.dev/faq#how-to-enable-the-script-variant-for-comments-or-function-names .

What should I put on my **Editor: Font Family**?

**Comment by mnco25** [comment]
I did that, and this is what happened.

![image](https://github.com/MonoLisaFont/feedback/assets/75378716/bd146852-cb4d-417c-a11e-55892e2c2dca)

Should I put on my **Editor: Font Family**?

**Comment by bebraw** [comment]
> Should I put on my Editor: Font Family?

That should be like this:

> "editor.fontFamily": "MonoLisa",

You can use that `editor.fontLigatures` portion to enable specific features you want.

**Comment by bebraw** [comment]
> Should it be "MonoLisa Mac Medium Italic"? If I want to use the italic one?

No, just `MonoLisa` since the editor is doing rest of the work and it's extremely important to use the non-customized version with VS Code.

**Comment by mnco25** [comment]
This is what I get for **"MonoLisa":**
![image](https://github.com/MonoLisaFont/feedback/assets/75378716/088896ad-9226-4c5f-9892-10e2a2254f8e)

This is when I used **"Monolisa Mac"** it gives me the script variant for ONLY the comment.
![image](https://github.com/MonoLisaFont/feedback/assets/75378716/7d99af73-3a55-423c-ab36-777f3f5f96f7)


https://github.com/MonoLisaFont/feedback/assets/75378716/e7a238b8-96e4-4946-bed4-cdd6d1fae359

**Comment by bebraw** [comment]
You can validate the font files you have at https://fontdrop.info/ . For non-customized version all stylistic sets are toggleable.

Note that ss02 has been defined only for italic. That's why you have to adjust a theme to match it.

**Comment by mnco25** [comment]
I got it now. **Thank you so much for your assistance!**
