### ISSUE TITLE
[Bug]: Font name display error

### ISSUE THREAD

**Issue by lieuvu** [MonoLisaFont/feedback#221]
### Edition

Complete (Personal)

### What version are you using?

2.008

### What type of weights are you using?

Variable (customized)

### Operating system

MacOS Ventura 13.4

### Program

Xcode 14.3

### What happened?

I have two fonts `MonoLisa (version 1)` and `MonoLisa V2`. The font name is displayed weirdly for `MonoLisa V2` in Xcode 14.3.

**MonoLisa (version 1)**: The font is displayed as **MonoLisa Medium - 11.0** ✅
<img width="1526" alt="Screenshot 2023-06-20 at 10 14 17 AM" src="https://github.com/MonoLisaFont/feedback/assets/16427754/50f28a0a-78ae-4185-9048-3c7680b53ebb">

**MonoLisa V2**: The font is displayed as **MonoLisa V2 Regular Medium - 11.0** ❌
<img width="1526" alt="Screenshot 2023-06-20 at 10 14 35 AM" src="https://github.com/MonoLisaFont/feedback/assets/16427754/e04efe14-1588-43b0-bd61-618722fcf6e8">

**MonoLisa (version 1)**: The font is displayed as **MonoLisa Light Italic - 11.0** ✅
<img width="1528" alt="Screenshot 2023-06-20 at 10 14 50 AM" src="https://github.com/MonoLisaFont/feedback/assets/16427754/8762900c-9c30-4da8-8f6a-d0c497681c51">

**MonoLisa V2**: The font is displayed as **MonoLisa V2 Regular Italic Light Italic - 11.0** ❌
<img width="1526" alt="Screenshot 2023-06-20 at 10 15 23 AM" src="https://github.com/MonoLisaFont/feedback/assets/16427754/acbf59ef-616f-4db0-ac32-c497962a047b">

**Comment by bebraw** [comment]
Can you see the same behavior in the non-customized v2?

At least the Regular case might be expected since there may have been a slight change in naming in v2 but the name for italic looks off for v2.

**Comment by lieuvu** [comment]
Yes, I still see the same thing in the non-customized v2. Actually, I downloaded the non-customized v2.

**Comment by bebraw** [comment]
Can you see the same behavior in other apps that provide a UI for selecting the font (i.e., Affinity, Adobe products, Font Book, whatnot)?

**Comment by lieuvu** [comment]
There are differences in the postscript name and unique name between v1 and v2. The screen shot is from Font Book application.

**MonoLisa (version 1)**: The font postscript name is `MonoLisa-ExtraLightItalic` and unique name is `2.002;FCTP:MonoLisa-ExtraLightitalic`
![Screenshot 2023-06-21 at 7 58 04 PM](https://github.com/MonoLisaFont/feedback/assets/16427754/2a118c9f-93ae-49f8-891c-bf8768dc0496)

**MonoLisa V2**: The font postscript name is `MonoLisaV2RegularItalic-ExtraLightItalic` and unique name is `2.008;FCTP:MonoLisaV2Regularitalic`
![Screenshot 2023-06-21 at 8 02 38 PM](https://github.com/MonoLisaFont/feedback/assets/16427754/2eab1f7a-2ef8-4f88-98a4-6514916bd78b)

**Comment by bebraw** [comment]
This will be changed in the next version that is available as a prerelease now (plus or complete). It won't match the old behavior but it should be better than now.

It may be worth it to report the issue to xcode regardless since it seems they derive the font name differently than other software.

**Comment by bebraw** [comment]
It should look better in 2.009 (just released).

**Comment by bebraw** [comment]
It should look better in 2.009 (just released).
