### ISSUE TITLE
[Bug]: Using backticks breaks rendering

### ISSUE THREAD

**Issue by bebraw** [MonoLisaFont/feedback#222]
### Edition

Plus

### What version are you using?

2.009 (prerelease)

### What type of weights are you using?

Default (non-customized)

### Operating system

MacOS

### Program

VS Code

### What happened?

If I enter a backtick (`) to my code, it renders it like below:

<img width="279" alt="Screenshot 2023-07-07 at 9 34 15" src="https://github.com/MonoLisaFont/feedback/assets/166921/4db34c5b-79aa-42c9-b0a7-735f2d4cf1ef">

Expected render in another font for comparison:

<img width="258" alt="Screenshot 2023-07-07 at 9 34 29" src="https://github.com/MonoLisaFont/feedback/assets/166921/17d2da59-730d-4917-8662-792b34dec21a">

**Comment by jpallatin** [comment]
Yes. I experienced this while writing some JS code (testing 2.009) . IMHO, that backtick character could use a little better design, it seems a little inconsistent to me in the font collection (it's somewhat "light" or not visible enough) especially when compared to the single and double quotes.

**Comment by MarcusSterz** [comment]
@jpallatin What you call backtick in programming is actually an accent called ‘grave’ (like acute, dieresis, ring, caron etc). It is not a variation of or connected to quote symbols therefor the lack of resemblance. In fact it is key to distinguish accents from quotes to prevent confusion. It is usually combined with other letters to create diacritics like à, ò, ì and so on. 

We are looking into this issue :)

**Comment by jpallatin** [comment]
Understood Marcus, that makes all the sense, thanks for the explanation.

**Comment by bebraw** [comment]
@jpallatin I pushed a new prerelease with the fix to test. It worked locally for me.

**Comment by jpallatin** [comment]
Thank you. I'm testing right now. So far so good. Reported bug is fixed.

**Comment by bebraw** [comment]
Ok, let's close. Thanks for confirming.
