### ISSUE TITLE
[Bug]: Symbols from powerline-extra are not present?

### ISSUE THREAD

**Issue by lucastrvsn** [MonoLisaFont/feedback#224]
### Edition

Plus

### What version are you using?

2.009

### What type of weights are you using?

Static (customized)

### Operating system

MacOS Ventura

### Program

Alacritty

### Display resolution

4K

### What happened?

Hello! I've just bought the font and it looks amazing! But I'm a bit disappointed that all my powerline symbols are gone or are rendering weirdly. Looks like the MonoLisa is trying to render some symbols that are not supported, for example:

Using [JuliaMono](https://juliamono.netlify.app/):
<img width="356" alt="Screenshot 2023-08-22 at 10 51 01" src="https://github.com/MonoLisaFont/feedback/assets/8826449/215ec36e-657a-4b38-95b2-4caeab4744f8">

Using MonoLisa (Plus):
<img width="391" alt="Screenshot 2023-08-22 at 10 51 20" src="https://github.com/MonoLisaFont/feedback/assets/8826449/024cef54-5480-4a31-b436-bd02de9955be">

The symbols I'm trying to render here are from [powerline-extra-symbols](https://github.com/ryanoasis/powerline-extra-symbols) (which is installed on my system, but seems like MonoLisa is trying to provide the symbols and not allowing to fallback to other fonts).

Other powerline-extra symbols are rendered as:
<img width="262" alt="Screenshot 2023-08-22 at 10 59 10" src="https://github.com/MonoLisaFont/feedback/assets/8826449/775e3a2d-d2d2-4c40-b062-fe59ddb1dfc5">

It's possible to change this or provide the symbols from powerline-extra as well? Thank you!

**Comment by bebraw** [comment]
Can you try https://www.monolisa.dev/faq#how-to-enable-nerd-fonts-with-monolisa ? You would have to use a tool like https://github.com/daylinmorgan/monolisa-nerdfont-patch to add the additional symbols to the font.

**Comment by lucastrvsn** [comment]
> Can you try https://www.monolisa.dev/faq#how-to-enable-nerd-fonts-with-monolisa ? You would have to use a tool like https://github.com/daylinmorgan/monolisa-nerdfont-patch to add the additional symbols to the font.

Sure! I'll do that right now. I didn't realise that we have this section on the FAQ. My bad! 🙌

**Comment by bebraw** [comment]
No worries, I'll move the related question behind the terminal section as it fits there better.
