### ISSUE TITLE
[Bug]: Monolisa version 2.009 does not validate correctly on macOS

### ISSUE THREAD

**Issue by ThorstenRhau** [MonoLisaFont/feedback#225]
### Edition

Plus

### What version are you using?

2.009

### What type of weights are you using?

Default (non-customized)

### Operating system

macOS 13.5.1

### Program

macOS built in FontBook.app

### Display resolution

5k retina Studio display at 1440p scaling

### What happened?

I removed Monolisa font version 2.008 from the system. Cleared the font cache and installed version 2.009. This new version of Monolisa does not validate correctly.

'name' table usability
'name' table structure

The two items above fail validation for all italic fonts of this typeface.

**Comment by bebraw** [comment]
@MarcusSterz I noticed that you can see the validation warning **only** in the version downloaded from https://www.monolisa.dev/orders but not in the original source so maybe it's something in the API. I wonder what the validation warnings mean.

**Comment by okonet** [comment]
Not sure either. But we didn’t change anything on the API between these versions so I bet it must be something in the font since we did change things there, didn’t we?

**Comment by ThorstenRhau** [comment]
The unaltered downloaded version of the Plus version is 1,4 MB for 2.008 and 1,7MB for 2.009.

**Comment by bebraw** [comment]
> Not sure either. But we didn’t change anything on the API between these versions so I bet it must be something in the font since we did change things there, didn’t we?

Yup, must be the font source.

> The unaltered downloaded version of the Plus version is 1,4 MB for 2.008 and 1,7MB for 2.009.

That could be the added characters for the improved language support.

**Comment by MarcusSterz** [comment]
> The unaltered downloaded version of the Plus version is 1,4 MB for 2.008 and 1,7MB for 2.009.

The increase is related to the extended language support.

**Comment by ThorstenRhau** [comment]
Should there be any information that I can provide to make the troubleshooting about this bug easier please let me know.

**Comment by MarcusSterz** [comment]
Thx! We are on it and there will be an update soon.

**Comment by bebraw** [comment]
Fixed in 2.010 available now.
