### ISSUE TITLE
[Feature request]: Dollar alternative with full line through

### ISSUE THREAD

**Issue by bruderstein** [MonoLisaFont/feedback#226]
### What feature are you proposing?

Would you consider an alternative for the `$` sign, with a line all the way through? As it is, for me, it's too close to capital S and difficult to see the difference.

Compare:
<img width="114" alt="Screenshot 2023-08-22 at 22 33 08" src="https://github.com/MonoLisaFont/feedback/assets/91716/eacc4be2-3c3f-4b6a-8ace-55d3fa0d7d52">

vs (excuse my terrible artwork, but just to demonstrate)
<img width="114" alt="withline" src="https://github.com/MonoLisaFont/feedback/assets/91716/bcef807a-8e76-4300-a4d3-15dac3b2e357">

**Comment by dinhquochan** [comment]
Yes. +1 here.

**Comment by bebraw** [comment]
We discussed the issue and decided to try to alter the standard glyph and its readability. We have a couple of options in mind.

Can you confirm the issue is about legibility?

**Comment by bruderstein** [comment]
Yes, absolutely about legibility, specifcally about distinguishing it from other similar characters (i.e. capital `S`). 

`$witch` and `Switch` are not easy to tell apart at the moment, for example.

Many thanks for considering this!

**Comment by dinhquochan** [comment]
Yes, It's similar "S". I use a lot of `$` in PHP an jQuery, JavaScript. 

Thanks if you consider adding it to the alt set.

<img width="660" alt="image" src="https://github.com/MonoLisaFont/feedback/assets/9979458/980c2439-8a21-4df8-b3a8-20187af8c4a4">

Compared at Berkeley Mono

<img width="608" alt="image" src="https://github.com/MonoLisaFont/feedback/assets/9979458/34ab0800-d7e3-43e0-a442-76ce6d615ef2">

 and SF Mono:

<img width="625" alt="image" src="https://github.com/MonoLisaFont/feedback/assets/9979458/bc81ca46-7ce8-4768-9752-b58a8c8a6d78">

**Comment by MarcusSterz** [comment]
There will be a alternative for the Dollar sign available with the upcoming version 2.011 – stay tuned!

**Comment by bruderstein** [comment]
That is fantastic news, thanks so much for considering this & doing it - really looking forward to seeing it!

**Comment by bebraw** [comment]
Included to newly released 2.011.
