### ISSUE TITLE
[Bug]: Variable black regular font name error

### ISSUE THREAD

**Issue by xqdoo00o** [MonoLisaFont/feedback#227]
### Edition

Complete (Pro)

### What version are you using?

2.010

### What type of weights are you using?

Variable (customized)

### Operating system

Windows 10 21H1

### Program

VSCode

### Display resolution

1920*1080

### What happened?

Open folder C:\Windows\Fonts, check the MonoLisa Variable font, found that there are two `MonoLisa Variable Regular`, missing the `MonoLisa Variable Black`.
![image](https://github.com/MonoLisaFont/feedback/assets/12299238/88691fd0-086d-4940-9a84-c4e7c109d4cf)

And after check the static MonoLisa font, there is no such error.

**Comment by okonet** [comment]
I’m not entirely sure how you arrived at this state since variable font shouldn’t have separate weights exposed. Have you downloaded the variable version or static one on the customization form?

**Comment by xqdoo00o** [comment]
> I’m not entirely sure how you arrived at this state since variable font shouldn’t have separate weights exposed. Have you downloaded the variable version or static one on the customization form?

Just open folder C:\Windows\Fonts, double click monolisa variable font
the same result, two variable regular, static font no such error.
![image](https://github.com/MonoLisaFont/feedback/assets/12299238/9f05d2ab-c02c-4853-a518-85cfe33151cf)

**Comment by xqdoo00o** [comment]
Looks like version 2.009 has no such error, so 2.010 cause this error

**Comment by bebraw** [comment]
There was a name table related change in 2.010 (some Glyphs update) that may have caused this. Interestingly enough it's not visible on MacOS as all of the variable instances are visible there. It might be something specific to Windows.

**Comment by mekkablue** [comment]
I don’t understand. What exactly is the issue? Is the Black weight not showing up in the font menu? In which app? Does it persist after uninstalling, cleaning the caches, restarting, and reinstalling?

That the Windows 10 file system interface struggles with variable fonts, may be cosmetic or a caching issue. Most of the other weights are misrepresented as well in the screenshot.

Some Windows apps are known to exclusively use the info in the STAT table to build the menu, so the Regular may show up twice (once for its representation on the axes, once for style linking).

**Comment by mekkablue** [comment]
Hold on, after some digging, I indeed found a bug. Working on a fix.

**Comment by MarcusSterz** [comment]
This problem should solved with the upcoming version 2.011 – stay tuned!

**Comment by bebraw** [comment]
There's an initial prerelease available now. Could you download the prerelease version and check? Note that you have to select the following at the download to get it.

<img width="264" alt="Screenshot 2023-10-04 at 15 07 13" src="https://github.com/MonoLisaFont/feedback/assets/166921/0c2154b1-daa2-4507-869d-e5b104dd2871">

To verify you have the right version, it should register itself as 2.011 on your system (visible through a font metadata viewer).

**Comment by xqdoo00o** [comment]
> There's an initial prerelease available now. Could you download the prerelease version and check? Note that you have to select the following at the download to get it.
> 
> <img alt="Screenshot 2023-10-04 at 15 07 13" width="264" src="https://user-images.githubusercontent.com/166921/272567934-0c2154b1-daa2-4507-869d-e5b104dd2871.png">
> To verify you have the right version, it should register itself as 2.011 on your system (visible through a font metadata viewer).

It's now shows fine using prerelease version

**Comment by bebraw** [comment]
Included to newly released 2.011.
