### ISSUE TITLE
[Bug]: Why is it the same price for me to upgrade from Basic to Plus as it is to buy a brand new Plus version?

### ISSUE THREAD

**Issue by zihluwang** [MonoLisaFont/feedback#228]
### Edition

Basic (Personal)

### What version are you using?

2.010

### What type of weights are you using?

Default (non-customized)

### Operating system

macOS

### What happened?

I am planning to upgrade from basic edition to plus edition, but I found it is the almost the same price for me to upgrade. As you can see in the screenshots.

This is the price for me to **upgrade: JPY 17, 811**.
![Upgrade](https://github.com/MonoLisaFont/feedback/assets/47817169/54029cda-a079-424e-85e3-6d5e713d9476)

This is the price for me to **purchase a new one: JPY 17, 878**
![Purchase a new one](https://github.com/MonoLisaFont/feedback/assets/47817169/680c00fd-f9a9-492b-bd1f-9b3c080c0d03)

What is this ridiculous price?

**Comment by zihluwang** [comment]
And here is the price that displayed in the purchase page.

For upgrade:
![Upgrade](https://github.com/MonoLisaFont/feedback/assets/47817169/7ef5b342-730b-40af-ad02-426997c9ffb6)

For purchase a new one:
![Purchase a new one](https://github.com/MonoLisaFont/feedback/assets/47817169/b879f66c-96e2-4ea7-a332-0879c9126d12)

The selected region is China.

**Comment by bebraw** [comment]
I checked the code locally and it applied the discount fine within the same region (China). There might be some cross-region complexity due to different pricing kicking in.

I sent a discount code with the discount you expect to your email.

**Comment by zihluwang** [comment]
> I checked the code locally and it applied the discount fine within the same region (China). There might be some cross-region complexity due to different pricing kicking in.
> 
> 
> 
> I sent a discount code with the discount you expect to your email.

Sorry to disturb but it seems I lost that promotion code you sent to me, can you send that again?

**Comment by bebraw** [comment]
@zihluwang Ok, done.
