### ISSUE TITLE
[Feature request]: Could we please get an et ligature for ampersand?

### ISSUE THREAD

**Issue by jasonbraganza** [MonoLisaFont/feedback#229]
### What feature are you proposing?

I love the way et looks and prefer it over an ampersand. 
would love if there was a way that MonoLisa gave me the ability to have a ligated et (like 🙲 instead of & :)

**Comment by bebraw** [comment]
Reference: https://richmariner.wordpress.com/2015/02/18/why-an-is-called-an-ampersand/ .

We will investigate this one. If you know typefaces doing this well, do link.

**Comment by jasonbraganza** [comment]
I know of it, because the font I use and love most, other than my beloved Monolisa is Nitti:
https://fonts.adobe.com/fonts/nitti
I don’t know how to link to a sample there, so I’ve attached a screen shot.

I also love how Chiva does it.
Chiva Mono: https://fonts.google.com/specimen/Chivo+Mono?preview.text=Jane,%20Jill%20%26%20Mary&preview.text_type=custom&classification=Monospace


Other fonts that have it are below:

Fira Code: https://fonts.google.com/specimen/Fira+Code?preview.text=Jane,%20Jill%20%26%20Mary&preview.text_type=custom

Fira Mono: https://fonts.google.com/specimen/Fira+Mono?classification=Monospace&preview.text=Jane,%20Jill%20%26%20Mary&preview.text_type=custom

Space Mono: https://fonts.google.com/specimen/Space+Mono?preview.text=Jane,%20Jill%20%26%20Mary&preview.text_type=custom&classification=Monospace


![nitti-sample](https://github.com/MonoLisaFont/feedback/assets/4888781/ba684164-3113-42ef-a3d0-c07aa920950f)

**Comment by jasonbraganza** [comment]
oh, SF Mono (Apple) does it too

**Comment by jasonbraganza** [comment]
Sudo: https://coding-fonts.pages.dev/fonts/sudo/?language=charmap

**Comment by MarcusSterz** [comment]
Actually, the most common version of the ampersand `&` which MonoLisa also shows IS already a ligature of e and t. 
We will however experiment with an alternative that resembles more what you suggested.

**Comment by jasonbraganza** [comment]
oh yes, “&” is definitely et. i just prefer the older et and was requesting you folk if it would be possible for me to have that alternative :)

**Comment by jasonbraganza** [comment]
> oh yes, “&” is definitely et. i just prefer the older et and was requesting you folk if it would be possible for me to have that alternative :)

i love the et glyph :)

**Comment by MarcusSterz** [comment]
There will be a alternative for the ampersand available with the upcoming version 2.011 – stay tuned!

**Comment by bebraw** [comment]
Included to newly released 2.011.

**Comment by jasonbraganza** [comment]
Thank you very much! I really appreciate this. Loving my new glyph
