### ISSUE TITLE
Provide TTF files

### ISSUE THREAD

**Issue by alexeyten** [MonoLisaFont/feedback#23]
On Linux (Ubuntu) there is some issues with rendering otf files, or at least rendering differs from ttf.
So could you please provide ttf files?

**Comment by bebraw** [comment]
ttf is planned for the next release that will likely go out this week.

**Comment by bebraw** [comment]
@alexeyten ttf is included now. Please re-download the font using the original link in the Paddle email and let me know how it goes.

**Comment by alexeyten** [comment]
It's there, but it's 1.303 version.
```
$ otfccdump MonoLisa-Regular.ttf  | jq .head.fontRevision
1.3029937744140625

$ otfccdump MonoLisa-Regular.otf  | jq .head.fontRevision
1.399993896484375
```

**Comment by bebraw** [comment]
@alexeyten Thanks for the heads up. Looks like the release process picked up the older one. Now you should get the same version for both after downloading.

**Comment by alexeyten** [comment]
Works now. Thank you!

**Comment by bebraw** [comment]
Awesome. 👍
