### ISSUE TITLE
[Feature request]: A more curly brace

### ISSUE THREAD

**Issue by sonulohani** [MonoLisaFont/feedback#230]
### What feature are you proposing?

I really love this font. Its very readable. The only issue I have with this font is the curly brace which is somewhat flat. 
![image](https://github.com/MonoLisaFont/feedback/assets/2958681/7797a1d1-e0f9-407e-801e-4d3ba95e16a2)

I really like input mono curly brace
![image](https://github.com/MonoLisaFont/feedback/assets/2958681/4f1d3e30-1f9d-4bfa-9872-bec783058cdb)

This is from intel one mono
![image](https://github.com/MonoLisaFont/feedback/assets/2958681/5c04be53-7f72-47e7-b02f-fc4c3b7c2bae)

Is it possible to introduce one more variant of curly brace in this font. It would be very lovely to have this. 

Thanks

**Comment by bebraw** [comment]
We will experiment and most likely tweak ss07 to be more sharp. The issue is on our radar.

**Comment by MarcusSterz** [comment]
There will be a curlier bracket available with the upcoming version 2.011 – stay tuned!

**Comment by sonulohani** [comment]
> There will be a curlier bracket available with the upcoming version 2.011 – stay tuned!

Waiting eagerly. Is it available in pre-release?

**Comment by bebraw** [comment]
@sonulohani It's available in the prerelease, yes.

**Comment by sonulohani** [comment]
> @sonulohani It's available in the prerelease, yes.

I have downloaded prerelease and I see that its looking more beautiful and readable. Thanks.

**Comment by bebraw** [comment]
Included to newly released 2.011.
