### ISSUE TITLE
Alt At Sign (@) renders smaller than non-alt At 

### ISSUE THREAD

**Issue by carlomunguia** [MonoLisaFont/feedback#231]
### Edition

Plus

### What version are you using?

2.010 (newest stable) 

### What type of weights are you using?

Static (customized)

### Operating system

macOS

### Program

VS Code

### Display resolution

1920 x 1080

### What happened?

It seems that the alt At sign (@) renders smaller in size then the normal At sign, which makes it harder to use. 

At size 14 font on Vscode, on macOS Ventura current, on HD screen using 1920 x 1080, it’s noticeably harder to parse/view on screen. 

I’m filing this as a bug report, as I don’t think it’s technically an enhancement.

**Comment by bebraw** [comment]
Can you provide a visual example to illustrate the problem?

**Comment by carlomunguia** [comment]
Just saw this, will upload comparison photos ASAP.

**Comment by dantereve** [comment]
The baseline is clearly different. It makes it appear smaller than it really is I guess.

Screenshot on the latest 2.011 with a font size of 13 in VSCode. 

<img width="132" alt="Capture d’écran 2023-10-23 à 07 23 25" src="https://github.com/MonoLisaFont/feedback/assets/13101343/05bc399b-6547-47a5-acea-03b66cb0fa2f">
<img width="132" alt="Capture d’écran 2023-10-23 à 07 18 58" src="https://github.com/MonoLisaFont/feedback/assets/13101343/dde9246a-d946-4675-898c-40e6e78de699">

**Comment by carlomunguia** [comment]
<img width="70" alt="At" src="https://github.com/MonoLisaFont/feedback/assets/43321570/e494c04a-0d24-40c9-822a-07213f498139">
<img width="70" alt="Alt_At" src="https://github.com/MonoLisaFont/feedback/assets/43321570/c3dbb360-0dc9-42b4-b35e-b10ed073e9c6">

VSCode, Font Size 13, version 2.011. It's simply harder to parse a page of code with the Alt sign, despite it being desirable and usable.

**Comment by bebraw** [comment]
For reference, here's how Zeit Geist Mono is handling it:

<img width="1164" alt="Screenshot 2023-11-06 at 10 23 45" src="https://github.com/MonoLisaFont/feedback/assets/166921/1d0abb8b-9aca-4912-9e02-0dbe73dcf949">

It looks like they go slightly below baseline with the lowest part. I wonder if a good fix would be to nudge `@` up slightly so that the upper part matches with uppercase height (i.e., D in your example).

Source: https://vercel.com/font/mono .

**Comment by MarcusSterz** [comment]
Lifting up the alt `@` (ss06) to match the capital height in all masters. Will be available with the upcoming update.

**Comment by bebraw** [comment]
If you want to try, the upcoming fix is available in the prerelease version now.

**Comment by stevemolitor** [comment]
Lifting up the alt `@` helped. It looks pretty good to me now. However it's still a little busy for my taste. Here are three versions of the at sign:

MonoLisa Alt At Sign, Preview Release:
![](https://cdn.zappy.app/81d8dd28612fd7d77fa145e1964d26bf.png)

IBM Plex Mono At Sign:
![](https://cdn.zappy.app/016569575750a9e011fef0618a7e570f.png)

MonoLisa Default At Sign
![](https://cdn.zappy.app/623d99203a492f32629933ce2f722b1e.png)

Comparing the three, the default Monolisa `@` is the most legible and has the least amount of "ink" - it doesn't look busy compared to neighboring characters. However, it's also very distinctive - it may call too much attention to itself sometimes.

Both the IBM Plex and the MonoLisa Alt `@` look like a traditional at sign. The difference is subtle in these screen shots, but to me the IBM Plex is just a little bit less busy and easier to make out.

The ideal here for me would be an alt `@` sign that looks more traditional, but still has the MonoLisa flavor - _some_ personality is ok, and looks a little less busy, with less "ink".

I hope that makes sense.

**Comment by MarcusSterz** [comment]
@stevemolitor I agree with most of your analysis. The traditional `@` (our alt sign) hardly fits into the space we have, although we use 640 units instead of the usual 600. The ‘business’ as you call it is given by the structure of the `@` sign.

Look closely: IBM Plex does NOT use the traditional construction which is the reason it looks less crowded than our alt `@`.

**Comment by stevemolitor** [comment]
> Look closely: IBM Plex does NOT use the traditional construction 

@MarcusSterz You're right! At first glance, it looked "traditional enough" to me but I didn't look too closely.

I guess it depends on what the goal is with the alt at then. It does look pretty good now, although personally I'd prefer a compromise somewhere in between - traditional-ish, not _too_ busy. 

OTOH this alt at may be exactly what other folks are looking for. 

Tradeoffs!

**Comment by MarcusSterz** [comment]
@stevemolitor In the upcoming version (2.012) a secand alt verison will be included that resembles the Plex construction for those who prefer it.

**Comment by stevemolitor** [comment]
Oh that's cool thanks so much!

**Comment by bebraw** [comment]
The new alternate @ is behind `ss18` in the latest prerelease to test if you want to try before stable.

**Comment by carlomunguia** [comment]
While I think both lifting up the first alt & having a 2nd alt is great (they both help) , I personally don't feel the IBM Plex @ fits into the vibe of Monolisa. 

Personally, I would take inspiration from Sudo:

![image](https://github.com/MonoLisaFont/feedback/assets/43321570/123e88f8-18b3-433c-b54b-34e0f882a54e)

or Mononoki: 

![image](https://github.com/MonoLisaFont/feedback/assets/43321570/49c0b58b-ff86-4a14-a761-1f39d8b5b96a)

Both of those example @'s use their respective space well & don't intrude with the flow of each line & are easy to parse. 

Just my two cents, perhaps we can even do a 3rd alt & pick one of the above (that suits the team)?

**Comment by stevemolitor** [comment]
I don't have an easy way to test ss18 on the preview because I can't select OpenType features in my editor (Emacs). I just bake it in on download. 

I do appreciate the work here and am looking forward to trying it out!

**Comment by bebraw** [comment]
Included in 2.012.

**Comment by bebraw** [comment]
Fixed in 2.012.
