### ISSUE TITLE
[Bug]: Font Scaling Issue 

### ISSUE THREAD

**Issue by stevemolitor** [MonoLisaFont/feedback#234]
### Edition

Plus

### What version are you using?

2.010

### What type of weights are you using?

Default (non-customized)

### Operating system

MacOS Sonoma 14.0

### Program

iTerm 2, Emacs

### Display resolution

3456x2234 

### What happened?

In iTerm 2 and Emacs, when I increase the font size from 15 to 16, the font gets taller but not wider. Other increments work as expected - both the font height and width change as I change the font size.

Here are my iTerm 2 font settings:

![](https://cdn.zappy.app/e5e28f8228012e0f527390f46ece940d.png)

In the gif below, I use the `Command +` and `Command -` keys to increase my font size from 14, 15, 16, 17 and then back down - 17, 16, 15, 14. You'll notice that when I change between 15 and 16 (the 2nd and 3rd largest font sizes in the gif), the font height increases but not the width. Size 15 looks a little odd to me also:

![](https://cdn.zappy.app/f014ffd7bb6a32562bd52b1f733ba9cb.gif)

The same thing happens if I manually change the font size to size 15, open a new iTerm 2 window, change the size to 16, and open a new window. Sizes 15 and 16 have the same width but different heights.

I've noticed the same thing in Emacs. These are the only two apps I've tried.

Other increments work fine, just not 15 -> 16.

**Comment by bebraw** [comment]
@MarcusSterz Do you think something could be done about this? I wonder if it's actually an upstream issue and something for iTerm 2 to fix esp. if the same occurs with other fonts.

**Comment by MarcusSterz** [comment]
@bebraw Weird. There is hardly I can do anything about it from my side, I will investigate never the less. I suspect some of the preferences in iTerm or iTerm itself are responsible.

**Comment by bebraw** [comment]
@stevemolitor Can you see the issue with other fonts (Fira Code etc.)? If yes, I would say it's an upstream issue and something we cannot fix.

**Comment by stevemolitor** [comment]
@bebraw I do see it in other fonts. I thought I didn't, but it seems it can happen at different font sizes depending on the font. I tried a bunch of different monosapace fonts (Fira, IBM Flex, Input One, Menlo, and others...) and it happened with all of them at certain sizes.

I see it in iTerm 2, the built-in terminal app, emacs, basically all the apps I used that use monospace fonts. So it might be a MacOS font scaling thing. I tried with antialiasing on and off; same result.

So anyway I agree, it sounds like an upstream issue and not something you can fix. Thanks again for the responses.

**Comment by bebraw** [comment]
Ok, thanks for confirming. You could re-open the issue at iTerm 2 to get their input. In the worst case it's MacOS font scaling, yeah, in case you cannot see the same behavior in other terminals.

**Comment by stevemolitor** [comment]
Thanks again.

I see it in the built in MacOS terminal app and Emacs in MacOS as well, so I think it’s a MacOS thing.
