### ISSUE TITLE
[Feature request]: Annoyingly nitpicky request: cursive `s` slight overshoot so it's less tiny?

### ISSUE THREAD

**Issue by martinemde** [MonoLisaFont/feedback#237]
### What feature are you proposing?

Hey, I'm being really nitpicky here. Sorry in advance.

I'm trying out the cursive for the first time and the visual height of the cursive `s` is throwing me off.

Because the MonoLisa `s` has a narrow top, it looks visually tiny in a line of text. I tried to give an example here from code I'm working on. The `unless` at the bottom is especially notable because the word visually trails off near the end.

<img width="130" alt="Screenshot 2023-10-19 at 5 54 30 PM" src="https://github.com/MonoLisaFont/feedback/assets/989/5b27c03f-fb5e-458d-8102-25f5897a2ecf">

Here's an example image where a similar cursive s overshoots the meanline:

![image](https://github.com/MonoLisaFont/feedback/assets/989/d8cc8d6e-16d9-460d-a8de-a417b4fa7867)

It would seem warranted to overshoot the height a little to compensate for its pointy top.

I'm not trying to tell you how to do your job though, so I'll shut up now and never speak of this again unless asked.

Thanks for a great font! Been using it for a year in trial mode and just purchased it!

**Comment by MarcusSterz** [comment]
Hi Martin, thank you for interest in MonoLisa. As you can see in the screenshot, the script `s` overshoots already the x-height and the baseline. We might talk about it though and adjust that detail in the future :)
 
<img width="945" alt="grafik" src="https://github.com/MonoLisaFont/feedback/assets/51958720/948e6067-8665-4011-bf4e-bce47db2224b">

**Comment by martinemde** [comment]
I appreciate the reply, Marcus. As a font nerd myself, I'm happy to have such a great font to use daily. Thank you!
