### ISSUE TITLE
Windows rendering (ttf 1.400)

### ISSUE THREAD

**Issue by Eldair** [MonoLisaFont/feedback#24]
After testing the latest ttf version on windows, this is still the same

14px (!= is the only issue unless it should be small like this):
![image](https://user-images.githubusercontent.com/470003/80471905-58463900-8944-11ea-9617-11a84bbb8b11.png)
13px:
![image](https://user-images.githubusercontent.com/470003/80471979-701dbd00-8944-11ea-9304-170d7cba1f45.png)
12px:
![image](https://user-images.githubusercontent.com/470003/80472025-7dd34280-8944-11ea-8b7b-5a23e82a1c95.png)
15px:
![image](https://user-images.githubusercontent.com/470003/80472068-86c41400-8944-11ea-9696-047070e3c51b.png)

**Comment by okonet** [comment]
Is this still an issue? I see your comment in https://github.com/MonoLisaFont/feedback/issues/19 and not sure now if we should be investigating it still.

**Comment by Eldair** [comment]
Hi, yeah, it is still the same, on version 1.5

**Comment by bebraw** [comment]
@Eldair Which resolution are you using on your display? That's a good extra piece of information to have.

**Comment by Eldair** [comment]
Same thing on both 1920x1080 (24") and 2560x1440 (27")

**Comment by bebraw** [comment]
Ok, thanks!

Is it the same regardless of the editor (VS Code and others)?

**Comment by Eldair** [comment]
Sublime is the same but for different font size (their 10 is the same as vscode 14)

![image](https://user-images.githubusercontent.com/470003/88083114-f122d400-cb82-11ea-8468-79c71de63dbe.png)
![image](https://user-images.githubusercontent.com/470003/88083142-f7b14b80-cb82-11ea-8bda-2f2e1e59b30f.png)
![image](https://user-images.githubusercontent.com/470003/88083164-ff70f000-cb82-11ea-8963-cedaeb32b8ef.png)
![image](https://user-images.githubusercontent.com/470003/88083199-0c8ddf00-cb83-11ea-9c5e-079eb78568d7.png)

These screenshots are from the larger display (1440p)
If you need more font sizes let me know

**Comment by bebraw** [comment]
Can you check with 1.6 as there were ttf rendering improvements there? You can use the original download link.

**Comment by Eldair** [comment]
Hello,

13px and 14px are perfect on both 1440p (27") and 1080p (23")

12px
![image](https://user-images.githubusercontent.com/470003/100441062-23e75680-30a6-11eb-9d89-b4566b7b570f.png)
11px and below have an issue with .= only
![image](https://user-images.githubusercontent.com/470003/100441102-33ff3600-30a6-11eb-8ad2-2abcb441ab72.png)
15px
![image](https://user-images.githubusercontent.com/470003/100441145-48433300-30a6-11eb-9b19-bf228cbea5cb.png)
16px and above is same as 11 and below .=
![image](https://user-images.githubusercontent.com/470003/100441179-52fdc800-30a6-11eb-952b-0fb9c41dd489.png)

**Comment by bebraw** [comment]
@MarcusSterz Can you comment when you have time? TTF looks better now and I guess the question is, can the rest be improved?

I know there are inherent limitations in font rendering so the problem often is that you cannot make each size perfect especially on lower resolutions. Based on that it's possible we won't be able to make it perfect on each but let's see what Marcus has to say.

**Comment by MarcusSterz** [comment]
I will pass the torch to @mekkablue – Is there a final answer to this?

**Comment by mekkablue** [comment]
Will employ ‘natural’ rather than ‘quantized’ gridfitting, which will deliver a smoother scaling across sizes at the cost of a bit more antialiasing (i.e., a bit more fuzziness). This should be a slight improvement.

However it is not mathematically possible to always gridfit three equally distant stems at equal pixel distances in _all_ pixel sizes, and line them up with the rest of the font at the same time. There will have to be some compromise in some pixel sizes.

**Comment by bebraw** [comment]
The fix has been included to the newly published 1.700.
