### ISSUE TITLE
[Feature request]: Consistent ligatures for alternate symbols `&` and `$`

### ISSUE THREAD

**Issue by gixim** [MonoLisaFont/feedback#240]
### What feature are you proposing?

Hello,

I have recently upgraded to Plus and really like the features.

I noticed that alternate `&` and `$` (ss13, ss14 respectively) go back to normal when they are a part of a ligature like `&&`, `<$>`, etc.

It would be great if those ligatures also supported alternate symbol shapes.
Especially, `&&` is often used for logical and operator in C-like languages.

![2023-11-06_monolisa-ss13-ss14](https://github.com/MonoLisaFont/feedback/assets/83961834/213e9a62-b6ba-400e-abcc-c39950542285)

Thank you.

**Comment by MarcusSterz** [comment]
@gixim You are absolutely right. We will include this in the next update asap.

**Comment by bebraw** [comment]
Included in 2.012.

**Comment by gixim** [comment]
Thank you for adding. New ligatures are wonderful! :tada:
