### ISSUE TITLE
[Bug]: C++ Scope resolution(::) ligature in italics is wrong

### ISSUE THREAD

**Issue by sonulohani** [MonoLisaFont/feedback#241]
### Edition

Plus

### What version are you using?

2.011

### What type of weights are you using?

Default (non-customized)

### Operating system

Linux mint 20.3

### Program

VS Code

### Display resolution

1920x1080

### What happened?

![image](https://github.com/MonoLisaFont/feedback/assets/2958681/e39f5be6-519e-4dba-a507-4aa6a9590aa7)

**Comment by MarcusSterz** [comment]
@sonulohani That’s a path compatibility problem between masters. Thanks for finding it – will be solved in next version.

**Comment by bebraw** [comment]
If you want to try, the upcoming fix is available in the prerelease version now.

**Comment by bebraw** [comment]
Fixed in 2.012.
