### ISSUE TITLE
[Feature request]: Consistent curly brace + vertical pipe ligature compared to non-ligature.

### ISSUE THREAD

**Issue by martinemde** [MonoLisaFont/feedback#242]
### What feature are you proposing?

In Ruby, this is very common and doesn't look great:

<img width="314" alt="Screenshot 2023-11-17 at 12 34 38 PM" src="https://github.com/MonoLisaFont/feedback/assets/989/bb5af89d-02ab-430d-a492-0220009005b2">

Compared with ligatures turned off.

<img width="191" alt="Screenshot 2023-11-17 at 12 35 43 PM" src="https://github.com/MonoLisaFont/feedback/assets/989/7842ba0a-efa9-4721-80bf-f96c2e6a8616">

Neither are pretty. Any ideas?

**Comment by bebraw** [comment]
It might be worth checking how Fira Code and others solve it to come up with a solution.

Somehow the ligature seems off when compared with }.

**Comment by okonet** [comment]
We should align the `|` and make it taller. Let's discuss internally.

**Comment by martinemde** [comment]
Fira Code, for reference (with ligatures enabled):

<img width="130" alt="Screenshot 2023-11-17 at 1 25 47 PM" src="https://github.com/MonoLisaFont/feedback/assets/989/23096189-38ed-4a8f-94f1-351f364a1500">

**Comment by MarcusSterz** [comment]
Yes, let's align the bar to match the brackets. We can make the traditional bar position a stylistic set if needed.

**Comment by martinemde** [comment]
I downloaded the preview and it looks great.

**Comment by bebraw** [comment]
Fixed in 2.012.
