### ISSUE TITLE
[Feature request]: Support Japanese language

### ISSUE THREAD

**Issue by ktym4a** [MonoLisaFont/feedback#243]
Hi team,

Thank you for the great font ever.
I think It would be great if this font supports Japanese.

Thanks!

**Comment by bebraw** [comment]
Do you have a list of glyphs that would have to be supported?

**Comment by ktym4a** [comment]
@bebraw 
I don't have that, Sorry.

I Just wanted to know if plan to support Japanese or not in the future.

**Comment by bebraw** [comment]
@ktym4a Based on my understanding it is not likely especially if there are hundreds of glyphs to add. A good compromise might be to use another font as a fallback for those as some environments allow for it.

**Comment by ktym4a** [comment]
@bebraw Okay, I understand! Thanks for your kind support.
