### ISSUE TITLE
[Feature request]: Add ability to notify users of new releases

### ISSUE THREAD

**Issue by mikesmithgh** [MonoLisaFont/feedback#244]
### What feature are you proposing?

Provide a way to be notified of new releases.

My typical workflow for MonoLisa is to randomly check my orders after a period of time to see if a new version is available.

I think it would be nice to get notified via email or another mechanism. I was hoping I could come to Github and subscribe to releases but that doesn't seem like an option since the repo is private.

Thanks!

**Comment by bebraw** [comment]
Can you subscribe to RSS? http://monolisa.dev/api/rss

X is another option: https://twitter.com/monolisafont

We also send a notification on release to those that gave a permission to Paddle during purchasing flow.

Would any of these work for you?

**Comment by bebraw** [comment]
I added a signup form for the mailing list: https://monolisa.ipzmarketing.com/f/IC7-jCQB2gU . I hope this work for you!

**Comment by okonet** [comment]
We send emails to folks who allowed us to contact them during the purchase process.

**Comment by bebraw** [comment]
I'll close this as now there are multiple ways to subscribe for updates.

**Comment by mikesmithgh** [comment]
> I added a signup form for the mailing list: https://monolisa.ipzmarketing.com/f/IC7-jCQB2gU . I hope this work for you!

Perfect! I just subscribed. I have a habit of not subscribing to any mailing list when purchasing, so that is why I missed that. Also, didn't realize the RSS feed 👍. Thanks!
