### ISSUE TITLE
[Feature request]: Add another font weight - SemiMedium (450)

### ISSUE THREAD

**Issue by xshapira** [MonoLisaFont/feedback#247]
### What feature are you proposing?

It would be nice to have a font weight that is a cross between Regular (400) and Medium (500) as often Medium appears too bold.

**Comment by sonulohani** [comment]
I agree, 450 would have been the perfect medium variant weight.

**Comment by bebraw** [comment]
We had a brief discussion about the topic. More specific weights like 450 are best served by the Complete plan as it was designed for the purpose so one option would be upgrading in case you want more flexibility.
