### ISSUE TITLE
slashed zero

### ISSUE THREAD

**Issue by yalelo** [MonoLisaFont/feedback#25]
Hi,

It would be great to have a slashed zero glyph.
Personally, I like slashed zeros more and would have make it the default but that's a personal taste. I would be happy if there is a stylistic alternate too.

Thanks

**Comment by okonet** [comment]
We will introduce stylistic sets. Related to https://github.com/MonoLisaFont/website/issues/359

**Comment by alexeyten** [comment]
Looks like slashed zero was added as `ss02`.
May I suggest to use `zero` as it is exactly what it should be
https://docs.microsoft.com/en-us/typography/opentype/spec/features_uz#tag-zero
> Function: [...] This feature allows the user to change from the default 0 to a slashed form.

![image](https://user-images.githubusercontent.com/44377/95583832-65b03500-0a45-11eb-8ae6-9c86e96487f7.png)

**Comment by bebraw** [comment]
@alexeyten Hi, it's not officially released yet (not in docs yet) but it's a great idea to use `zero` for its name (cc @MarcusSterz).

**Comment by okonet** [comment]
Yes, we agreed it should be `zero` so I'm confused why it's in `ss02` now.

**Comment by bebraw** [comment]
The current release doesn't have the new naming yet.

**Comment by bebraw** [comment]
This has been implemented in 1.6 (please use the original download link). Closing.

More info on usage at https://www.monolisa.dev/releases . You'll have to enable `zero` explicitly in your editor.
