### ISSUE TITLE
[Bug]:  Regular looking Bold in VS Code MacOS

### ISSUE THREAD

**Issue by santigarcor** [MonoLisaFont/feedback#255]
### Edition

Basic (Personal)

### What version are you using?

2.012

### What type of weights are you using?

Default (non-customized)

### Operating system

Mac OS Sonoma 14.3

### Program

VScode

### Display resolution

1920x1080

### What happened?

I just moved from a linux laptop to a macbook pro. I'm using the same display, an LG FHD, but for some reason the font looks like if it were bold, but i'm using the regular font:
This is how it looks on linux:
![image](https://github.com/MonoLisaFont/feedback/assets/7565417/e4390b9f-efe6-4cca-864c-6c105708461e)

And this is how it looks on Mac OS:
![image](https://github.com/MonoLisaFont/feedback/assets/7565417/8af41b5d-e522-46c3-a88f-86e81a2d3b3e)

I didn't have this issue in linux

**Comment by okonet** [comment]
Font rendering algorithms are very different on every OS. On a Mac there are some know issues related to font smoothing making fonts look bolder. 

Check this out: https://apple.stackexchange.com/questions/442167/how-to-fix-blurry-fonts-on-external-monitor-m1-mac-mini

This is a great article on the matter too: https://tonsky.me/blog/monitors/

I would try increasing the font size a be it and experimenting with those hidden settings on Mac.

**Comment by sonulohani** [comment]
> Font rendering algorithms are very different on every OS. On a Mac there are some know issues related to font smoothing making fonts look bolder.
> 
> Check this out: https://apple.stackexchange.com/questions/442167/how-to-fix-blurry-fonts-on-external-monitor-m1-mac-mini
> 
> This is a great article on the matter too: https://tonsky.me/blog/monitors/
> 
> I would try increasing the font size a be it and experimenting with those hidden settings on Mac.

Maybe this can go in FAQ in website

**Comment by okonet** [comment]
Did it help you mitigate the issue? If yes, what part specifically?

**Comment by santigarcor** [comment]
In my case disabling font soothing together with better display made it more bearable, but in the end I bought a 4k monitor but still without font smoothing
