### ISSUE TITLE
[Feature request]: Ligature for JavaScript's unsigned right shift assignment operator (>>>=)

### ISSUE THREAD

**Issue by ghost** [MonoLisaFont/feedback#256]
### What feature are you proposing?

JavaScript features an unsigned right shift assignment operator: `>>>=` 

A ligature for this operator would be a nice addition. Currently, it appears as a combination of the `greater` symbol and the `greater_greater_equal` symbol:

![image](https://github.com/MonoLisaFont/feedback/assets/9667667/29ac7793-ca34-4599-a5ad-3fe7e317f07d)

**Comment by bebraw** [comment]
Included in 2.013.
