### ISSUE TITLE
[Bug]: istroke is not implemented for ss15 although it belongs to it

### ISSUE THREAD

**Issue by bebraw** [MonoLisaFont/feedback#257]
### Edition

Basic (Personal)

### What version are you using?

2.012

### What type of weights are you using?

Default (non-customized)

### Operating system

MacOS

### What happened?

Screenshot without ss15 applied:

<img width="240" alt="Screenshot 2024-02-17 at 9 06 10" src="https://github.com/MonoLisaFont/feedback/assets/166921/ba681b79-b9ee-4570-9e41-1971f75df495">

Screenshot with ss15 applied:

<img width="221" alt="Screenshot 2024-02-17 at 9 06 44" src="https://github.com/MonoLisaFont/feedback/assets/166921/53403ea2-e19f-4261-8ba5-6e27243e3b1a">

It looks like applying `ss15` does nothinig on `istroke` so either it's not categorized correctly or it's missing an implementation. The same issue is visible for both normal and italic versions.

**Comment by MarcusSterz** [comment]
It’s all there.

<img width="180" alt="Bildschirmfoto 2024-02-22 um 11 42 42" src="https://github.com/MonoLisaFont/feedback/assets/51958720/c3fdc6af-9dde-4c91-bd47-abfa91d08629">
<img width="282" alt="Bildschirmfoto 2024-02-22 um 11 43 52" src="https://github.com/MonoLisaFont/feedback/assets/51958720/89285d64-6877-46e0-89db-c1a72c1b1eb0">

**Comment by MarcusSterz** [comment]
This is connected to #258
