### ISSUE TITLE
[Bug]: rfishhook is not implemented for ss16 although it belongs there

### ISSUE THREAD

**Issue by bebraw** [MonoLisaFont/feedback#258]
### Edition

Basic (Personal)

### What version are you using?

2.012

### What type of weights are you using?

Default (non-customized)

### Operating system

MacOS

### What happened?

This is the same as #257 but for rfishhook. The same behavior is visible for both normal and italic.

<img width="226" alt="Screenshot 2024-02-17 at 9 09 29" src="https://github.com/MonoLisaFont/feedback/assets/166921/c1316882-0e88-4ba2-8f6c-8e2804f5ffa2">

**Comment by MarcusSterz** [comment]
We do have both. What your screensht shows is the `ss16` version.

<img width="229" alt="Bildschirmfoto 2024-02-22 um 11 41 04" src="https://github.com/MonoLisaFont/feedback/assets/51958720/dccd2524-6783-4a35-9f3b-a391af7a71d3">

**Comment by MarcusSterz** [comment]
Actually I see a lot of letters displayed the wrong way... these are fallback versions.
This is a website bug, not a font bug.

<img width="2528" alt="Bildschirmfoto 2024-02-22 um 11 46 33" src="https://github.com/MonoLisaFont/feedback/assets/51958720/64ba6fa8-efab-411e-b98f-2ce88bf4a7bf">
