### ISSUE TITLE
[Bug]: EM dash glyph is inconsistent with hypen and EN dash

### ISSUE THREAD

**Issue by galdor** [MonoLisaFont/feedback#260]
### Edition

Plus

### What version are you using?

2.012

### What type of weights are you using?

Default (non-customized)

### Operating system

Linux

### Program

Emacs

### Display resolution

3840x2160

### What happened?

The EM dash glyph is inconsistent with the glyphs of the minus character and the EN dash character: it is thinner and not vertically aligned.

![monolisa-em-dash](https://github.com/MonoLisaFont/feedback/assets/37804/392255c9-84af-4c62-9463-216ce9a07e0a)

![monolisa-em-dash-2](https://github.com/MonoLisaFont/feedback/assets/37804/f2b9ab83-2e9a-42da-8b2f-d028dd2588cf)

I would expect the thickness to be identical and all three glyphes to be vertically aligned: the only difference should be the length of the stroke.

**Comment by MarcusSterz** [comment]
Tradionally `minus`, `endash` and `emdash` do not share the same thickness. Especially the emdash is usually drawn as a quite thin line. However we strongly consider to bring it into line with the others.

**Comment by galdor** [comment]
Interesting, I did not know that. I imagine having both thicknesses as alternate glyphes would satisfy everyone. Is vertical misalignment considered normal too?

**Comment by MarcusSterz** [comment]
It is not a misalignment. When you have 3 lines and one is a lot thinner, where do you align it to? The upper, the middle or the lower line? I chose the latter. But as I wrote we will change this to make it more screen-friendly.

**Comment by galdor** [comment]
As I said in my original post, I would expect the middle, but I understand there might be reasons to do otherwise. I'm no typography expert :)

**Comment by MarcusSterz** [comment]
You find them modified with the next update :)

**Comment by bebraw** [comment]
Included in 2.013.

**Comment by galdor** [comment]
They are just perfect in the last stable version, thank you!
