### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Devlevel9000** [MonoLisaFont/feedback#261]
### Edition

Plus

### What version are you using?

2.012

### What type of weights are you using?

Default (non-customized)

### Operating system

Windows 11

### Program

Any

### What happened?

Trying to patch font with nerd fonts and both original nerd fonts and daylinmorgan's patcher show the following output:
> Nerd Fonts Patcher v3.1.1 (4.8.4) (ff 20230101)
Done with Patch Sets, generating font...
The following table(s) in the font have been ignored by FontForge
  Ignoring 'STAT' style attributes table
The following table(s) in the font have been ignored by FontForge
  Ignoring 'EPAR'
The glyph named asterisk is mapped to U+F069.
  But its name indicates it should be mapped to U+002A.
The glyph named plus is mapped to U+F067.
  But its name indicates it should be mapped to U+002B.
The glyph named question is mapped to U+F128.
  But its name indicates it should be mapped to U+003F.
The glyph named minus is mapped to U+F068.
  But its name indicates it should be mapped to U+2212.
The glyph named heart is mapped to U+F004.
  But its name indicates it should be mapped to U+2665.
The glyph named home is mapped to U+F015.
  But its name indicates it should be mapped to U+21B8.
The glyph named check is mapped to U+F046.
  But its name indicates it should be mapped to U+2713.
The glyph named bell is mapped to U+F0A2.
  But its name indicates it should be mapped to U+2407.
The glyph named lessequal is mapped to U+F500.
  But its name indicates it should be mapped to U+2264.
The glyph named circle is mapped to U+F111.
  But its name indicates it should be mapped to U+25CB.
The glyph named smile is mapped to U+F118.
  But its name indicates it should be mapped to U+263A.
The glyph named frown is mapped to U+F119.
  But its name indicates it should be mapped to U+2322.
The glyph named bullseye is mapped to U+F140.
  But its name indicates it should be mapped to U+25CE.
The glyph named compass is mapped to U+F14E.
  But its name indicates it should be mapped to U+263C.
The glyph named female is mapped to U+F182.
  But its name indicates it should be mapped to U+2640.
The glyph named male is mapped to U+F183.
  But its name indicates it should be mapped to U+2642.
The glyph named sun is mapped to U+F185.
  But its name indicates it should be mapped to U+263C.
The glyph named venus is mapped to U+F221.
  But its name indicates it should be mapped to U+2640.
The glyph named slash is mapped to U+E016.
  But its name indicates it should be mapped to U+002F.
The glyph named pi is mapped to U+E02C.
  But its name indicates it should be mapped to U+03C0.
The glyph named ring is mapped to U+E03D.
  But its name indicates it should be mapped to U+02DA.
The glyph named infinity is mapped to U+E055.
  But its name indicates it should be mapped to U+221E.
The glyph named equal is mapped to U+E079.
  But its name indicates it should be mapped to U+003D.
The glyph named alpha is mapped to U+F002B.
  But its name indicates it should be mapped to U+03B1.
The glyph named at is mapped to U+F0065.
  But its name indicates it should be mapped to U+0040.
The glyph named backspace is mapped to U+F006E.
  But its name indicates it should be mapped to U+2408.
The glyph named bell is mapped to U+F009A.
  But its name indicates it should be mapped to U+2407.
The glyph named beta is mapped to U+F00A1.
  But its name indicates it should be mapped to U+03B2.
The glyph named box is mapped to U+F00D4.
  But its name indicates it should be mapped to U+25A1.
The glyph named check is mapped to U+F012C.
  But its name indicates it should be mapped to U+2713.
The glyph named compass is mapped to U+F018B.
  But its name indicates it should be mapped to U+263C.
The glyph named delete is mapped to U+F01B4.
  But its name indicates it should be mapped to U+2421.
The glyph named delta is mapped to U+F01C2.
  But its name indicates it should be mapped to U+03B4.
The glyph named earth is mapped to U+F01E7.
  But its name indicates it should be mapped to U+2641.
The glyph named equal is mapped to U+F01FC.
  But its name indicates it should be mapped to U+003D.
The glyph named heart is mapped to U+F02D1.
  But its name indicates it should be mapped to U+2665.
The glyph named home is mapped to U+F02DC.
  But its name indicates it should be mapped to U+21B8.
The glyph named image is mapped to U+F02E9.
  But its name indicates it should be mapped to U+22B7.
The glyph named minus is mapped to U+F0374.
  But its name indicates it should be mapped to U+2212.
The glyph named omega is mapped to U+F03C9.
  But its name indicates it should be mapped to U+03C9.
The glyph named percent is mapped to U+F03F0.
  But its name indicates it should be mapped to U+0025.
The glyph named pi is mapped to U+F03FF.
  But its name indicates it should be mapped to U+03C0.
The glyph named plus is mapped to U+F0415.
  But its name indicates it should be mapped to U+002B.
The glyph named sigma is mapped to U+F04A0.
  But its name indicates it should be mapped to U+03C3.
The glyph named tie is mapped to U+F0519.
  But its name indicates it should be mapped to U+2040.
The glyph named triangle is mapped to U+F0536.
  But its name indicates it should be mapped to U+25B3.
The glyph named bullseye is mapped to U+F05DD.
  But its name indicates it should be mapped to U+25CE.
The glyph named copyright is mapped to U+F05E6.
  But its name indicates it should be mapped to U+00A9.
The glyph named lambda is mapped to U+F0627.
  But its name indicates it should be mapped to U+03BB.
The glyph named asterisk is mapped to U+F06C4.
  But its name indicates it should be mapped to U+002A.
The glyph named hook is mapped to U+F06E2.
  But its name indicates it should be mapped to U+2440.
The glyph named infinity is mapped to U+F06E4.
  But its name indicates it should be mapped to U+221E.
The glyph named prescription is mapped to U+F0706.
  But its name indicates it should be mapped to U+211E.
The glyph named tilde is mapped to U+F0725.
  But its name indicates it should be mapped to U+02DC.
The glyph named cancel is mapped to U+F073A.
  But its name indicates it should be mapped to U+2418.
The glyph named square is mapped to U+F0764.
  But its name indicates it should be mapped to U+25A1.
The glyph named null is mapped to U+F07E2.
  But its name indicates it should be mapped to U+2400.
The glyph named pipe is mapped to U+F07E5.
  But its name indicates it should be mapped to U+01C0.
The glyph named ring is mapped to U+F07EB.
  But its name indicates it should be mapped to U+02DA.
The glyph named cross is mapped to U+F0953.
  But its name indicates it should be mapped to U+2629.
The glyph named trademark is mapped to U+F0A78.
  But its name indicates it should be mapped to U+2122.
The glyph named ampersand is mapped to U+F0A8D.
  But its name indicates it should be mapped to U+0026.
The glyph named diamond is mapped to U+F0B8A.
  But its name indicates it should be mapped to U+2666.
The glyph named bullet is mapped to U+F0CF3.
  But its name indicates it should be mapped to U+2022.
The glyph named comma is mapped to U+F0E23.
  But its name indicates it should be mapped to U+002C.
The glyph named rectangle is mapped to U+F0E5E.
  But its name indicates it should be mapped to U+25AD.
The glyph named spade is mapped to U+F0E65.
  But its name indicates it should be mapped to U+2660.
The glyph named epsilon is mapped to U+F10E0.
  But its name indicates it should be mapped to U+03B5.
The glyph named gamma is mapped to U+F10EE.
  But its name indicates it should be mapped to U+03B3.
The following table(s) in the font have been ignored by FontForge
  Ignoring 'webf'
The glyph named question is mapped to U+F02C.
  But its name indicates it should be mapped to U+003F.
The glyph named check is mapped to U+F03A.
  But its name indicates it should be mapped to U+2713.
The glyph named plus is mapped to U+F05D.
  But its name indicates it should be mapped to U+002B.
The glyph named x is mapped to U+F081.
  But its name indicates it should be mapped to U+0078.
The glyph named home is mapped to U+F08D.
  But its name indicates it should be mapped to U+21B8.
The glyph named ellipsis is mapped to U+F09A.
  But its name indicates it should be mapped to U+2026.
The glyph named bell is mapped to U+F0DE.
  But its name indicates it should be mapped to U+2407.
The glyph named circle is mapped to U+F27D.
  But its name indicates it should be mapped to U+25CB.
The glyph named diamond is mapped to U+F292.
  But its name indicates it should be mapped to U+2666.
The glyph named image is mapped to U+F2B8.
  But its name indicates it should be mapped to U+22B7.
The Traceback (most recent call last):
  File "C:\Users\<MyUser>\Tools\nerd-fonts\font-patcher", line 2087, in <module>
    main()
  File "C:\Users\<MyUser>\Tools\nerd-fonts\font-patcher", line 2079, in main
    patcher.generate(sourceFonts)
  File "C:\Users\<MyUser>\Tools\nerd-fonts\font-patcher", line 446, in generate
    sourceFont.generate(outfile, bitmap_type=bitmaps, flags=gen_flags)
OSError: Font generation failed
glyph named infinity is mapped to U+F2B9.
  But its name indicates it should be mapped to U+221E.
The glyph named square is mapped to U+F2F0.
  But its name indicates it should be mapped to U+25A1.
The glyph named sun is mapped to U+F2F5.
  But its name indicates it should be mapped to U+263C.
The glyph named bell is mapped to U+EAA2.
  But its name indicates it should be mapped to U+2407.
The glyph named check is mapped to U+EAB2.
  But its name indicates it should be mapped to U+2713.
The glyph named compass is mapped to U+EBD5.
  But its name indicates it should be mapped to U+263C.
The glyph named ellipsis is mapped to U+EA7C.
  But its name indicates it should be mapped to U+2026.
The glyph named heart is mapped to U+EB05.
  But its name indicates it should be mapped to U+2665.
The glyph named home is mapped to U+EB06.
  But its name indicates it should be mapped to U+21B8.
The glyph named newline is mapped to U+EBEA.
  But its name indicates it should be mapped to U+2424.
The glyph named question is mapped to U+EB32.
  But its name indicates it should be mapped to U+003F.
Save Failed
Patcher run aborted!

Is there a way to get past this? 

I've tried updating Windows locale to UTF-8 but based on [this question](https://github.com/daylinmorgan/monolisa-nerdfont-patch/issues/7#issuecomment-1979296878) I get this output:
>python -c 'import locale; print(locale.getpreferredencoding())'
cp65001

Much appreciate any help patching Monolisa with the nerd icons for my neovim setup.

**Comment by bebraw** [comment]
I tried this under MacOS with 2.012 Plus and it patched perfectly. That implies it might be an upstream issue in the patching tool itself or perhaps something Windows related.

Instead of running directly under Windows, you could run it within a Docker container as they seem to have support for that.

Another direction I would investigate is skipping patching altogether and using a fallback font for Nerd Fonts instead as instructed at https://github.com/ryanoasis/nerd-fonts/wiki/Font-Substitution-&-Fallback .

**Comment by bebraw** [comment]
As mentioned, for Windows the fallback option discussed at https://github.com/ryanoasis/nerd-fonts/wiki/Font-Substitution-&-Fallback seems like the best option.

You could also keep an eye on #57.
