### ISSUE TITLE
[Feature request]: Zed editor support

### ISSUE THREAD

**Issue by ahyield** [MonoLisaFont/feedback#263]
### What feature are you proposing?

It would be awesome if the font is supported in Zed editor same like VS code :(

**Comment by bebraw** [comment]
It seems they support OpenType features. See https://zed.dev/docs/configuring-zed for more info.

For anything missing on the editor side, I would suggest opening an issue at their issue tracker: https://github.com/zed-industries/zed/issues .

**Comment by ahyield** [comment]
@bebraw thank you but I meant more like the screen shot attached:

<img width="1734" alt="Screenshot 2024-03-24 at 16 26 10" src="https://github.com/MonoLisaFont/feedback/assets/4132009/ac857eeb-2fc7-4afd-bc15-f19bea35f5a6">


As you can see vscode renders the code with the scripted character, is this a feature of the editor?

**Comment by bebraw** [comment]
@ahmgeek To replicate that rendering at Zed, you would have to do this kind of setup there: https://www.monolisa.dev/faq#how-to-enable-the-script-variant-for-comments-or-function-names . In other words, you would have to find a way to enable `ss02` and have Zed use italics for the portions of text you want to be rendered using the script feature. A potential alternative would be to use the customize tool available at `/orders` to freeze the feature directly to the font and use italics directly though the former approach is preferable if possible.

**Comment by ahyield** [comment]
You are awesome. Thanks.
