### ISSUE TITLE
[Feature request]: Illegal copy of the font on GitHub 

### ISSUE THREAD

**Issue by l-d-s** [MonoLisaFont/feedback#265]
### What feature are you proposing?

It seems a copy of the font has been illegally posted at at https://github.com/d8-bbc11/monolisa by @d8-bbc11 (and also possibly at https://github.com/diegotres/MonoLisa-font-backup )

**Comment by MarcusSterz** [comment]
Thank you @l-d-s for letting us know! We have just reported this user.
