### ISSUE TITLE
[Bug]: Uppercase `A` renders weird

### ISSUE THREAD

**Issue by gixim** [MonoLisaFont/feedback#266]
### Edition

Plus

### What version are you using?

2.013 pre-release

### What type of weights are you using?

Static (customized)

### Operating system

Windows 11 23H2

### Program

VSCode, Windows Terminal

### Display resolution

1920x1080

### What happened?

Hello,

Thank you for the update!
This update would make the font more readable, and more familiar for those new to this font.

I have noticed that uppercase `A` and variants with diacritics have a weird horizontal bar, like this screenshot.

![Screenshot 2024-04-18 013025](https://github.com/MonoLisaFont/feedback/assets/83961834/18234f3a-4877-4334-b56d-0c349b82d067)

Only roman variant renders weird. Italic/cursive variants rendered correctly.
My font customization is only the font name and other settings are left as they are.

I wasn't sure if it is good to mention about pre-release version here but I just wanted to let you know.

Thanks

**Comment by bebraw** [comment]
Make sure you have the latest prerelease as I believe that should have been fixed about an hour ago. You can verify the current behavior through https://www.monolisa.dev/specimen/prerelease .

**Comment by gixim** [comment]
Oh, I haven't noticed that the release has been updated.
I downloaded the font again and that worked correctly.

Thank you.

**Comment by bebraw** [comment]
No worries, let us know if you notice anything else as that's why the prerelease is there. 👍
