### ISSUE TITLE
[Bug]: Variable font only seems to be italic

### ISSUE THREAD

**Issue by Sacro** [MonoLisaFont/feedback#267]
### Edition

Complete (Pro)

### What version are you using?

2.013

### What type of weights are you using?

Default (non-customized)

### Operating system

Windows 11 23H2 (OS Build 22631.3447)

### Program

Notepad

### What happened?

Open the settings, select the family as "MonoLisa Variable", all the fonts in the Style dropdown are Italic, no none-italic.

**Comment by Sacro** [comment]
Also, there's a "MonoLisa Variable Thin" family, this has multiple styles that are all "Regular"

**Comment by bebraw** [comment]
I have trouble reproducing this under MacOS so I imagine it might be a Windows specific issue to debug.

**Comment by bebraw** [comment]
When you have time, can you check if the latest prerelease has the issue? When downloading, make sure to choose `prerelease` channel.

**Comment by Sacro** [comment]
Italic now looks right, but non-italic are still all called "Thin"

**Comment by Sacro** [comment]
I now have Font Family `MonoLisa Variable`, this covers all the italic styles, correctly named

And then I have `MonoLisa Variable Thin`, which is the non-italic, but all styles still show `Regular`

**Comment by mekkablue** [comment]
Works as expected in upcoming font version  2.014:

![image](https://github.com/MonoLisaFont/feedback/assets/1103103/30f891b1-0171-44bb-9ad1-fe28dfe4c920)

**Comment by Sacro** [comment]
How does it look in the settings dropdown?

Did you push an updated preview?

**Comment by bebraw** [comment]
@Sacro I'll let you know when there's a new version to test. Likely later today.

**Comment by bebraw** [comment]
@Sacro Good to test now.

**Comment by Sacro** [comment]
That seems to have fixed it!

Looking fixed in Notepad and VSCode at least.

**Comment by bebraw** [comment]
Fixed in 2.014.
