### ISSUE TITLE
[Feature request]: Bring back the original 'g' into the basic package

### ISSUE THREAD

**Issue by azuenko** [MonoLisaFont/feedback#269]
### Description

[Monolisa 2.013](https://www.monolisa.dev/releases/2.013) release introduces, among other fixes, the following breaking change:

> Alt 1 g variant made default in upright version, original g kept as ss03

The change is breaking, as the `ss03` option is only available in Plus subscription:
![image](https://github.com/MonoLisaFont/feedback/assets/7202664/8d113e95-494f-4884-8d0b-8fcb467fe2c4)

This effectively leaves Basic subscription holders with a difficult choice: either to accept the new variant, or stop getting the updates.

It would be much, much better for some of us to be able to keep the original 'g', if the `ss03` option remains available in the Basic subscription.

### Some thoughts

Yes, if feels like the 'g' have been a difficult one. Indeed, this is a letter with a character. Maybe even too strong character. This is why it stands out. To be honest, I originally hesitated about it. I even considered opting for a Plus subscription, as it provided the option for a more standard variant at that time. But, a few weeks after I purchased & set Monolisa as the default font I actually started to like it. Even love it. The commands `git` and `grep`, written with the original 'g' started to feel even more ninja. The letter has become iconic for the font, along with the capital 'C' . 

It is possible the choice to make the more softer variant of the 'g' is based on some user research. Indeed, with no prior exposure to the font, I would opt for a safer version. But now I'm afraid I cannot live without original 'g' anymore. Continuing to have it in the Basic subscription would be a good gesture for the existing faithful users.

**Comment by MarcusSterz** [comment]
We heard you! Not only will we bring the iconic `g` back but decided to make all three options available for all packages in the future.

**Comment by bebraw** [comment]
Done in 2.014. Now old `g` is the default and the other two are available through `ss03` and `ss04`.

**Comment by azuenko** [comment]
Thank you Monolisa team for shipping the change that swiftly! ❤️
