### ISSUE TITLE
[Bug]: Some apps use fake bold instead of actual bold face

### ISSUE THREAD

**Issue by gixim** [MonoLisaFont/feedback#270]
### Edition

Plus

### What version are you using?

2.013

### What type of weights are you using?

Default (non-customized)

### Operating system

Windows 11 23H2

### Program

Notepad++

### Display resolution

1920x1080

### What happened?

Hello,

I have installed regular and bold weight and italic variant, but Notepad++ doesn't recognize MonoLisa Bold and uses fake bold instead as I show in the screenshot below.
Notepad++ doesn't recognize only roman bold variant; it renders bold italic correctly.

![Screenshot 2024-04-26 003748](https://github.com/MonoLisaFont/feedback/assets/83961834/c7dee4d4-e92b-4593-a089-ad57d5f42d37)

Also I found some apps (Windows Terminal, Windows default notepad) lists MonoLisa regular and bold as different fonts.
This might relate to the issue.

![Screenshot 2024-04-26 005017 2](https://github.com/MonoLisaFont/feedback/assets/83961834/b27e5c43-9337-4c22-9e19-1a4a2f1808de)

**Comment by bebraw** [comment]
@MarcusSterz This might be related to the other Windows issues. Do you know why it could be showing the bold variant separately like that?

**Comment by bebraw** [comment]
When you have time, can you check if the latest prerelease has the issue? When downloading, make sure to choose `prerelease` channel.

**Comment by gixim** [comment]
The latest pre-release version also has the same issue.

One more thing I found is that the font (both 2.013 and the pre-release) with Nerd Fonts applied doesn't have the issue.
I'm not sure if this info helps, but I will share it just in case.

**Comment by bebraw** [comment]
@gixim There's a new prerelease to test now.

**Comment by gixim** [comment]
Hello, I just tried and it looks the issue is solved.
Here's the screenshots with the latest pre-release.

![Screenshot 2024-05-02 220454](https://github.com/MonoLisaFont/feedback/assets/83961834/57c144fb-1f16-4cc7-abd6-dfe0d3b795a4)

![Screenshot 2024-05-02 214621 2](https://github.com/MonoLisaFont/feedback/assets/83961834/97a97c95-e48e-4d26-9cf8-3d64c29489ad)

**Comment by bebraw** [comment]
Fixed in 2.014.
