### ISSUE TITLE
[Bug]: No ligatures basic plan

### ISSUE THREAD

**Issue by rumichaska** [MonoLisaFont/feedback#272]
### Edition

Basic (Personal)

### What version are you using?

2014

### What type of weights are you using?

Default (non-customized)

### Operating system

Pop-OS

### Program

Kitty

### Display resolution

1440 x 1080

### What happened?

Greetings,

Up until the 2013 version ligatures (LIGA and CALT) were included in the basic plan (Fig-1) but with the 2014 version ligatures moved to plus features (Fig-2 and Fig-3). I really love the font and ligatures were one of the main reasons I opted for MonoLisa. I hope ligatures return to the basic plan as shown on the purchase page.

![imagen](https://github.com/MonoLisaFont/feedback/assets/88051372/9f934763-950d-442a-bda3-826f370e5e6b)
(Fig-1)

![imagen](https://github.com/MonoLisaFont/feedback/assets/88051372/dfe3d711-f846-49ee-b2bc-6f19ee5c9f87)
(Fig-2)
![imagen](https://github.com/MonoLisaFont/feedback/assets/88051372/03f51d7c-a836-4218-ac42-0827b8da9a48)
(Fig-3)

**Comment by bebraw** [comment]
Ah, good catch. Let me fix, I know what's the problem.

**Comment by bebraw** [comment]
Fixed in 2.015. Thanks for the report.

**Comment by rumichaska** [comment]
Thank you for shipping the change!
