### ISSUE TITLE
[Issue]: "Bouncing" `*` on Curses TUI with ligatures on

### ISSUE THREAD

**Issue by Neved4** [MonoLisaFont/feedback#276]
> [!IMPORTANT]  
> Fix: ***Disable ligatures on your terminal font.***

### Edition

Plus

### What version are you using?

2.003

### What type of weights are you using?

Static (customized)

### Operating system

macOS Sonoma 14.5

### Program

Terminal.app, iTerm2, Kitty

### Display resolution

2880x1800

### What happened?

Found an amusing one: MonoLisa seems to have bouncy asterisks on a terminal running curses.

Videos show GnuPG's `pinentry` (curses) with MonoLisa and SF Mono, respectively:

https://github.com/MonoLisaFont/feedback/assets/63655535/6f770e8a-c119-43cd-af72-bfbdebf1e191

https://github.com/MonoLisaFont/feedback/assets/63655535/66842de7-7b7f-4da1-bf3b-9c5a0ede03a7

###### Notice how the asterisk symbol bounces when entering the password when using the MonoLisa font.

Not sure how much of this is related to MonoLisa's glyphs / bitmap and how much is related to `pinentry` / `curses`, and if other `curses` programs are also affected.

Probably a nitpick without importance, so low priority.

Thanks for your amazing font! 🤍

**Comment by okonet** [comment]
It's a ligature kicking in. One way would be to disable ligatures since I don't know if there is a way to make it work differently.

**Comment by Neved4** [comment]
That was exactly it! Sorry I didn't know, thanks so much @okonet! Will close

P.S. For anyone else looking, in `Kitty` there's `disable_ligatures always`, in `iTerm 2` there's a setting too, and in `Terminal.app` there's a _`Ligatures`_ setting under the _`Typography`_ menu for the font:
![Terminal.app](https://github.com/MonoLisaFont/feedback/assets/63655535/eb804b89-7073-400f-9b59-738153555917)
