### ISSUE TITLE
Thin font weights unaffected by editor.fontWeight in vscode on macOS

### ISSUE THREAD

**Issue by kevinsperrine** [MonoLisaFont/feedback#28]
The `editor.fontWeight` settings in VSCode don't have any effect when attempting to use the "MonoLisa" font family.  However, if I explicitly set the weight by using the PostScript name of the thin weights it works as expected. This same issue doesn't seem to affect the medium, bold, or black weights.

I think this video shows the issue pretty clearly.
[https://www.dropbox.com/s/5larqkz2t62067g/Screen%20Recording%202020-05-19%20at%209.02.04%20PM.mov?dl=0](https://www.dropbox.com/s/5larqkz2t62067g/Screen%20Recording%202020-05-19%20at%209.02.04%20PM.mov?dl=0)

Please provide browser and OS so it's easier for us to debug.
vscode 1.45.1
macOS Mojave 10.14.5
MonoLisa 1.401

**Comment by bebraw** [comment]
Are you using the personal or the professional edition (includes all weights)?

**Comment by bebraw** [comment]
I am using VS Code and macOS Catalina. If I use font name "MonoLisa" (1.401) and vary the font weight using the professional edition, it's changing the weight as expected.

I wonder what could be the difference. Are you using the otf versions of the font?

**Comment by kevinsperrine** [comment]
@bebraw, Yes, I'm using the OTF files from the Professional version. It's still happening on VSCode 1.46.0, but I'm still on Mojave. It might be an issue there. I'll just continue using the postscript name of the fonts. Thanks for checking into it.

**Comment by bebraw** [comment]
Alright. 👍

**Comment by bebraw** [comment]
I can reproduce this particularly for *light* weights (100-300) now so I'm re-opening the issue.

**Comment by bebraw** [comment]
We looked into it and my understanding is that we cannot fix this at the font side. I've documented the issue at the font FAQ so VS Code users are aware of the limitation.
