### ISSUE TITLE
Personal Plus Plan - generating webfonts permitted? 

### ISSUE THREAD

**Issue by nfejzic** [MonoLisaFont/feedback#280]
### What feature are you proposing?

Hey there! I recently purchased this awesome font and I'm quite enjoying using it.

Since I purchased the Plus plan, I only get (as far as I can tell) TrueType format of the font (`*.ttf`). From the license: 

> 3.b Web
> 
> You can embed the purchased webfont into your website (a group of pages related to one domain, including sub-domains).
> 
> FaceType is not responsible for installing, embedding, hosting or updating the webfonts. Web design agencies or hosting providers are not allowed to share a single license across their clients’ websites.

I have multiple questions: 

1. Does "group of pages related to one domain" mean I can only use font on one domain, or is it just a clarification of "website" and I can use it on multiple domains that I own? (Non-Commercial use of course) 
2. Am I allowed to generate webfonts (`.woff`) from my TrueTypeFont versions? Any recommendations on ways to do this? 

Thank you in advance!

**Comment by okonet** [comment]
Hello! Thanks for your kind words!

The Plus version does not include webfont and this not eligible for web use. It's only allowed to use it in the editor / terminal for personal purposes. 

If you're interested in embedding it to your website we would kindly ask you to upgrade. You'll get a webfont plus an ability to optimize the bundle size by excluding features you don't need on the website. 

Hope it helps. Thanks!

**Comment by nfejzic** [comment]
Thank you for the clarification. I will use some other font for the time being.
