### ISSUE TITLE
[Bug]: ligatures of some symbols are not rendered correctly

### ISSUE THREAD

**Issue by mdmjmsa** [MonoLisaFont/feedback#282]
### Edition

Plus

### What version are you using?

2.015

### What type of weights are you using?

Default (non-customized)

### Operating system

Linux (Fedora 40), macOS 13.3

### Program

Kitty, wezterm

### Display resolution

3840x2160, 2560 x 1600

### What happened?

I haven't tested all and I am not sure what exactly happens under the hood. Just give some examples:

- `!=`, `~=` rendered as `&=`
- `+=`, `-=` rendered as `%=`
- `/=` rendered as `&=`
- `#:` rendered as `::`

**Comment by bebraw** [comment]
Can you add your Kitty/wezterm configuration? Can you reproduce the issue elsewhere (iTerm 2, VS Code etc.)?

**Comment by mdmjmsa** [comment]
Sorry, I haven't confirmed whether this issue occurs somewhere else, maybe I could have a try in Visual Studio later today. My config of kitty and wezterm are given as below:

## Kitty config

```
#: Fonts {{{
font_family      MonoLisa Medium
bold_font        MonoLisa Bold
italic_font      MonoLisa Medium Italic
bold_italic_font MonoLisa Bold Italic

font_size 14

#: Nerd Font v3
#: Seti-UI + Custom
symbol_map U+E5FA-U+E6AC Symbols Nerd Font Mono
#: Devicons
symbol_map U+E700-U+E7C5 Symbols Nerd Font Mono
#: Font Awesome
symbol_map U+F000-U+F2E0 Symbols Nerd Font Mono
#: Font Awesome Extension
symbol_map U+E200-U+E2A9 Symbols Nerd Font Mono
#: Material Design Icons
symbol_map U+F0001-U+F1AF0 Symbols Nerd Font Mono
#: Weather
symbol_map U+E300-U+E3E3 Symbols Nerd Font Mono
#: Octicons
symbol_map U+F400-U+F532,U+2665,U+26A1 Symbols Nerd Font Mono
#: Powerline Symbols
symbol_map U+E0A0-U+E0A2,U+E0B0-U+E0B3 Symbols Nerd Font Mono
#: Powerline Extra Symbols
symbol_map U+E0A3,U+E0B4-U+E0C8,U+E0CA,U+E0CC-U+E0D4 Symbols Nerd Font Mono
#: IEC Power Symbols
symbol_map U+23FB-U+23FE,U+2B58 Symbols Nerd Font Mono
#: Font Logos
symbol_map U+F300-U+F32F Symbols Nerd Font Mono
#: Pomicons
symbol_map U+E000-U+E00A Symbols Nerd Font Mono
#: Codicons
symbol_map U+EA60-U+EBEB Symbols Nerd Font Mono
#: Heavy Angle Brackets
symbol_map U+276C-U+2771 Symbols Nerd Font Mono
#: Box Drawing
symbol_map U+2500-U+259F Symbols Nerd Font Mono
#: }}}
```

## Wezterm config:

```lua
local wezterm = require("wezterm")

if wezterm.config_builder then
  config = wezterm.config_builder()
end

return {
  font = wezterm.font_with_fallback({
    { family = "MonoLisa Medium" },
  }),

  font_rules = {
    {
      intensity = "Normal",
      italic = true,
      font = wezterm.font_with_fallback({
        { family = "MonoLisa Medium Italic" },
      }),
    },
    {
      intensity = "Bold",
      italic = false,
      font = wezterm.font_with_fallback({
        { family = "MonoLisa Bold" },
      }),
    },
    {
      intensity = "Bold",
      italic = true,
      font = wezterm.font_with_fallback({
        { family = "MonoLisa Bold Italic" },
      }),
    },
  },

  font_size = 9.0,
}
```

**Comment by bebraw** [comment]
I installed 2.015 Plus to my machine (Sonoma 14.6) and did the following minimal configuration for wezterm: `config.font = wezterm.font 'MonoLisa'`. Render below:

<img width="167" alt="Screenshot 2024-09-16 at 11 01 52" src="https://github.com/user-attachments/assets/7ea66e88-5909-4355-a23f-861063cd8a19">

I cannot reproduce the behavior your are seeing in wezterm at least.

**Comment by mdmjmsa** [comment]
weirdly I re-downloaded the fonts and performed a reinstallation, now this is gone.

**Comment by bebraw** [comment]
Ok, maybe some bit was sideways. Good to hear it works.
