### ISSUE TITLE
[Bug]: ss14, ss16 does not work in VSCode

### ISSUE THREAD

**Issue by dongz9** [MonoLisaFont/feedback#289]
### Edition

Plus

### What version are you using?

1.808

### What type of weights are you using?

Default (non-customized)

### Operating system

MacOS 14.2

### Program

VS Code

### What happened?

ss14, ss16 does not work in VSCode

**Comment by bebraw** [comment]
Those features exist only in version 2. Reference: https://www.monolisa.dev/releases/2.011 .
