### ISSUE TITLE
dyslexiefont variant?

### ISSUE THREAD

**Issue by bebraw** [MonoLisaFont/feedback#3]
> Very tempted to use this it's elegant. I would also challenge you to consider implementing a specimen that puts some weight on some of the font equivalent to the dyslexiefont typeface which is great for reading log files.

Source: https://news.ycombinator.com/item?id=22535174 .

**Comment by MarcusSterz** [comment]
Nice!

**Comment by MarcusSterz** [comment]
The design of ML covers most problems dyslexic people have but a particular variant just for that is not on my list.

**Comment by okonet** [comment]
We decided not to act on it now.
