### ISSUE TITLE
The website shows two different currencies for me, is that intended?

### ISSUE THREAD

**Issue by JobLeonard** [MonoLisaFont/feedback#30]
So guess which country I'm visiting your website from ;)

<img alt="image" src="https://user-images.githubusercontent.com/259840/84166035-aa669800-aa74-11ea-82e5-d025b5a13b2b.png">

Not sure if this is a bug or by design (I don't know, maybe there is some legal reason for this?), but just mentioning it in case this wasn't intentional.

(If it was it might be nice to add a little disclaimer explaining that why there are two currencies)

(Also also, I'm not entirely sure if "Skr" is technically the correct abbreviation - I usually only the Swedish crown referred to as SEK)

**Comment by bebraw** [comment]
Hi,

Thanks for bringing this up. For some reason the professional edition was missing Swedish price and I added it there so it should show up now.

The currency is going through `Intl.NumberFormat` and we can add an exception for Sweden there.

**Comment by bebraw** [comment]
@JobLeonard Can you check this? We've done a bunch of work on the site so it's possible this has been fixed now.

**Comment by JobLeonard** [comment]
It's been reversed! Hahaha, don't you just love software development? ;)

![image](https://user-images.githubusercontent.com/259840/102889053-3ad95880-445a-11eb-978d-e544bf2a717b.png)

**Comment by bebraw** [comment]
@JobLeonard Ok, that's one step forward, one step backward. I clicked some buttons to match personal/plus with professional, can you check now?

**Comment by JobLeonard** [comment]
Sorry for reacting slowly, got your email on my phone but don't have access to GH there, then forgot about it when checking my mail on my desktop until after Christmas.

The good news is that I see SEK on every item!

![image](https://user-images.githubusercontent.com/259840/103232888-f22f0d00-493b-11eb-8eb4-ef54f0d73ba6.png)

**Comment by bebraw** [comment]
No worries (I'm taking some time off as well). Let's close this one then. 👍
