### ISSUE TITLE
»Unwanted« Ligature 

### ISSUE THREAD

**Issue by emanuelpesendorfer** [MonoLisaFont/feedback#32]
OS: MacOS
Editor: Sublime 3
Browser: Chrome

When typing a . (dot) and - (hyphen) next to each other I get an unwanted Ligature (see Screenshot on the left). The Browser shows the two characters as expected. Not a big issue but it got me confused ^^
 
<img width="1405" alt="Screenshot 2020-06-19 at 10 39 01" src="https://user-images.githubusercontent.com/2571129/85115767-7b8eb580-b21c-11ea-92b2-b8105c0a7f57.png">

**Comment by okonet** [comment]
I'm removing `bug` label since we intentionally added this ligature but we're considering adding stylistic sets for ligatures in the future so this problem can be solved as well.

**Comment by okonet** [comment]
This should be solved with https://github.com/MonoLisaFont/website/issues/359

**Comment by bebraw** [comment]
@emanuelpesendorfer We separated these type of ligatures to `liga` in 1.600. If you enable only `calt`, then it's not going to render combinations like `.-`. See more at https://www.monolisa.dev/releases .

I guess the remaining question is, does Sublime Text provide enough control for this?

Let me know if the current solution works for you or if we should iterate further.

**Comment by bebraw** [comment]
@emanuelpesendorfer I came by https://www.sublimetext.com/docs/3/ligatures.html . I think you should be able to get the behavior you want by setting `"no_liga"`. The caveat is that doing this will lose **shape replacing** ligatures.

**Comment by okonet** [comment]
I think this one is a great one for [stylistic sets](https://github.com/MonoLisaFont/website/issues/408). @MarcusSterz what do you think?

**Comment by bebraw** [comment]
Is there a valid use case for the middle dot and dash ligature?

Since for most, not transforming is the right option, I would say this should go behind a stylistic set as well.

**Comment by okonet** [comment]
I'd drop it for now and revisit as a stylistic set option.

**Comment by bebraw** [comment]
For reference, JetBrains Mono dropped the character (https://github.com/JetBrains/JetBrainsMono/issues/76) and there's a related open issue for FiraCode at https://github.com/tonsky/FiraCode/issues/670.

**Comment by bebraw** [comment]
@MarcusSterz Would it make sense to push this combination behind a character variant? It can then be exposed through the customize UI.

**Comment by bebraw** [comment]
We decided to drop the `.-` combination entirely from the typeface after considering different options.

**Comment by bebraw** [comment]
This one has been solved in the newly released 2.0.
