### ISSUE TITLE
Version 1.5 truetype problems on windows

### ISSUE THREAD

**Issue by mWaltari** [MonoLisaFont/feedback#34]
Apps can't render whole row height.

![Screenshot 2020-07-03 07 20 45](https://user-images.githubusercontent.com/4082975/86431788-61fe6b00-bcfe-11ea-9830-1fb6d9b3af6d.png)
![Screenshot 2020-07-03 07 22 51](https://user-images.githubusercontent.com/4082975/86431789-632f9800-bcfe-11ea-8611-34c74fd295c7.png)

**Comment by rcapraro** [comment]
Same issue in Intellij 2020.1.2, but no issue in Visual studio code or Windows terminal.
![image](https://user-images.githubusercontent.com/245490/86515060-b5fc7300-be16-11ea-9e37-cb678986382d.png)

**Comment by bebraw** [comment]
I've included the previous version (1.401) to the zip. Please use that as a fallback for ttf until our designer has time to troubleshoot this one better.

You can find the zip from your email. It's the same link in the Paddle email you used to download the font earlier.

**Comment by MarcusSterz** [comment]
We were able to reproduce the issue. The upcoming version 1.501 fixes this problem.

**Comment by MarcusSterz** [comment]
Closed.

**Comment by bebraw** [comment]
@mWaltari I've included the development version to test. You can get if you re-download the font using the original link. Let me know if the fix works for you.

**Comment by maraisr** [comment]
Re the development copy, I have grabbed that. Its definitely better than it was at 500, or 401. That being said, its still cutting the ascendors from what I can see.

**Comment by bebraw** [comment]
@maraisr I copied your screenshot from https://github.com/MonoLisaFont/feedback/issues/37#issuecomment-678082132 here so we have the info at the right place:

![cutting-if](https://user-images.githubusercontent.com/166921/90863147-3cedb680-e397-11ea-8ca2-52b3e7008d4b.png)

CC @MarcusSterz @mekkablue - note the cut `if` and `import` statements. It's better but no cigar.

**Comment by mekkablue** [comment]
Which OS, which app?
Cache issue excluded?

**Comment by maraisr** [comment]
Yes, yes and yes. As outlined in my other ticket and also the title of this issue. 

Its Windows 10 Pro, and in my case Intellij's Webstorm.

**Comment by bebraw** [comment]
@maraisr To make sure it's not a caching issue, can you erase your font cache on Windows and try with the `dev` version again?

**Comment by bebraw** [comment]
@maraisr I found https://troubleshooter.xyz/wiki/rebuild-font-cache-in-windows-10/ related to rebuilding the font cache. Please let me know how it goes with cache.

**Comment by mekkablue** [comment]
Upcoming MonoLisa 1.501 in WebStorm 2020.2.2, build form Sept 14, 2020, on Windows 10:

![Screenshot 2020-09-25 at 14 34 55](https://user-images.githubusercontent.com/1103103/94267899-a6378b00-ff3c-11ea-868e-8ca9e79509e8.png)
![Screenshot 2020-09-25 at 14 34 01](https://user-images.githubusercontent.com/1103103/94267903-a8014e80-ff3c-11ea-81b9-95dfc7e26db8.png)

I cannot find any clippings. The issue can be closed.

**Comment by bebraw** [comment]
@mekkablue Ok, thanks. I'll close on the next release then. 👍

**Comment by bebraw** [comment]
This should be resolved in 1.6 (please use the original download link). Closing.
