### ISSUE TITLE
Some long (3+) ligatures break on Sublime

### ISSUE THREAD

**Issue by HKervadec** [MonoLisaFont/feedback#36]
Hello,

Some ligatures (v1.500) aren't displayed properly on Sublime (build 3211), while it seems to be working on VSCode:

![ligatures_cmp](https://user-images.githubusercontent.com/4191866/89737750-9a057600-da41-11ea-8751-ee2119be7b64.png)

I am on Linux (kernel 5.7.8-zen2-1-zen), with Xorg/Cinnamon. 

The test text as reference:
```
# H1
## H2
### H3
#### H4

.
..
...
....

-
--
---
----

=>
==>
<==
>>=
<=>
<==>
<!--
```

**Comment by bebraw** [comment]
@MarcusSterz Here's the render against the current development version on MacOS. Sublime Text on left, VS Code on right.

<img width="563" alt="Screenshot 2020-08-11 at 9 21 29" src="https://user-images.githubusercontent.com/166921/89869168-a19d5a00-dbbc-11ea-8fdf-aba7a0b675a4.png">

Here's reference for testing: https://www.sublimetext.com/, https://www.sublimetext.com/docs/3/ligatures.html .

@HKervadec To make this one easier to test, can you please provide the font configuration you are using at Sublime? That way we can be sure we're testing with the same and can rule out some issues.

**Comment by HKervadec** [comment]
Hello, thank you for taking the time to investigate it.

I do not have any font options for now:
```python
	"font_face": "MonoLisa",
	"font_options":
	[
	],
```

Let's note that I tried by installing the OTF only, TTF only, or having both available. Is there one that I should prefer over the other ? My current fc-list:
```
>>> fc-list | grep -i MonoLisa
/usr/share/fonts/TTF/MonoLisa-BoldItalic.ttf: MonoLisa,MonoLisa Bold:style=Bold Italic
/usr/share/fonts/TTF/MonoLisa-RegularItalic.ttf: MonoLisa:style=Regular Italic,Italic
/usr/share/fonts/TTF/MonoLisa-Regular.ttf: MonoLisa:style=Regular
/usr/share/fonts/OTF/MonoLisa-Bold.otf: MonoLisa:style=Bold
/usr/share/fonts/OTF/MonoLisa-BoldItalic.otf: MonoLisa,MonoLisa Bold:style=Bold Italic
/usr/share/fonts/TTF/MonoLisa-Bold.ttf: MonoLisa:style=Bold
/usr/share/fonts/OTF/MonoLisa-Regular.otf: MonoLisa:style=Regular
/usr/share/fonts/OTF/MonoLisa-RegularItalic.otf: MonoLisa:style=Regular Italic,Italic
```

**Comment by bebraw** [comment]
@HKervadec My understanding is that OTF is often the best option. TTF is provided specifically for Windows.

I tested using OTF.

**Comment by HKervadec** [comment]
I uninstalled the TTF then, and also rebuild the cache/rebooted -- the problem is the same. I am disabling the ligatures until this is resolved. 

Another data point: those ligatures work fine on Sublime with Fira Code, but I don't know if they had to add some dedicated workaround for Sublime.

**Comment by bebraw** [comment]
> Another data point: those ligatures work fine on Sublime with Fira Code, but I don't know if they had to add some dedicated workaround for Sublime.

That's valuable information. Both MonoLisa and Fira use Glyphs (a popular font app) to manage source. I imagine there's some subtle difference that breaks the output for Sublime Text and it's worth looking into (cc @mekkablue).

**Comment by mekkablue** [comment]
AFAICS we have not pinned down whether it is an installation problem or a configuration issue, which seems likely because the same app on different systems does not exhibit the issue. Since I do not have access to a Linux machine, can you verify the following please:

* Is the font unavailable in other apps as well? Or is just Sublime affected?
* Have you tried on a different machine, or at least in a different user?
* Deleted application caches and settings and reconfigured from scratch?

I imagine simultaneously installing equivalent fonts (TTF and OTF in this case) must lead to font conflicts, but I do not know how Linux handles these.

**Comment by bebraw** [comment]
@mekkablue Note that I can see the ligature issue on my system (MacOS) with the current OTF (see render above) so it seems like it's not limited to Linux alone.

**Comment by mekkablue** [comment]
I finally could reproduce the render issue by switching through font sizes with Cmd +/−. It seems like in certain pixel sizes, SublimeText does not scale the rendering area for the glyph horizontally, it only scales it vertically. For instance, going from 15px to 16px, the horizontal width stays the same but the glyphs are scaled nonetheless:

![sublimetext-fontscaling-15-16](https://user-images.githubusercontent.com/1103103/90331237-359f6500-dfb3-11ea-9855-318415f279be.gif)

IOW, the ligatures work, but are cut off by the insufficient space that is allocated for rendering them. There is nothing in the font that dictates that style of rendering, but it may have to do with the ligature direction (ML substitutes forewards, whereas FC substitutes backwards).

**Comment by bebraw** [comment]
@mekkablue Ok, is this something to report to upstream then? I wonder if Sublime operates on some assumption related to glyph width there.

**Comment by mekkablue** [comment]
I reported the issue on the SublimeText forum, hoping for a response from the devs:
https://forum.sublimetext.com/t/ligature-glyphs-cut-off-horizontally/53275

**Comment by bebraw** [comment]
Great, thanks. 👍

**Comment by mekkablue** [comment]
Just got confirmation that this is indeed an issue of ST3. There is going to be a fix in an upcoming version of ST.

**Comment by bebraw** [comment]
Awesome. 🥁

**Comment by bebraw** [comment]
@HKervadec Can you check this? My understanding is that Sublime has done some fixes.

**Comment by HKervadec** [comment]
I've done some quick tests -- so far it is not working. But I am not on my main dev setup, I'll come back at you in a few days, with more details.

**Comment by HKervadec** [comment]
So I did more thorough tests, and also upgraded to the latest version of Monolisa (1.600 OpenType installed). Notice that there hasn't been a release in SublimeText in the meantime (v3211).

The change in https://github.com/sublimehq/Packages/pull/2449 seems to update only the syntax for markdown -- meaning that even if it was working, having the ligatures to properly work across languages would require to modify the corresponding `.sublime-syntax`. (I tested it locally by creating a new custom syntax [with the latest version](https://github.com/sublimehq/Packages/blob/master/Markdown/Markdown.sublime-syntax), and applying it to my sample text.)

# Current render (no syntax selected, as [recommended to test](https://www.sublimetext.com/docs/3/ligatures.html))
## Fira code (with ligatures)
![firacode](https://user-images.githubusercontent.com/4191866/102444242-b8ced700-3ff6-11eb-8a89-311e8e211208.png)

## Monolisa (with ligatures)
![monolisa](https://user-images.githubusercontent.com/4191866/102444264-c4220280-3ff6-11eb-93d3-56ccfd549342.png)

## Firacode (no ligatures)
![firacode_nocalt](https://user-images.githubusercontent.com/4191866/102444303-e0be3a80-3ff6-11eb-9620-7b13f7738baa.png)


## Monolisa (no ligatures)
![monolisa_nocalt](https://user-images.githubusercontent.com/4191866/102444286-d2701e80-3ff6-11eb-9ab3-1f5f61f0ef7d.png)

# Current render (latest markdown syntax)
## Monolisa
![monolisa_markdown](https://user-images.githubusercontent.com/4191866/102444613-9ee1c400-3ff7-11eb-8336-cd3621fff199.png)


## Fira code
![firacode_markdown](https://user-images.githubusercontent.com/4191866/102444617-a1dcb480-3ff7-11eb-8460-38a35f36d598.png)


---
So to me the issue is deeper than the syntax definition, especially as it does not affect Fira code in the same way.

While testing a bit more different font options, I found out that SublimeText does not support very well stylistic sets. 
* https://github.com/sublimehq/sublime_text/issues/2302
* https://forum.sublimetext.com/t/support-for-more-stylistic-sets/46418/4

Seems only the one names ss01 to ss10 can work. (And yeah I can activate `ss01` on MonoLisa but not `zero`. Similar behavior for FiraCode.)

Also found that: https://forum.sublimetext.com/t/sublime-text-3-build-3207-ligatures-not-working/44690/10
It might help to pinpoint exactly why long ligatures works with one font but not with the other.

**Comment by bebraw** [comment]
@mekkablue When you have time, could you please check this one? It seems the issue still persists.

The weird thing is that both Fira Code and MonoLisa are based on a Glyphs definition. I wonder if it's something within MonoLisa definition that's tripping Sublime Text.

**Comment by HKervadec** [comment]
> I finally could reproduce the render issue by switching through font sizes with Cmd +/−. It seems like in certain pixel sizes, SublimeText does not scale the rendering area for the glyph horizontally, it only scales it vertically. For instance, going from 15px to 16px, the horizontal width stays the same but the glyphs are scaled nonetheless:
> 
> ![sublimetext-fontscaling-15-16](https://user-images.githubusercontent.com/1103103/90331237-359f6500-dfb3-11ea-9855-318415f279be.gif)
> 
> IOW, the ligatures work, but are cut off by the insufficient space that is allocated for rendering them. There is nothing in the font that dictates that style of rendering, but it may have to do with the ligature direction (ML substitutes forewards, whereas FC substitutes backwards).

I just did the same test (increasing and decreasing the font size), I can notice a similar (small) effect, though unlike you `###` is cut after 2 chars only and not 3.

**Comment by bebraw** [comment]
@HKervadec Can you test the nightly build of Sublime Text? My understanding is that the issue may have been fixed there already.

**Comment by HKervadec** [comment]
As far as I know there is no nightly build for Sublime Text3, but the beta for ST4 ( https://aur.archlinux.org/packages/sublime-text-4-dev/ ) seems to have fixed it :)

![st4](https://user-images.githubusercontent.com/4191866/103223966-14516c80-48f5-11eb-8d91-f911a1b0a75b.png)

I am closing this one for now

**Comment by bebraw** [comment]
Ok, cool. Thanks for confirming!
