### ISSUE TITLE
Low legibility on 13px (MacOS non-retina screen)

### ISSUE THREAD

**Issue by phortuin** [MonoLisaFont/feedback#38]
I am on a non-retina screen and work with a font-size of 13px because I am fairly close to my screen. I noticed the legibility of MonoLisa severely suffers on this font size. At 11px or 12px, to an extent, it is more legible, and at 14px it most certainly is too. Possibly this is a hinting/antialiasing issue.

I am on MacOS 10.15.6 with a mid 2015 MacBook Pro, screenshots taken on a ~2007 24" Apple LED Cinema Display (1920x1200) in Sublime Text 3.2.2 (reproduced in VSCode, with the same result).

MonoLisa
![monolisa](https://user-images.githubusercontent.com/137299/91439899-0f5cad80-e86e-11ea-8f86-62904da6db09.png)

- `i` and `1` are hard to distinguish because the dot is glued to the stem of the `i`
- caret `^` and tilde `~` are hard to read, especially the caret in itself, and the tilde compared with a hyphen (See also #7)
- the lowercase t has almost no visible ascender
- parentheses `()` and curly brackets `{}` are fairly similar in shape; so is the ligature arrow `=>` with ligature double equals `==`, and the single quote `'` with the backtick `` ` `` 

For comparison some common alternative coding fonts, all rendered at 13px:

IBM Plex Mono
![ibm-plex-mono](https://user-images.githubusercontent.com/137299/91439901-0ff54400-e86e-11ea-82e2-74b96d8ab728.png)

Input Mono Narrow
![input-mono-narrow](https://user-images.githubusercontent.com/137299/91439902-108dda80-e86e-11ea-9583-759ab68350c0.png)

JetBrains Mono
![jetbrains-mono](https://user-images.githubusercontent.com/137299/91439905-108dda80-e86e-11ea-8cef-ef2b42afe9e9.png)

Pragmata Pro
![pragmata-pro](https://user-images.githubusercontent.com/137299/91439907-11267100-e86e-11ea-8fb9-05a1c9557c3f.png)

Menlo
![menlo](https://user-images.githubusercontent.com/137299/91439908-11267100-e86e-11ea-92a4-25934b71ae4a.png)

Fira Code
![fira-code](https://user-images.githubusercontent.com/137299/91439910-11267100-e86e-11ea-8bd1-2b4f619551d9.png)

Operator Mono
![operator-mono-book](https://user-images.githubusercontent.com/137299/91439912-11bf0780-e86e-11ea-88d5-e776b12a1951.png)

Edit: after seeing these screenshots on a Macbook Pro retina screen (which resamples the "1x" images to double their resolution), they all become even more blurry than on my non-retina led display. So to get an idea of what my user experience is with MonoLisa I would recommend checking these screenshots on a non-retina screen.

**Comment by bebraw** [comment]
@phortuin Can you provide information about your operating system and display resolution? That will help debugging the issue further as then we can replicate the problem easier.

I can see it's a bit blurry compared to the other fonts.

**Comment by phortuin** [comment]
@bebraw Added info in my initial post. Sorry for omitting at first. Yes it’s mostly blurry, although PragmataPro (for instance) advertises that the font is optimized at font-sizes up to as small as 9pt. So that might be the reason it's still very crisp at 13px. 

Although it might be a technical issue, I think some glyphs could have more distinct forms, the caret, tilde, backtick and curly bracket being the most obvious. Input Mono does these very well

**Comment by phortuin** [comment]
This is Mono Lisa at 13px downscaled from a retina screen (1440x900 @2x). Much more legible. Not sure if this is useful, but it does point in the direction of the MacOS rendering engine making things muddy (whereas it does a better job with some other fonts, as speculated in my initial post).

![monolisa-downscaled](https://user-images.githubusercontent.com/137299/91482803-ed335180-e8a6-11ea-98ea-568e3d737ca9.png)

**Comment by okonet** [comment]
There are some hints on how font rendering works in this article: https://tonsky.me/blog/monitors/

As a suggestion: try using one font size smaller or bigger since it’s often solves the hinting issues.

**Comment by phortuin** [comment]
@okonet I have a pretty good idea how font rendering works and I've read the article before, thanks. I just hoped to point out that — in contrast to some other popular monospaced fonts — Mono Lisa doesn’t perform well at 13px, which by chance is the font size I feel the most comfortable with in my setup, the quality of my screen and distance to my eyes, etc. Like you suggested, I already had bumped font size to 14px which renders fine.

From your reaction I gather that looking into improved hinting at smaller font sizes isn't on the to do list, shall I close this issue then?

**Comment by MarcusSterz** [comment]
@phortuin We can certainly work on the i-issue, thx for pointing it out. 
The differentiation between ^ and ~ has already been taken into account – will be more distinguishable in next version. 
I do not necessarily agree on the { ( topic. 
Same with ' and `. We had no complaints regarding these two so far, looks OK on the screenshot as well – also in comparison to most other examples provided.

**Comment by mekkablue** [comment]
> From your reaction I gather that looking into improved hinting at smaller font sizes isn't on the to do list, shall I close this issue then?

Hinting information that is stored in the font is ignored by the CoreText renderer. IOW you cannot influence hinting on the Mac with the hinting info you put inside the font.

You can try toggling the font smoothing setting and different sizes. No font can render crisp in all pixel sizes.

**Comment by phortuin** [comment]
@MarcusSterz thanks, good to hear. Looking forward to these updates 

@mekkablue Good stuff, thanks for pointing that out. I thought that hinting info was used for just that: influencing the font renderer. Is it just that MacOS doesn’t play nice, or is it simply dependent on too many variables to get right?

**Comment by mekkablue** [comment]
> Is it just that MacOS doesn’t play nice, or is it simply dependent on too many variables to get right?

The CoreText renderer ignores the hinting information built into the font. It autohints the font on the fly when you install it the first time.

**Comment by bebraw** [comment]
Note that ^ and ~ have been improved in 1.6 so it should render better now. You can use the original download link to get the new release.

**Comment by okonet** [comment]
Can we close it? @phortuin can you try the latest version v1.600 and see if it has improved for you?

**Comment by dinhquochan** [comment]
Nah, @okonet  It's still low legibility! Looks `=`, `<` and `>` so bad.

MonoLisa 13px
![image](https://user-images.githubusercontent.com/9979458/102568237-a5fef400-4115-11eb-9eec-3186c6c88c48.png)

Hack 13px
![image](https://user-images.githubusercontent.com/9979458/102568263-b57e3d00-4115-11eb-9bee-003e83c8a176.png)

Menlo 13px
![image](https://user-images.githubusercontent.com/9979458/102568313-cdee5780-4115-11eb-9b14-6f05be902f7f.png)

SF Mono 13px
![image](https://user-images.githubusercontent.com/9979458/102568334-d9da1980-4115-11eb-9539-d299d944588f.png)

Jetbrains Mono 13px
![image](https://user-images.githubusercontent.com/9979458/102568359-e78f9f00-4115-11eb-9323-c56c23f98402.png)

Iosevka 13px
![image](https://user-images.githubusercontent.com/9979458/102568401-02621380-4116-11eb-9978-004246f8a874.png)

**Comment by dinhquochan** [comment]
14px is good!

![image](https://user-images.githubusercontent.com/9979458/102569369-efe8d980-4117-11eb-8b91-1c803b43dbce.png)

**Comment by karlhorky** [comment]
> * `i` and `1` are hard to distinguish because the dot is glued to the stem of the `i`

I've also opened https://github.com/MonoLisaFont/feedback/issues/54 for this one issue as per wishes from @bebraw

**Comment by bebraw** [comment]
We've done a fix for this in 1.700.

**Comment by dinhquochan** [comment]
Hi @bebraw, in Monitor (1080x1920, non-retina), `<` and `>` is weird, low legibility on 13px, looks screenshot below:

![image](https://user-images.githubusercontent.com/9979458/145920489-a5fa0a4e-9717-4c33-929a-36a4f1a9a693.png)

On 14px, its seem fixed

![image](https://user-images.githubusercontent.com/9979458/145920567-88debe1e-7817-4db7-b2c3-c164f62c83cd.png)

I try another fonts with 13px: Hack, Jetbrains Mono, Iosevka,  Cartograph CF:

![image](https://user-images.githubusercontent.com/9979458/145920865-237176e9-802c-4c45-ae04-86a44108b077.png)
![image](https://user-images.githubusercontent.com/9979458/145920905-d873f119-2460-4107-bb00-2cec2bba8f95.png)
![image](https://user-images.githubusercontent.com/9979458/145920959-51143475-a934-4f0a-9405-fd2194426bea.png)
![image](https://user-images.githubusercontent.com/9979458/145920989-4fa77e4a-1c66-47bc-9b3d-9dd20f8ceba4.png)

**Comment by bebraw** [comment]
@dinhquochan Can you open a separate issue about that?

**Comment by dinhquochan** [comment]
Ok @bebraw
