### ISSUE TITLE
Copyright ligature `(c)` should be disabled

### ISSUE THREAD

**Issue by alexeyten** [MonoLisaFont/feedback#44]
Version 1.6
https://www.monolisa.dev/playground

When I type `(c)` it becomes narrower than 3 chars thus changing alignment of the text.
Also this (artificial) example looks weird:
```js
const charCodes = [...str].map((c) => c.charCodeAt(0));
const charCodes = [...str].map((a) => a.charCodeAt(0));
```
![image](https://user-images.githubusercontent.com/44377/100442330-de805480-30b8-11eb-9bc2-6ccf69c3beef.png)

**Comment by bebraw** [comment]
@MarcusSterz I guess this would be a good fit for a stylistic set? Keeping it enabled by default feels like the wrong choice for programming as the combination can come up in functions as in the example above.

**Comment by okonet** [comment]
Thanks for reporting this! Yes, it should be put into a stylistic set.

**Comment by okonet** [comment]
Hmm, I'm trying to reproduce it in my editor, but it works as expected:

<img width="437" alt="CleanShot 2020-11-27 at 15 50 22@2x" src="https://user-images.githubusercontent.com/11071/100460907-45f1d080-30c8-11eb-8353-3ecb102bc6cd.png">

Are you sure it's not a text substation of the OS kicking in?

**Comment by bebraw** [comment]
I have the same in VS Code when ligatures are enabled:

<img width="104" alt="Screen Shot 2020-11-27 at 16 02 52" src="https://user-images.githubusercontent.com/166921/100462086-64f56000-30d2-11eb-8281-a4b22655523e.png">

I can also see the problem in the playground.

You may be right in that it's MacOS that's kicking in, though, as the replacement it's doing is fairly aggressive.

Likely the thing to do here would be to check if we've defined a ligature for (c) to begin with or is it something coming from elsewhere.

**Comment by alexeyten** [comment]
My screenshot is from site’s playground in Firefox on Ubuntu

**Comment by MarcusSterz** [comment]
Yes, I can disable it and make it a stylistic set, no prob.

**Comment by MarcusSterz** [comment]
It is a common ligature trick. You normally add ligature-like features like this to make the workflow faster for people who write text. 
I can delete it easily. Making it a stylistic set is not a good option since a stylistic set replaces a glyph with another. Here you have 3 glyphs being replaced by 1 symbol.

**Comment by okonet** [comment]
Since we have a dedicated symbol for it I don't feel the need for it especially for developers. 

Interesting question is why it's not reproducible for me on v1.600 on Mac neither in IDE nor on the website playground.

**Comment by okonet** [comment]
We decided to drop the _ligature_ but keep the symbol in the font.
