### ISSUE TITLE
"Normal" width version

### ISSUE THREAD

**Issue by bebraw** [MonoLisaFont/feedback#47]
From email:

> Yes, by tighter, I meant less wide. I wonder how a denser version would compare to other fonts like Fira Code. I guess this is more of a personal preference. It would be awesome if this ends up happening though!

The idea would be to provide a normal width version of MonoLisa. As far as I understand, that would mean redoing all characters, though, so the amount of work might be quite big.

**Comment by okonet** [comment]
But why? That's the main differential factor for it. If they don't like this they why using ML? But maybe Marcus can comment too?

**Comment by bebraw** [comment]
Yup, let's wait for a comment from Marcus.

I agree it's a differentiating factor so it would be tricky to remove without losing something of value.

**Comment by MarcusSterz** [comment]
Clear nope from me. I would have to make every update twice. Also, we agreed on the wider approach because of the obvious advantages.

**Comment by bebraw** [comment]
Ok, let's close. 👍
