### ISSUE TITLE
Provide a version without ligatures

### ISSUE THREAD

**Issue by bebraw** [MonoLisaFont/feedback#49]
To quote the user:

> I love MonoLisa but I don't like ligatures (both liga and calt). Is it possible to distribute a version of the font without them?
I know I can turn them off on some editors and terminals but this isn't possible with macOS' Terminal.app so it would be very nice to have a version that I can use. As far as I know PragmataPro Mono, Iosevka, and JetBrains Mono provides two versions of their fonts: with and without ligatures.

**Comment by okonet** [comment]
Do we know what exactly he doesn't like about them?

**Comment by bebraw** [comment]
> Do we know what exactly he doesn't like about them?

No. I asked for more info.

**Comment by bebraw** [comment]
Reply:

> The reasoning is that I don’t like/want ligatures (the same for calt). I feel kinda bad asking for this, in part because this should be a toggle on macOS Terminal to enable/disable them, but at the same time, as I said, other fonts provide a version without ligatures/calt for people who doesn’t want them.

> I just can’t use ligatures/calt. I want to see the glyphs in a “fixed” way, like a “normal” monospace font.

So it's about matching the behavior seen in the other fonts (maybe a sight issue?).

**Comment by okonet** [comment]
What is the effort on our end to do so?

**Comment by bebraw** [comment]
> What is the effort on our end to do so?

I think @MarcusSterz knows the best as he is building the font.

I tried setting up a standalone script but it's crashing on something within the source file and to figure that one out we would likely need Rainer as the error is rather cryptic.

**Comment by florianbuerger** [comment]
Just to chime in here, I would love to see a version without ligatures as well if this is still considered 😊 

I prefer having ligatures enabled in my main editor(s) and in Terminal but they make code reviews a bit harder. So I would love to be able to select a non ligature version various diff tools (and they usually don't provide the level of customization to select a specific font feature). I do the same for GitHub via custom CSS, luckily there I can disabled ligatures (`font-variant-ligatures: none !important;`)

**Comment by okonet** [comment]
@florianbuerger currently, we don't enable ligatures besides the one that improve the legibility (`calt`) by default.

So, by default, you should only see those "whitespace" ligatures enabled:

<img width="990" alt="CleanShot 2021-05-17 at 13 04 17@2x" src="https://user-images.githubusercontent.com/11071/118478625-66fabc00-b710-11eb-8b63-9d58e9ff040f.png">

Can you confirm that this isn't the case for you?

**Comment by okonet** [comment]
That being said, I think we should evaluate this option @bebraw

**Comment by florianbuerger** [comment]
Interesting. I am using [Tower](https://www.git-tower.com/mac) mostly, all ligatures seem to render (same as Terminal, Xcode, TextMate and all other applications that use native macOS text rendering)

![ScreenShot 2021-05-17 at 13 50 50](https://user-images.githubusercontent.com/119219/118483999-0458ee80-b717-11eb-94bd-6dc28c772b19.png)

I have the open type version 1.7 installed on macOS 11.3.1

<img width="620" alt="ScreenShot 2021-05-17 at 13 52 08" src="https://user-images.githubusercontent.com/119219/118484105-23578080-b717-11eb-9865-2e0a00f82d9d.png">

**Comment by bebraw** [comment]
@florianbuerger It's possible Tower uses the `liga` set by default as that would explain what you are seeing. Unfortunately many developer tools have poor support for special font features like stylistic sets.

It may be possible for us to change font generation workflow so that there would be a ligature free version available as well. That would sort of bypass the issue and I suppose in this case the ligature free font would have a different name. Maybe there's a convention to follow.

**Comment by aaronmbos** [comment]
Would love to see a ligature free version available for download as well. I use Visual Studio for most of my day to day development and there is unfortunately no option to disable ligatures.

**Comment by okonet** [comment]
We exploring options how to make customization possible. Stay tuned.

**Comment by okonet** [comment]
@jonathanbennett73 we provide two sets of ligatures: `calt` OpenType flag for whitespace adjustments i.e. no glyph changes but only positioning of them. For example for pairs like `{|`. `calt` is applied by default. 

The second set is under `liga` OpenType flag and is not enabled by default. This one changes some glyphs presentation. For example `!=` becomes `≠` etc. 

Could you please confirm that both sets are applied for you be default in the Visual Studio? Can you also post a screenshot maybe just so we are on the same page.

**Comment by jonathanbennett73** [comment]
Hi, yes both are enabled.  Screenshot attached

![MonoLisa](https://user-images.githubusercontent.com/14364181/156560500-67a3a380-0ea2-421f-90e4-4b1d11f4dd47.png)

**Comment by asahaf** [comment]
I would like to disable ligatures and have only "calt" enabled

**Comment by okonet** [comment]
We are working on make it possible. Stay tuned.
