### ISSUE TITLE
Sublime Text alignment

### ISSUE THREAD

**Issue by pstrum** [MonoLisaFont/feedback#5]
I'm noticing in Sublime that the font is aligned at the top of each line, which makes for an awkward, not centered look.

![image](https://user-images.githubusercontent.com/12450486/76386315-78cd1c00-6321-11ea-8a7a-45382ea8d8c3.png)

Is this an issue with Sublime or with MonoLisa? Thank you for your help.

**Comment by hsleewis** [comment]
Not ideal, but these settings help:
```
"line_padding_bottom": -1,
"line_padding_top": 4,
```

**Comment by bebraw** [comment]
@hsleewis I tried it and those settings look good. Let's wait for a bit more feedback and add to the FAQ eventually.

If you want a reference, check how it renders in VS Code.

**Comment by yalelo** [comment]
Hello,

I also noticed the same thing, not only on Sublime text, but also on some other editors like Gnatstudio (on Debian linux). Unfortunately, not all editors have the possibility to edit padding parameters.

**Comment by okonet** [comment]
Just a follow up: we are working on the fix for this one and we’ll release it soon.

**Comment by bebraw** [comment]
This has been fixed in 1.500 (available now).
