### ISSUE TITLE
Rust - .., .= and ..= ligatures don't fit together

### ISSUE THREAD

**Issue by bebraw** [MonoLisaFont/feedback#50]
To quote:

> One thing that annoys me are ligatures for ".=". There are two range operators in Rust: ".." for a right-exclusive range and "..=" for a right-inclusive range and when I use the latter dots are displayed vertically in the middle. Otherwise, it is awesome and no other fixes/improvements come to my mind right now.

**Comment by MarcusSterz** [comment]
@bebraw Can you help me with this one? Not sure what the user means by ‘dots are displayed vertically in the middle’.
We already have a double period ligature. On a scale from 1-10 how important is it to change it to match ‘..=’? 
Will this create a discrepancy somewhere else?

**Comment by bebraw** [comment]
@MarcusSterz That's a great point. Would it make sense to have a stylistic set specifically for Rust where we would override `..` with the non-ligature one? In this case we would have to identify which ligatures make most sense to enable for Rust specifically but we would have to figure out the exact set somehow. I think #1 is related and @mitsuhiko is probably the right person to comment on Rust support.

**Comment by bebraw** [comment]
There's a prerelease with a potential fix.

The core of the issue has to do with the combinations of `..`, `.=` and `..=` which feel like a group. The problem is that we don't understand the meaning of these in many languages so the issue needs more research.

**Comment by bebraw** [comment]
Included in 2.012. The exact ligatures added are +=, -=, *=, %=, &=, &^, and &^=.
