### ISSUE TITLE
Visual Studio 2019 - Ligatures don't work

### ISSUE THREAD

**Issue by bebraw** [MonoLisaFont/feedback#52]
Apparently this might be an issue on Visual Studio 2019 side based on https://developercommunity.visualstudio.com/idea/591741/font-ligatures-not-working.html and not something that can be fixed in the font itself.

If anyone is using Visual Studio 2019 and has experience with ligatures, please comment on this thread.

**Comment by fredericrous** [comment]
hey! the link you shared is about Visual Studio 2019 and not VS Code (current version is 1.52.1)

**Comment by bebraw** [comment]
Ah, good point. I had a typo - I meant Visual Studio in particular. It's a separate product from VS Code.

Ligatures work perfectly in VS Code but it's Visual Studio that's more problematic.

**Comment by bebraw** [comment]
As a workaround, you can use the font website to freeze certain font features to create a custom build. I think that's the best we can do for Visual Studio.

See https://twitter.com/monolisafont/status/1503709310915915781 for further info.

**Comment by okonet** [comment]
I have been testing with Visual Studio and ligatures are working just fine there. You can't disable them though. For that you can use the new feature and drop them from the build completely.
