### ISSUE TITLE
1.602 - Backticks render wrongly

### ISSUE THREAD

**Issue by bebraw** [MonoLisaFont/feedback#53]
> I encountered a problem with your font! When I'm using Backticks (`), there is a display error (I'm using the latest available version). I have attached the evidence below, I also tested this anomaly on your site, and it behaves on you as well. 

![image-1](https://user-images.githubusercontent.com/166921/106043974-685f9480-60df-11eb-8083-48d0a8bed80a.png)
![image-2](https://user-images.githubusercontent.com/166921/106043978-6990c180-60df-11eb-9cf6-1431ea3669a8.png)

**Comment by bebraw** [comment]
Based on the user report it's on MacOS but I cannot reproduce this one on my system (Big Sur). Please comment here if you can reproduce it.

**Comment by petrisoralexandru** [comment]
Hi, I'm the one who reported this. The problem is tested on the operating systems: macOS High Sierra & Windows 10 as well as on your website (Playground). 

I have attached some more animated images. 
![Proof1](https://user-images.githubusercontent.com/34144926/106047726-a4e5bd00-60ec-11eb-896b-f44079b2f5f0.gif)
![Proof2](https://user-images.githubusercontent.com/34144926/106047728-a57e5380-60ec-11eb-83fa-24214da4f922.gif)



Backticks (`) work correctly in italics. In the below photos, you can see it's a big difference in the glyph (left one is Regulat Italic, right one is just Regular).
![image](https://user-images.githubusercontent.com/34144926/106047691-99929180-60ec-11eb-8011-c36892def315.png)

**Comment by bebraw** [comment]
@MarcusSterz Is it possible there's some automatic replacement causing this? Can you reproduce the issue?

**Comment by bebraw** [comment]
Hi,

Just to verify, if you change the font in the playground, does it give the expected result (separate characters)? If not, that would imply some replacement on the system level.

**Comment by petrisoralexandru** [comment]
> Hi, Just to verify, if you change the font in the playground, does it give the expected result (separate characters)? If not, that would imply some replacement on the system level.
> […](#)
> On 27.01.2021, at 21:13, Ţandără Petrişor-Alexandru ***@***.***> wrote: ﻿ Hi, I'm the one who reported this. The problem is tested on the operating systems: macOS High Sierra & Windows 10 as well as on your website (Playground). I have attached some more animated images. Backticks (`) work correctly in italics. In the below photos, you can see it's a big difference in the glyph (left one is Regulat Italic, right one is just Regular). — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Did you mean to switch to MonoLisa to Fira Code/Jetbrains/Source Code?

**Comment by petrisoralexandru** [comment]
Sure!

![Proof3](https://user-images.githubusercontent.com/34144926/106060186-635d0e00-60fc-11eb-96d5-99ad8c5e13ed.gif)

**Comment by pkazmier** [comment]
For another data point, I'm on a Mac (Catalina) and backticks work as expected in both playground and my editor (emacs 28).

**Comment by petrisoralexandru** [comment]
I don't know, I think this is on a system level. I tested it on my Android phone and my laptop (Windows & Ubuntu) and the playground works well, but the same issue in VS Code.

**Comment by MarcusSterz** [comment]
Cannot reproduce this in playground in any browser so far. Looks good in VS Code, too.

**Comment by petrisoralexandru** [comment]
Maybe is from keyboard?

https://github.com/microsoft/vscode/issues/93567#issuecomment-663862573

**Comment by petrisoralexandru** [comment]
@bebraw What replacement on the system level do you recommend?

**Comment by bebraw** [comment]
@petrisoralexandru You could try https://stackoverflow.com/a/12759063/228885 . I wonder if this is related to input source.

If I'm interpreting right, it's doing a replacement for the diacritic character ù on your system. I don't understand why this doesn't happen for the other font families, though.

**Comment by petrisoralexandru** [comment]
Thanks, it will be great if you recommend some settings for Windows as well.

joi, 28 ian. 2021, 18:50 Juho Vepsäläinen <notifications@github.com> a
scris:

**Comment by bebraw** [comment]
@petrisoralexandru https://superuser.com/questions/1236768/how-do-i-disable-automatic-diacritics seems related for Windows. It looks like there may be some automation in place as well that's causing the behavior.

**Comment by petrisoralexandru** [comment]
@bebraw Today I needed to get on IntelliJ IDEA and I told myself to try if I can replicate the bug in this compiler as well. It seems that I don't have any problems here, I don't know if it's from OS or VSCode, in IntelliJ IDEA the rendering is done correctly.

**Comment by bebraw** [comment]
On my system, I'll have to do shift-backtick-space to make a standalone backtick (Finnish layout). Without the space, it's going to merge the accent to the following character. This seems like standard OS behavior to me. Screenshot below:

<img width="80" alt="Screen Shot 2021-01-29 at 20 48 41" src="https://user-images.githubusercontent.com/166921/106320596-60385e00-6273-11eb-89d1-ddf542bf2ce0.png">

Do you think this could be it?

**Comment by petrisoralexandru** [comment]
Yes, in Windows I have to do `+Space (instead of just press `) to render correctly, but if I want to delete, the problem appears again because of missing space.

**Comment by petrisoralexandru** [comment]
@bebraw @MarcusSterz How can we solve this problem? Do you know? If not, I could change the font and move the backticks from italic to regular, as I said, there are no problems with italics.

**Comment by bebraw** [comment]
@petrisoralexandru So far the problem is that we've been unable to reproduce it on our systems. There's some difference I don't understand yet.

**Comment by bebraw** [comment]
@petrisoralexandru Do you still have the issue? The problem is that nobody has been able to reproduce it so far making it difficult to troubleshoot and debug.

**Comment by Lyrillind** [comment]
Same problem here. It happens everywhere.

**Comment by bebraw** [comment]
@mekkablue How would you debug something like this? We're having trouble reproducing the backtick rendering issue here.

@Lyrillind Which system language do you use?

**Comment by Lyrillind** [comment]
> @Lyrillind Which system language do you use?

System language is Chinese.

**Comment by bebraw** [comment]
Can you see the issue when the system language is set to English?

**Comment by mekkablue** [comment]
We need to verify if the backtick is defined as combining mark or if it occurs in a ligature. Will have a look at this today.

**Comment by Lyrillind** [comment]
@bebraw Same problem under English

**Comment by mekkablue** [comment]
I cannot reproduce the issue in 1.604, it works as expected for me in this version, including on the web page:

![image](https://user-images.githubusercontent.com/1103103/114739059-d57edf80-9d48-11eb-912b-52a2bd00aaf9.png)

(tested in both Chrome and Safari on macOS X 10.15)

* Can you paste the character stream here between triple backticks?
* Which input methods are you using and which key sequence are you typing exactly?

**Comment by Lyrillind** [comment]
Confirmed this issue is fixed in 1.604 as followed screenshot.

<img width="216" alt="CleanShot 2021-04-15 11 14 09@2x" src="https://user-images.githubusercontent.com/4125903/114808918-cac15a80-9ddb-11eb-923d-5a4970fc2e48.png">

**Comment by MarcusSterz** [comment]
Great! 
Please make sure to have the latest version when reporting bugs.

**Comment by kkirsche** [comment]
I have this issue with 1.808 on macOS, will try again with 2.0.0 prerelease:

the following:
```

````this is an example```

```

Renders as:

<img width="268" alt="CleanShot 2022-08-04 at 13 29 37@2x" src="https://user-images.githubusercontent.com/947110/182913838-3fcfcfe9-a838-487c-9066-8c8a9144b240.png">

**Comment by kkirsche** [comment]
Tested, reproduced and isolated the issue I'm seeing:

1. Reproducible in VSCode 1.70.0 on macOS 12.5 with version 2.0 of the font.
2. Only reproducible when using a NERD font patched version of MonoLisa

Font related settings:
1. Font size: 12
2. Font Family: MonoLisa Nerd Font
3. Tab size: 4
4. `editor.fontLigatures: true`
5. `editor.fontWeight: "normal"`

**Comment by bebraw** [comment]
@kkirsche Are you using the variable version?

I am waiting for a fixed build for separate weights so it's better to use the variable one.

**Comment by kkirsche** [comment]
Yes I am using the variable version, which does not require installing as many .ttf files.

**Comment by bebraw** [comment]
@kkirsche Do you see the issue **only** with the patched version or with the "vanilla" version as well?

**Comment by bebraw** [comment]
> @kkirsche Do you see the issue only with the patched version or with the "vanilla" version as well?

Ah, you responded that already.

I think the problem here might be that we cannot guarantee the font to work with external modifications but I'll re-open the issue regardless.

**Comment by kkirsche** [comment]
I think that's fine but the way it's modified is coming from your issue tracker, which while a user-provided solution is still a likely course of action for many users given NERD icons were an early request in #57

**Comment by krish-r** [comment]
Hello, there's already an open [issue](https://github.com/ryanoasis/nerd-fonts/issues/858) and a [PR](https://github.com/ryanoasis/nerd-fonts/pull/860) with a fix in the nerd fonts repository for this backtick issue.

Until it gets merged, you can self-patch the font from the command-line using the options suggested in [this comment](https://github.com/ryanoasis/nerd-fonts/issues/858#issuecomment-1177439193) (& by following the instructions in [this comment](https://github.com/ryanoasis/nerd-fonts/discussions/847#discussioncomment-2984491)).

**Comment by krish-r** [comment]
> Hello, there's already an open [issue](https://github.com/ryanoasis/nerd-fonts/issues/858) and a [PR](https://github.com/ryanoasis/nerd-fonts/pull/860) with a fix in the nerd fonts repository for this backtick issue.
> 
> Until it gets merged, you can self-patch the font from the command-line using the options suggested in [this comment](https://github.com/ryanoasis/nerd-fonts/issues/858#issuecomment-1177439193) (& by following the instructions in [this comment](https://github.com/ryanoasis/nerd-fonts/discussions/847#discussioncomment-2984491)).

Its merged now. You can now patch the font using -
- the command-line approach mentioned in my previous reply until their next release (v2.2.0)
(or)
- their latest docker image

**Comment by Finii** [comment]
>  until their next release (v2.2.0)

There is a new release :tada: https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.2.0

;)

**Comment by bebraw** [comment]
I wonder what to do with this one. Given they've patched Nerd Fonts, should we simply close this issue?

**Comment by krish-r** [comment]
Hi, 

- If possible, when closing this issue, can you add a note in your FAQ advising users to use nerd fonts `>=v2.2.2` when patching the font manually.

- Alternatively, instead of patching MonoLisa, users can now install [`Symbols Nerd Font (mono)`](https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/NerdFontsSymbolsOnly.zip) from nerd fonts and use that as a fallback font if their terminal or application supports it.
  For Ex:
  - kitty terminal: Using `symbols_map` in `kitty.conf` as suggested in [kitty's FAQ](https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font)
    `symbol_map <Unicode codepoints> Symbols Nerd Font`

  - VS Code terminal: Using font fallback in `settings.json`
  `"terminal.integrated.fontFamily": "'MonoLisa', 'Symbols Nerd Font'"`

**Comment by bebraw** [comment]
@krish-r Great info, added.

I wonder if there's some way to "merge" another font with `Symbols Nerd Font` to generate a single file as that would provide another way to patch.

**Comment by Finii** [comment]
> I wonder if there's some way to "merge" another font with `Symbols Nerd Font` to generate a single file as that would provide another way to patch.

Well, that is the whole purpose of Nerd Fonts. To give users a patcher script that takes an arbitrary font and creates a patched version. For convenience Nerd Fonts also supplies some already patched versions of popular fonts.

https://github.com/ryanoasis/nerd-fonts#font-patcher

The `Symbols Nerd Font` was just a byproduct. It uses the same patcher script but an empty input font. It is for use cases where font substitution (by the OS's font system) is good enough.

(The 'problem' with merging is that you want to scale the symbols to somehow match the to-be-patched font.)

**Comment by bebraw** [comment]
> Well, that is the whole purpose of Nerd Fonts. To give users a patcher script that takes an arbitrary font and creates a patched version. For convenience Nerd Fonts also supplies some already patched versions of popular fonts.

Yup, what I found out is that it **doesn't** work against variable fonts, though, as some underlying dependency doesn't support this type of patching.

It's not exactly clear to me how to handle Nerd Fonts for the variable case but `Symbols Nerd Font` seems to address the problem.

> (The 'problem' with merging is that you want to scale the symbols to somehow match the to-be-patched font.)

That's a great point.

**Comment by bebraw** [comment]
For future reference or anyone that's interested, it seems the way to include Nerd Fonts to a variable font has been documented at https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Inconsolata/font-info.md#inconsolata . This works only if you have access to the original Glyphs file, however.

**Comment by Finii** [comment]
> It's not exactly clear to me how to handle Nerd Fonts for the variable case but `Symbols Nerd Font` seems to address the problem.

That is most probably just font fallback. The is handled transparently by the OS's font subsystem.

**Comment by bebraw** [comment]
I forgot to close this issue now that it has been documented at the FAQ. Thanks for the info.
