### ISSUE TITLE
Lowercase `i` looks like a `1`

### ISSUE THREAD

**Issue by karlhorky** [MonoLisaFont/feedback#54]
Hi @okonet and @bebraw ! 👋

First of all, thanks for your tireless work on MonoLisa! It's great to see this passion in the industry 🙌

So now that CodeSandbox is using MonoLisa as the default font, I see it on a lot of different monitors at a lot of different resolutions. 🎉

Very often it is on a cramped 13" MacBook screen over [Zoom](https://zoom.us/) remote screensharing (often from a monitor larger than mine, which exacerbates even further!).

One thing that always stands out to me is that I often think that students have mistakes in their code, because the lowercase `i` looks a lot like a `1` (one).

For example, take a look at this screenshot:

![Screen Shot 2021-01-27 at 17 45 39](https://user-images.githubusercontent.com/1935696/106196241-7da4f380-61b1-11eb-9d6d-f236ae872f8d.png)

On line 50, `transition` looks like `trans1t1on` and line 54 seems like `.l1ne::before`

I see that it was one of the feedback points on https://github.com/MonoLisaFont/feedback/issues/38, but maybe separately highlighting this one point would be useful.

**Comment by bebraw** [comment]
@MarcusSterz Can you check this one again? In the online service above, it's using the newest fix but it looks like it's not enough in all cases. I wonder if there's any more that could be done.

**Comment by MarcusSterz** [comment]
Looking at the ‘f’ I bet that this is not 1.602 🧐

**Comment by MarcusSterz** [comment]
@karlhorky Are you certain, this is 1.602?
We improved the terminal of f, too. It should look different in the current version. But then it’s a screen shot so it’s hard to tell.

**Comment by karlhorky** [comment]
I don't know - I tried getting the person to look in the Network panel, but there was no version information there. How do I find out?

**Comment by karlhorky** [comment]
One additional piece of info here is that the person on the other end is on Windows, in case that makes a difference.

**Comment by bebraw** [comment]
The version on Codesandbox has only your i/1 fix as the f fix was implemented after it.

**Comment by MarcusSterz** [comment]
> I don't know - I tried getting the person on the other end to look in the Network panel, but there was no version information there - only the year "2020" (this was in the CSS file).
> 
> How do I find out?

Can you could magnify the font up to i e 20 or bigger and make a screenshot of the ’f‘? Then I can tell.

**Comment by MarcusSterz** [comment]
> The version on Codesandbox has only your i/1 fix as the f fix was implemented after it.
> […](#)

True. 1.602 is 2021 already.

**Comment by bebraw** [comment]
It's not possible to tell based on f alone as that wasn't included to the early test version with the i/1 fix provided to Codesandbox.

Here the problem is made worse by a combination of Windows, low resolution, and poor connection.

**Comment by MarcusSterz** [comment]
So codesandbox is not using our cutting edge latest version?

**Comment by bebraw** [comment]
Just a sidenote, it looks like Nokia Font solved the issue by having lower angle at the "1" top. It was designed with extremely low resolutions in mind.

Maybe that and adding a tiny bit more spacing to "i" would help in telling them apart in extreme cases?

**Comment by bebraw** [comment]
Codesandbox is using the version with your fix as the fix was made for them but it doesn't have the new f.

**Comment by MarcusSterz** [comment]
> Codesandbox is using the version with your fix as the fix was made for them but it doesn't have the new f.
> […](#)

That’s  awkward, isn’t it?

**Comment by bebraw** [comment]
Pushing the new f wouldn't solve the issue with i/1.

It takes engineering effort to test/validate a new version on their side. Just let me know when to do it.

**Comment by MarcusSterz** [comment]
> Pushing the new f wouldn't solve the issue with i/1. It takes engineering effort to test/validate a new version on their side. Just let me know when to do it.
> […](#)

What do you mean?

**Comment by bebraw** [comment]
Asking them to update to 1.602 would not fix the problem we are seeing here since the version we provided to Codesandbox already contains your i/1 fix. As it's there already, it would not change the situation when it comes to this issue.

**Comment by bebraw** [comment]
@karlhorky Can you ask the person using Zoom if the i and 1 look good locally? If that's the case, I suspect it might be Zoom that's decreasing the quality here since there's some compression on the stream. It's still something to fix but this information would help to narrow down **when** the problem occurs.

**Comment by karlhorky** [comment]
Sure, will ask :) Maybe we'll get a screenshot too.

**Comment by karlhorky** [comment]
Ok, so the answer is: it's still pretty bad, without Zoom.

Here's a screenshot:

![image](https://user-images.githubusercontent.com/1935696/106289884-171fe400-624a-11eb-83f0-fffb54beb759.png)

Again, in case this is relevant, this is on a Windows 10 machine.

**Comment by bebraw** [comment]
@karlhorky Can you get the system display resolution so we can validate locally?

**Comment by okonet** [comment]
@karlhorky can that person go to https://www.monolisa.dev/playground and try it there so we can at least be sure about the font version?

**Comment by karlhorky** [comment]
cc @Josehower

**Comment by Josehower** [comment]
Hi, on the playground is looking a lot better

windows 10

![image](https://user-images.githubusercontent.com/61600906/106300152-666c1180-6256-11eb-96da-97313503e1cc.png)

**Comment by bebraw** [comment]
Thanks for the info.

I think I may have found the root of the issue. It seems after our fix for the "i", something changed in Codesandbox deployment and they reverted to an earlier version. I explain more at https://github.com/codesandbox/codesandbox-client/pull/5337#issuecomment-769928678 .

**Comment by bebraw** [comment]
@Josehower We traced it down to service worker caching at https://github.com/codesandbox/codesandbox-client/pull/5337 . That would explain the difference. You can try to verify this by using another browser (Firefox for example) or by removing entire service worker for Codesandbox in Chrome through dev tools.

**Comment by MarcusSterz** [comment]
> Thanks for the info.
> 
> I think I may have found the root of the issue. It seems after our fix for the "i", something changed in Codesandbox deployment and they reverted to an earlier version. I explain more at [codesandbox/codesandbox-client#5337 (comment)](https://github.com/codesandbox/codesandbox-client/pull/5337#issuecomment-769928678) .

Great job @bebraw !

**Comment by karlhorky** [comment]
Great! @Josehower if you confirm that it looks fine after removing the service worker from the Application tab of the DevTools, I will close :)

**Comment by bebraw** [comment]
Hi,

It's a bit more complex than that. It seems Codesandbox is using Cloudflare with long cache times (my font file was from mid-December). I am currently discussing what to do about that. Hopefully I know more next week.

**Comment by bebraw** [comment]
I've opened a follow-up issue on Codesandbox side at https://github.com/codesandbox/codesandbox-client/issues/5444 about the caching problem.

It's best to follow that as there's nothing we can do on the font side.

**Comment by karlhorky** [comment]
Thanks for following up here @bebraw , will continue watching over there!
