### ISSUE TITLE
Dot position above ‘i’ and ‘j’

### ISSUE THREAD

**Issue by pkazmier** [MonoLisaFont/feedback#55]
Does anyone else feel the dot above the ‘i’ and ‘j’ could be slightly shifted to the left to provide a more visual balance? Because the dot is wider than the stem, when centered over it as it is now, it looks out of place.

I’ve never noticed such a small detail before in any font, but it just stands out at the size I use MonoLisa. So, I went and checked a few other fonts I use to see if purposely not centering the dot is common. It seems like several others shift the dots left. Here are some examples:

Monolisa
![IMG_0334](https://user-images.githubusercontent.com/747855/106232863-b09fb500-61ba-11eb-8315-37d4ec512bb6.jpeg)

Source code pro
![IMG_0329](https://user-images.githubusercontent.com/747855/106232726-4f77e180-61ba-11eb-96bf-ae331c8f8ab3.jpeg)

Fira code
![IMG_0333](https://user-images.githubusercontent.com/747855/106232984-0b391100-61bb-11eb-8244-094a082c3220.jpeg)

Jet Brains mono
![IMG_0335](https://user-images.githubusercontent.com/747855/106233178-813d7800-61bb-11eb-8198-1a81b092666a.jpeg)

What do you think?

**Comment by bebraw** [comment]
@MarcusSterz What do you think? Maybe it's good to tune this while doing the general i/j fix for extremely low resolutions?

**Comment by MarcusSterz** [comment]
> doing the general i/j fix for extremely low resolutions?

We did exactly that in 1.602

**Comment by okonet** [comment]
@MarcusSterz can you please make a comparison of 1.601 and 1.602 with similar zoom levels?

**Comment by pkazmier** [comment]
The Monolisa screenshot came from the website, but maybe my browser has a cached version of the font? Here is another screenshot straight from my Font Book app on the Mac where I installed 1.602. It still looks like the dot is centered over the stem:

<img width="360" alt="image" src="https://user-images.githubusercontent.com/747855/106279265-c1bfe480-6201-11eb-80c6-f964bdecc502.png">


And the info display for the font showing 1.602 has been installed if it helps:

<img width="571" alt="image" src="https://user-images.githubusercontent.com/747855/106279357-ea47de80-6201-11eb-8849-a84a3e0344dc.png">

Thanks for your consideration. This is a lovely font and I'm really enjoying it as my main driver these days.

**Comment by MarcusSterz** [comment]
This issue has been taken care of and you will see improvement in upcoming v1.603.
