### ISSUE TITLE
Support Bash specific ligatures

### ISSUE THREAD

**Issue by bebraw** [MonoLisaFont/feedback#58]
- bash process substitution -> https://www.gnu.org/software/bash/manual/html_node/Process-Substitution.html
- bash command substitution -> https://www.gnu.org/software/bash/manual/html_node/Command-Substitution.html
- bash redirections -> https://www.gnu.org/software/bash/manual/html_node/Redirections.html

Please 👍 this issue if you would like to see these in the font family.

**Comment by okonet** [comment]
What kind of ligatures do you have in mind?

**Comment by bebraw** [comment]
Looking at the links sent by the user:

* <(
* >(
* $(
* >&
* &>
* &>>
* <&
* <>
* <<
* >&-
* <&-
* &>> (not as important as the others are more common?)

I think some of these exist already and it's possible I didn't catch them all (if someone uses Bash, please comment in the thread).

**Comment by fredericrous** [comment]
That's the list @bebraw 👍 

The most common operators are, without a doubt, output redirection and command substitution:

```bash
&>
>&
$(
```

I often use these as well:

```
<<
<(
```

the others are less common, IMO.

I think only these ones are already implemented

```bash
* <>
* <<
```

**Comment by MarcusSterz** [comment]
> Looking at the links sent by the user:
> 
> ```
> * <(
> * >(
> * $(
> * >&
> * &>
> * &>>
> * <&
> * <>
> * <<
> * >&-
> * <&-
> * &>>
> ```
> 
> I think some of these exist already and it's possible I didn't catch them all (if someone uses Bash, please comment in the thread).

Would we make them LIGA or CALT?

**Comment by bebraw** [comment]
@MarcusSterz I think the basic rule is that if it's only spacing alterations, it should go to `calt` but if entire characters are replaced then `liga`. Most likely this has to be decided per case.

**Comment by MarcusSterz** [comment]
> @MarcusSterz I think the basic rule is that if it's only spacing alterations, it should go to `calt` but if entire characters are replaced then `liga`. Most likely this has to be decided per case.

Some are definite candidates for `liga`.

**Comment by MarcusSterz** [comment]
@bebraw @okonet Can you have a look? I have now created the listed ligs. Some combinations clearly can be `liga`, while most would be `calt`.
<img width="560" alt="Bildschirmfoto 2021-07-20 um 15 01 43" src="https://user-images.githubusercontent.com/51958720/126329910-10427077-424c-4b8d-9a4e-f72d897bc071.png">

**Comment by okonet** [comment]
Since I don't really have an opinion on that topic, I'd suggest to ask @fredericrous instead.

**Comment by bebraw** [comment]
Implemented in 1.802.
