### ISSUE TITLE
rendering issues on Linux: letters have thick areas

### ISSUE THREAD

**Issue by danielbartsch** [MonoLisaFont/feedback#6]
Seen in https://monolisa.dev/ Playground

![image](https://user-images.githubusercontent.com/19350749/76400738-160b6d00-6381-11ea-98ed-b8ceadb6a77e.png)

![image](https://user-images.githubusercontent.com/19350749/76400421-9087bd00-6380-11ea-83c9-5c8e7e84727b.png)

You can see some thick areas in the letters:
normal: `i`, `j`, `r`, `t`, `z`
italics: same as above, `r` is a little less prevalent

**Comment by okonet** [comment]
Can you please provide details about OS version and browser used?

**Comment by danielbartsch** [comment]
```
⫸ uname -a
Linux A-N-W-054 5.0.0-38-generic #41-Ubuntu SMP Tue Dec 3 00:27:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
I'm using [Vivaldi](https://vivaldi.com/) which uses chromium version 76 in my current installation.

**Comment by okonet** [comment]
Thanks for the report. We're investigating this hinting issue ATM.

**Comment by georggrubner** [comment]
same for me too

browser zoom 100%
![image](https://user-images.githubusercontent.com/24992489/76431014-4e2aa400-63b1-11ea-87b3-98c5032a6103.png)

browser zoom 500%
![image](https://user-images.githubusercontent.com/24992489/76431174-8b8f3180-63b1-11ea-92d9-62af9d8b7422.png)

`Linux A-N-W-055 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
`
using Chrome `Version 80.0.3987.132 (Official Build) (64-bit)`

**Comment by bkircher** [comment]
Same here for Fedora 31, Firefox 74.0
Font rendering on Linux is, um, dissatisfactory.
80% Zoom:
![ml-1](https://user-images.githubusercontent.com/536464/76696720-c41f5b80-668e-11ea-8f48-a0026f1e20c0.png)

![ml-2](https://user-images.githubusercontent.com/536464/76696748-ee711900-668e-11ea-9cfb-edf255271d17.png)

Higher zoom levels look way better. Screen resolution 3840x2160. Antialiasing is standard (grayscale) with slight hinting.

**Comment by MarcusSterz** [comment]
@bebraw can you please add Rainer to this conversation?

**Comment by bebraw** [comment]
cc @mekkablue. It would be good to check if this is something related to Glyphs export. I imagine if there's something wrong with export, we should see it in other fonts created with Glyphs as well.

**Comment by mekkablue** [comment]
The problem was the bottom zone for superscript figures. The Regular’s horizontal stems at the x-height touched it and were aligned with the raised figures. Only solution was to remove it.

Other updates for better rendering:
* blueFuzz (zone extension) fixed at 1 unit
* reduced V and H standard stems to one each (there were two in each, very close together)

![Screenshot 2020-03-23 at 11 22 32](https://user-images.githubusercontent.com/1103103/77306907-9f635d80-6cf8-11ea-9eca-33f91e990ed1.png)

**Comment by mekkablue** [comment]
Version 1.303 fixes this. You can close the issue.

**Comment by bebraw** [comment]
@danielbartsch @georggrubner @bkircher Can you please check https://monolisa-website-git-feat-1303.monolisa.now.sh/ and confirm the font renders correctly now?

**Comment by bebraw** [comment]
I managed to confirm it renders well. Pushing release in a short while.

**Comment by bebraw** [comment]
I've pushed `1.303` to Paddle.

Please let us know if you encounter any further rendering issues.

**Comment by georggrubner** [comment]
> https://monolisa-website-git-feat-1303.monolisa.now.sh/ 

looks good there :tada:
