### ISSUE TITLE
Add a section in the FAQ regarding TextMate keywords configuration

### ISSUE THREAD

**Issue by fredericrous** [MonoLisaFont/feedback#60]
Hey, here is a suggestion for the FAQ page

OS: MacOS Big Sur 11.2
Editor: VS Code 1.52.1

If I navigate to the monolisa.dev website, I see the following on the Javascript page

<img width="500" src="https://user-images.githubusercontent.com/702227/107059302-8b6c0180-67cd-11eb-83d7-5d246fb9ff4d.png">

the keywords `import, export, if, for, const, return, undefined` are in italic.

My VS Code configuration is:

```json
{
    "editor.fontFamily": "MonoLisa, Apple Braille",
    "editor.lineHeight": 0,
    "editor.fontLigatures": true
}
```

My font size is set to 12

I put Braille in the example to see the difference easily if it gets loaded instead of MonoLisa (MonoLisa gets loaded)

I copy-paste the example from the website and I get the bellow:

<img width="500" src="https://user-images.githubusercontent.com/702227/107059243-78593180-67cd-11eb-8241-a03d76517e40.png">

Being a long time user of TextMate, then Sublime Text, I should have known better but It took me a while to understand why the keywords were different between what I saw online and what I was seeing in VS Code. On Sublime "function", and "var" are in italic, but nothing else by default.

To get the same rendering as on the website, I had to configure TextMate rules on VS Code like so: https://github.com/wesbos/cobalt2-vscode/issues/116 

For the keywords not configured by the list shared in the issue, like `undefined` and `var`, I used the VS Code devtool [Inspect Editor Tokens and Scopes](https://code.visualstudio.com/blogs/2017/02/08/syntax-highlighting-optimizations#_new-textmate-scope-inspector-widget) to find these 2 tokens:

```
                  "constant.language.undefined.js",
                  "storage.type.js",
```

Here is the result:

<img width="500" src="https://user-images.githubusercontent.com/702227/107065445-b148d480-67d4-11eb-8ffe-2f8176c1623c.png">

It could be cool if the FAQ would suggest a minimal configuration recommended that reproduces the example on the website?

**Comment by okonet** [comment]
We could add this but isn't it related to the theme you're using?

**Comment by fredericrous** [comment]
I honestly don't know, I use the default theme, "Default Dark+"

**Comment by fredericrous** [comment]
On IntelliJ Idea, the configuration is done per theme however, I'm putting the screenshot here for reference

![image](https://user-images.githubusercontent.com/702227/107079655-0d692400-67e8-11eb-8198-648ca74e5230.png)

**Comment by bebraw** [comment]
It's covered in the FAQ well enough now. Thanks for the issue.
