### ISSUE TITLE
Website Playground - Fira Code

### ISSUE THREAD

**Issue by jaacko-torus** [MonoLisaFont/feedback#61]
I know this is about another font, but since you're trying to allow us to see the differences between the fonts, then I suggest updating all the fonts you include in the playground. For example Fira Code (my daily driver) has updated to 5.2 last year, with it come a lot of updates and adjustments, but I don't know if I should buy MonoLisa (for $60) because I can't compare them fairly.

Again, sorry for talking about the competition, I just hope you get the website updated, and I didn't offend anyone. Cheers :D

**Comment by okonet** [comment]
We are using latest versions of all fonts provided to us by Google Fonts. If they don't have an updated version I suggest to send the inquiry there.

**Comment by bebraw** [comment]
Yup, as we depend on Google Fonts CDN, it's best if you can re-open the issue there so their consumers get the newest version: https://github.com/google/fonts . Thanks!
