### ISSUE TITLE
Regular font doesn't support Powerline

### ISSUE THREAD

**Issue by dongheeleeme** [MonoLisaFont/feedback#62]
I'm using MonoLisa with Regular on Vim. But I got a problem displaying Powerline font.
As a result of m tests, `Regular Italic`, `Bold` and `Bold Italic` doesn't have a problem displaying Powerline font.
Would you please check it? Thank you!

### Screenshot
![Screenshot 2021-02-08 at 19 31 55](https://user-images.githubusercontent.com/38916112/107265421-882e7b00-6a44-11eb-941f-93f195ef7914.png)

**Comment by okonet** [comment]
What version of the font you're using?

**Comment by dongheeleeme** [comment]
Hi @okonet, I'm using the latest version.

**Comment by okonet** [comment]
Just to confirm: `1.602` right?

**Comment by dongheeleeme** [comment]
Hi @okonet, I tried to reinstall the font, and then the issue was fixed so far.
(I don't know why it was fixed 😅 )
Thank you for your reply and I'll create an issue again if I get an issue again.

**Comment by bebraw** [comment]
Cool, let's close. Feel free to open a new issue if you encounter the glitch again. 👍

**Comment by dongheeleeme** [comment]
Hi @bebraw, I need your favor. Could you please delete this issue?
