### ISSUE TITLE
Support Korean language

### ISSUE THREAD

**Issue by dongheeleeme** [MonoLisaFont/feedback#63]
Hi team,

Thank you for the great font ever but have one request.
It would be great if this font supports Korean. Would you please consider this?

Thanks!

**Comment by mayaul** [comment]
I am also looking forward to Korean language support soon.

**Comment by MarcusSterz** [comment]
I am keen to look into that more deeply.

**Comment by MarcusSterz** [comment]
@okonet @bebraw I reached out for a feriend who is south korean. What would out budget be for that?

**Comment by bebraw** [comment]
@MarcusSterz If I understood correctly, it's about 40 characters to cover and italic for each I imagine. Then there's some amount of effort per character. It's difficult to give an exact figure but that's the starting point at least for some kind of hour estimate.

**Comment by MarcusSterz** [comment]
@bebraw I do not know enough but it is a bit more complicated:
https://glyphsapp.com/learn/creating-a-hangeul-font

**Comment by mayaul** [comment]
hello. I purchased last night.
I used for a few days the trial version.
I think this font is good, for developer.

I expect korean support.
thank you.

**Comment by dongheeleeme** [comment]
Hi team, I'll close this issue since it doesn't look a high priority so far, but supporting Korean is required huge efforts. Thanks for your reply!

**Comment by bebraw** [comment]
@dongheeleeme No worries, let me know if you find a good fallback font and I'll add it to the documentation.
