### ISSUE TITLE
FAQ update for Cyrillic languages

### ISSUE THREAD

**Issue by app** [MonoLisaFont/feedback#64]
Nice shaped font!
Do not found Russian among supported languages looking at FAQ page.
But found in releases page.  
Thanks!

**Comment by okonet** [comment]
Oh that's embarrassing 😳 Thanks for mentioning this. I'll add this to FAQ.

**Comment by okonet** [comment]
@MarcusSterz fyi

**Comment by MarcusSterz** [comment]
Oops 😬
