### ISSUE TITLE
Wider dash for em and em dashes?

### ISSUE THREAD

**Issue by bebraw** [MonoLisaFont/feedback#65]
> One thing that might be interesting to add would be support for using a wider dash for em and en dashes, like the iA Writer fonts (although, looking at the article about their fonts, it sounds like they might be proportional but designed so most characters look monospaced).  Probably I could get the same effect using ligatures, depending on the application I’m working in.

**Comment by cmconnelly** [comment]
(This is one I asked about by e-mail.)

**Comment by bebraw** [comment]
I just had a chat with our designer about this and it's something we cannot fix as em dash is already at its maximum width. :)
