### ISSUE TITLE
More Unique Parentheses?

### ISSUE THREAD

**Issue by carlomunguia** [MonoLisaFont/feedback#66]
Absolutely smitten with Monolisa, and have been using it on every IDE / console that I use for work & personal use. 

One thing I do note though, is that the parentheses are a bit flat on top/bottom of each glyph & a bit vague/ non-unique compared to other monospace fonts - compare for example [Monaco](https://www.cufonfonts.com/font/monaco) or [Mononoki](https://madmalik.github.io/mononoki/)

I'm not saying Monolisa has to obey that style, but a bit more unique parentheses that stand out for the programmer would be excellent. 

Otherwise - keep killing it! Monolisa is _awesome!_

**Comment by bebraw** [comment]
Starting from 1.700, { and } have been redone. Let us know what you think. 👍

**Comment by bebraw** [comment]
Let's close as this has been done.
