### ISSUE TITLE
condensed style

### ISSUE THREAD

**Issue by imjma** [MonoLisaFont/feedback#67]
Would like to have a condensed style to save space on each line.

**Comment by bebraw** [comment]
We discussed this in #47 as there was an earlier request.

Extra width is considered a **feature** as it allows our font designer to put extra effort into wide characters such as "m". Doing a condensed ("normal width") version of MonoLisa would require a full redesign and I believe the other popular font families cover that niche well enough.

I use MonoLisa for my editors (legibility matters) and I've been experimenting with Fira Code for my terminals lately as it's more narrow and there winning space makes sense even if you sacrifice a bit of legibility.
