### ISSUE TITLE
A ligature request for |=

### ISSUE THREAD

**Issue by vikky49** [MonoLisaFont/feedback#68]
A ligature request for |=

This is how it looks in MonoLisa
<img width="524" alt="1" src="https://user-images.githubusercontent.com/180512/108895169-1a4b8d00-75c8-11eb-81d3-ad7832bf573d.png">

This is how it looks in Jetbrains Mono
<img width="542" alt="2" src="https://user-images.githubusercontent.com/180512/108895259-35b69800-75c8-11eb-8549-05efca97917e.png">

**Comment by okonet** [comment]
I guess we could also add `|->` as well. It looks much better in JBM.

**Comment by bebraw** [comment]
The two ligatures have been added in 1.700.

**Comment by Eldair** [comment]
Hello,

@bebraw 
I think `|=` should be removed when preceded by `|` (there is `||=` assignment in JS which looks bad with aforementioned ligature).

**Comment by bebraw** [comment]
@Eldair Can you open a separate issue with a couple of screenshots? Thanks!
