### ISSUE TITLE
^ and ~ are hard to distinguish

### ISSUE THREAD

**Issue by sapegin** [MonoLisaFont/feedback#7]
It's hard to distinguish `^` and `~` in the code:

![image](https://user-images.githubusercontent.com/70067/76421056-61367780-63a3-11ea-970a-b2e8ce7167f1.png)

For comparison, in Hack they are bigger and the shape is more distinguishable:

![image](https://user-images.githubusercontent.com/70067/76421199-9b077e00-63a3-11ea-8c1e-aeeedea8f510.png)

Screenshots are from WebStorm on macOS Catalina.

**Comment by bebraw** [comment]
This should be resolved in 1.6 (please use the original download link). Closing.
