### ISSUE TITLE
Brackets aren't centered as in JetBrains Mono

### ISSUE THREAD

**Issue by bebraw** [MonoLisaFont/feedback#71]
This was raised up by a user. Examples below:

**MonoLisa:**

<img width="348" alt="Screenshot 2021-03-22 at 11 08 18" src="https://user-images.githubusercontent.com/166921/111966316-13486980-8af7-11eb-8c31-09980b28df89.png">

**JetBrains Mono:**

<img width="331" alt="Screenshot 2021-03-22 at 11 08 57" src="https://user-images.githubusercontent.com/166921/111966342-193e4a80-8af7-11eb-9b64-5a79b59272a4.png">

Note the alignment of the brackets against the characters. JetBrains Mono feels more balanced and aesthetic there.

**Comment by bebraw** [comment]
The feature has been already implemented in the typeface but you have to enable it separately like this (VS Code):

<img width="286" alt="Screen Shot 2021-04-08 at 10 43 03" src="https://user-images.githubusercontent.com/166921/113987693-5e80ad00-9857-11eb-83c6-c759641ac119.png">

Enabling the feature will change the orientation of the following characters:

```
colon.case
exclamdown.case
questiondown.case
asterisk.case
parenleft.case
parenright.case
braceleft.case
braceright.case
bracketleft.case
bracketright.case
```

**Comment by okonet** [comment]
@MarcusSterz i think we should have the default behavior swapped too.

**Comment by MarcusSterz** [comment]
> @MarcusSterz i think we should have the default behavior swapped too.

Not sure what you mean – can you elaborate

**Comment by okonet** [comment]
I mean that brackets etc should be aligned like in JetBrains Mono by default

**Comment by MarcusSterz** [comment]
They are already aligned to the upper case letters as we agreed. Still not sure what you mean.

**Comment by okonet** [comment]
> They are already aligned to the upper case letters

They are not:

![CleanShot 2021-06-29 at 09 15 51@2x](https://user-images.githubusercontent.com/11071/123754016-b826cf80-d8ba-11eb-9ad7-b496a5f3d7e2.png)
