### ISSUE TITLE
Hard to differentiate ligature between == and !=

### ISSUE THREAD

**Issue by wip0** [MonoLisaFont/feedback#72]
Hi,

I have attached the image from my IDE in C#
![2564-04-10_15h24_43](https://user-images.githubusercontent.com/20312631/114263655-22914780-9a11-11eb-88ec-b5966c968b5c.png)

Please make "!=" be easier to read. It is hard for me to tell that they are "==" or "!="

IDE: Visual Studio 2017
Font size: 10
OS: Windows 7

**Comment by dinhquochan** [comment]
I think you should use a bigger font size. Below is in Sublime Text 4 at 13px.

![image](https://user-images.githubusercontent.com/9979458/114648189-9d57ac80-9d08-11eb-824b-a54537c2d769.png)

**Comment by bebraw** [comment]
@wip0 Make sure to download the most recent release (1.700). Rendering was changed there and I believe it might help in your use case. If you check, let me know how it goes.

**Comment by bebraw** [comment]
This has been solved in 1.800. You can use the same download link to access it.
