### ISSUE TITLE
MonoLisa at Macbook M1

### ISSUE THREAD

**Issue by calebeaires** [MonoLisaFont/feedback#76]
Hey! I have set up MonoLisa at Macbook M1 and while using Intellij apps the font does work well as expected. **The font is too thin, more than expected**. I have to change the settings randomly to take the correct behavior, but I had no success.

Version
MonoLisa Plus 1.7

This print is from a Macbook M1

![image](https://user-images.githubusercontent.com/794195/115239933-a1fbd680-a0f5-11eb-91eb-d26aabfbddce.png)

This other is from a Macbook Intel

![image](https://user-images.githubusercontent.com/794195/115240267-f1da9d80-a0f5-11eb-8f45-00e0c6b059dd.png)

**Comment by okonet** [comment]
Can you please make suer you're installing _only_ the OTF version of the font? The first M1 screenshot looks completely wrong to me.

**Comment by bebraw** [comment]
@calebeaires Can you confirm that you are using the OTF version of the font? That's the optimal version for MacOS. TTF is something for Windows only and using that leads on MacOS to subpar rendering as far as I understand.

**Comment by bebraw** [comment]
Let's close as there was no response. Please re-open if you can still see the issue with OTF on M1.

**Comment by Sacro** [comment]
Are OTFs still a thing? If not then could we update this so that people like myself aren't looking for them!

**Comment by bebraw** [comment]
No, OTFs were dropped with version 2 as TTFs are enough for Mac as well.
