### ISSUE TITLE
unwanted ligature in handlebars files 

### ISSUE THREAD

**Issue by fredericrous** [MonoLisaFont/feedback#78]
I have been working with emberjs recently. It uses handlebars templating (file extension: `.hbs`).
`{{` and `}}` are used to delimit a handlebars statement.
At the end of a statement we can use the `as |something|`. In the example below, I use the [each](https://handlebarsjs.com/guide/builtin-helpers.html#each) keyword to define a loop, its iterator variable is defined with `as | ... |` . Closing the statement with `}}` results in a ligature being made at a place I'm not expecting to see 

![image](https://user-images.githubusercontent.com/702227/115691521-0c12b680-a356-11eb-949a-9f5c29ea9dde.png)

**Comment by bebraw** [comment]
I can see three ways to solve this one:

1. Define a ligature for `|}}` (doesn't feel right)
2. Push `|}` within a stylistic set so it can be optionally enabled
3. Drop the `|}` ligature (what's the use case for this?)

**Comment by bebraw** [comment]
We discussed this and we'll make sure that we use the same form for all the brackets and also align them even when ligatures are used so combinations like `|}}` look visually better.

**Comment by bebraw** [comment]
Ok, done (building atm). Closing.
