### ISSUE TITLE
"Thousand separator on Windows fixed width True Type Font" - issue

### ISSUE THREAD

**Issue by mWaltari** [MonoLisaFont/feedback#80]
Default float Format : "12 345 678,99"
DateSeparator        : "."
DecimalSeparator     : ","
ThousandSeparator    : " "

![2021-05-06_11h17_01](https://user-images.githubusercontent.com/4082975/117266044-831f7300-ae5d-11eb-923e-499d4858f104.png)

Tested with two unrelated editor in which I use MonoLisa in.

**Comment by okonet** [comment]
We would need steps to reproduce this in order to investigate. What editors and what part of the editor are you referring to?

**Comment by mWaltari** [comment]
Delphi IDE and https://texteditor.pro/

Interestingly enough Notepad with MonoLisa works OK. Hmmm... Have to also report this tpo TestEditorPRo programmer. Have no other text editor available with now.,

**Comment by okonet** [comment]
We have tested in WebStorm on windows without any issues. Maybe try it too just to confirm?

**Comment by mWaltari** [comment]
I tested this with few older versions of MonoLisa, and it did not help. I am pretty sure that I saw those working on TextEditorPro earlier. 

So this most likely is not MonoLisa problem after all. I'll get back to this later when I've got more info.

**Comment by mWaltari** [comment]
Not and thousand separator after all, sorry 'bout that.

It seems to be "NO-BREAK SPACE"
https://www.fileformat.info/info/unicode/char/00a0/index.htm

And Seems that MonoLisa has no "character" for that and some editors Circumvent that. Is that standard behavioir or coudl you add the NO-BREAK SPACE in it.

What you suggest if I report that for the software developers. Also if I am correct that the "character" is missing from MonoLisa, if you could add it, and also give some hint how those apps should handle that character missing in from the font.

I am not 100% sure any of this tough. Added UTF16-LE encoded text file here also, so easier to check and no conversions by copy paste etc.


[UnicodeTest.txt](https://github.com/MonoLisaFont/feedback/files/6439035/UnicodeTest.txt)

**Comment by okonet** [comment]
Yes, let us take a look. We'll definitively would add it to MonoLisa. Sounds to me like a bug.

**Comment by okonet** [comment]
@MarcusSterz could you please check it out?

**Comment by MarcusSterz** [comment]
Yup, will do!

**Comment by MarcusSterz** [comment]
Not sure what the problem is here. All needed glyphs are within MonoLisa. There are no special glyphs for that purpose that would be missing. More info here:

https://en.wikipedia.org/wiki/Decimal_separator#Unicode_characters

Unicode characters

Used with Western Arabic numerals (0123456789):

    U+0020   SPACE (HTML &#32;)
    U+0027 ' APOSTROPHE (HTML &#39; · &apos;)
    U+002C , COMMA (HTML &#44; · &comma;)
    U+002E . FULL STOP (HTML &#46; · &period;) - Full stop punctuation mark.
    U+00B7 · MIDDLE DOT (HTML &#183; · &middot;, &CenterDot;, &centerdot;)
    U+2009   THIN SPACE (HTML &#8201; · &thinsp;, &ThinSpace;)
    U+202F   NARROW NO-BREAK SPACE (HTML &#8239;)
    U+02D9 ˙ DOT ABOVE (HTML &#729; · &DiacriticalDot;, &dot;)

**Comment by MarcusSterz** [comment]
We could add the last one but I am not sure that is what you are looking for.

**Comment by okonet** [comment]
I understand the problem is that we’re missing `NO-BREAK SPACE' (U+00A0)`. Could it be the case? I think I actually experienced it myself recently but dismissed by replacing those spaces with normal spaces.

**Comment by MarcusSterz** [comment]
OK, i ll add it - no problem.

**Comment by mWaltari** [comment]
Tested, works in Delphi and Text Editor Pro without any problems
