### ISSUE TITLE
Unwanted characters in JetBrains Rider tooltips

### ISSUE THREAD

**Issue by maciejszymanski** [MonoLisaFont/feedback#82]
Hi,
I've started using Monolisa as my default programming font in Rider. I love it but have a small issue with rendering some "x-boxes" inside tooltips.
![image](https://user-images.githubusercontent.com/2227118/119014283-1b5a4380-b998-11eb-8bc2-16343ecdc56e.png)

Font version: 1.700

Rider version: 
![image](https://user-images.githubusercontent.com/2227118/119014796-9d4a6c80-b998-11eb-9883-1d9db5598dde.png)

**Comment by okonet** [comment]
This is related to non breaking space missing #80

**Comment by MarcusSterz** [comment]
These boxes stand for glyphs that are not within ML’s glyphs range. 
I would have to know what has been typed.

**Comment by okonet** [comment]
Judging by the image, it’s non breaking space @MarcusSterz

**Comment by MarcusSterz** [comment]
> Judging by the image, it’s non breaking space @MarcusSterz

It will be in the upcoming release.

**Comment by bebraw** [comment]
This has been fixed in 1.800. Please report if you can still see it after upgrading (the same download link will work).

**Comment by maciejszymanski** [comment]
I've just upgraded to 1.801 and it seems the problem with Rider still exists.

![image](https://user-images.githubusercontent.com/2227118/123699475-9ea46a00-d85f-11eb-9d36-9fced52686a4.png)

**Comment by bebraw** [comment]
@maciejszymanski Can you ask JetBrains about what character they use in Rider for that particular purpose? We added a character but it seems like we missed exactly the one they are using. I imagine they must have an issue tracker somewhere as well.

**Comment by dinhquochan** [comment]
@bebraw  I doesn't see anymore? It's fixed.

<img width="677" alt="image" src="https://user-images.githubusercontent.com/9979458/123845502-76d80380-d93e-11eb-8902-d55587423f04.png">

**Comment by bebraw** [comment]
@maciejszymanski Can you confirm? Could it have been a font cache issue on your system?

**Comment by maciejszymanski** [comment]
@bebraw Still no luck on my side. 
What I tried: uninstall/reinstall font via windows fonts settings window, remove fonts from Windows/Fonts folder then reinstall, disable font cache service then clear font cache folder and reinstall. 

When using bold variant the issue does not exist:
![image](https://user-images.githubusercontent.com/2227118/123853399-b3dfce00-d91d-11eb-98c4-7f13a58064af.png)

Regular:
![image](https://user-images.githubusercontent.com/2227118/123853474-c9ed8e80-d91d-11eb-8969-be3b77bb70c4.png)

Rider Settings:
![image](https://user-images.githubusercontent.com/2227118/123853673-07521c00-d91e-11eb-83a7-7774f1c89c1f.png)

**Comment by bebraw** [comment]
That's a good clue, thanks. Based on what you just said, there might be some subtle difference between the font builds on our side. That's something to fix.

**Comment by maciejszymanski** [comment]
Hi @bebraw, 
Small update, after installing a newer version of Rider IDE (2021.1.3) the problem does not occur anymore. Out of curiosity, I rolled back to 2021.1.2 and the problem came back. So it seems it is related to the Rider version. Anyway, in the latest version, the font is working fine so I'm closing the issue. Thanks!
