### ISSUE TITLE
= looks like it is not in the middle in vs code?

### ISSUE THREAD

**Issue by adschem** [MonoLisaFont/feedback#83]
Using vs code on Linux (Arch) the = symbol is appearing lower than usual for MonoLisa looks very strange see attached:
![image](https://user-images.githubusercontent.com/14344249/119545780-1972f480-bd8b-11eb-8143-e4955708ca89.png)

The font works very nicely in Pycharm 
![image](https://user-images.githubusercontent.com/14344249/119545891-34ddff80-bd8b-11eb-937e-614132931a20.png)

Please help?

**Comment by bebraw** [comment]
What's your display resolution and font size? Is the behavior the same if you go one font size higher/lower? Are you using OTF?

**Comment by adschem** [comment]
Display is 1920 x 1080
Font size in image is 12, have also tried 11 and 13 with same results

I installed tff font, is it best to use OTF?

**Comment by bebraw** [comment]
I believe OTF may be worth a go. TTF is there primarily for Windows users.

**Comment by adschem** [comment]
I have tried the OTF font:
[image: image.png]

my settings in VS code are like this :) thanks for the help,
best
Adam

{
"editor.fontFamily": "MonoLisa",
"editor.lineHeight": 0,
"editor.fontLigatures": "'case' on",
"editor.fontSize": 13
}

**Comment by bebraw** [comment]
@adschem I cannot see your image. Most likely you have to upload it through GitHub UI.

**Comment by dinhquochan** [comment]
Here @bebraw 13px on VS Code (ubuntu 20.04)

![image](https://user-images.githubusercontent.com/9979458/119752894-fc900b80-bec7-11eb-8d46-9fd895da1849.png)

16px:

![image](https://user-images.githubusercontent.com/9979458/119752975-2ba67d00-bec8-11eb-9836-909adf4ab743.png)

Iosevka as 16px

![image](https://user-images.githubusercontent.com/9979458/119753082-5b558500-bec8-11eb-8fa4-c64f6d1d22bd.png)

**Comment by adschem** [comment]
![image](https://user-images.githubusercontent.com/14344249/119787723-6957d580-bec9-11eb-9fce-d8856e988d15.png)
with the settings: 
{
    
    "editor.fontFamily": "MonoLisa",
    "editor.lineHeight": 0,
    "editor.fontLigatures": "'case' on",
    "editor.fontSize": 13,
    "editor.renderLineHighlight": "gutter"
    
}

**Comment by bebraw** [comment]
@adschem Can you use https://www.monolisa.dev/playground and paste screenshots generated with different fonts and `1 + 1 = 12` for comparison?

**Comment by adschem** [comment]
![image](https://user-images.githubusercontent.com/14344249/119969632-b3fb4f80-bfa6-11eb-8319-e70e6e26e70e.png)

**Comment by bebraw** [comment]
@adschem Can you paste render from Fira Code or the others as well to compare?

**Comment by adschem** [comment]
![image](https://user-images.githubusercontent.com/14344249/119970087-3ab02c80-bfa7-11eb-8350-79b64d6931fb.png)
![image](https://user-images.githubusercontent.com/14344249/119970101-3dab1d00-bfa7-11eb-9495-7ea9fe69e431.png)
![image](https://user-images.githubusercontent.com/14344249/119970116-40a60d80-bfa7-11eb-968d-09f26130a145.png)

**Comment by adschem** [comment]
hope that helps :)

**Comment by okonet** [comment]
It looks correct to me in the first screenshot: https://github.com/MonoLisaFont/feedback/issues/83#issuecomment-850316177

**Comment by adschem** [comment]
Yes that is from the playground where it looks different to the screen shot that is from VScode @okonet 

in 
https://github.com/MonoLisaFont/feedback/issues/83#issue-901163871

**Comment by MarcusSterz** [comment]
The = [equal sign] is centered in all styles as you can see when you type H=H. Different white space occurs naturally since the figures have different side bearings but all have the same width.
