### ISSUE TITLE
Disable |= ligature when preceded by |

### ISSUE THREAD

**Issue by Eldair** [MonoLisaFont/feedback#84]
In most recent update `|=` was added but it looks bad when preceded by `|` - which is an assignment operator in javascript `||=`
![image](https://user-images.githubusercontent.com/470003/119647604-c186cd00-be20-11eb-8f42-3aa681ec6f4a.png)

**Comment by okonet** [comment]
That's a good catch. @bebraw I think we should build a better test suite to catch such regressions in the future. @MarcusSterz can we make the ligature appear only if _it is not preceded_ by `|`?

**Comment by bebraw** [comment]
Instead of disabling, another option would be to define a ligature for `||=` if disabling based on a rule isn't possible.

We weren't aware of the combination earlier so we missed it.

**Comment by bebraw** [comment]
We discussed this, we should add ligatures for both `||` and `||=`.

**Comment by bebraw** [comment]
This has been fixed in 1.800.
