### ISSUE TITLE
Larger ≤ and ≥ ligatures to match == and != spacing

### ISSUE THREAD

**Issue by sgigou** [MonoLisaFont/feedback#85]
`>=` and `<=` ligatures looks rather small compared to other 2-chars comparison operators. The spacing between the ligatured operator and the vars around is wider than other spaces in code. In a dense block of code, it creates holes that break the flow.

Is it possible to stretch the icon to have the same spacing between operators and vars?

Case:
<img width="104" alt="Capture d’écran 2021-06-01 à 10 10 35" src="https://user-images.githubusercontent.com/33257100/120295839-d56e7b00-c2c7-11eb-8893-c5197f05e6f6.png">

Example with PragmataPro:
<img width="95" alt="Capture d’écran 2021-06-01 à 10 11 41" src="https://user-images.githubusercontent.com/33257100/120295871-dc958900-c2c7-11eb-8eb6-c8fbb4875a88.png">

Real case:
<img width="617" alt="Capture d’écran 2021-06-01 à 10 56 47" src="https://user-images.githubusercontent.com/33257100/120296122-18305300-c2c8-11eb-9c61-1e1cdeaad070.png">

**Comment by bebraw** [comment]
Do you have any other ligatures in mind that could benefit from a bit of stretching like this?

**Comment by sgigou** [comment]
All the other ligatures are well balanced! Maybe `|=` is in the same situation, but I do not use this ligature, so I don’t know if it is annoying or not…

**Comment by joshmosh** [comment]
I'd also like to add a +1 to this enhancement as well. I recently switched to MonoLisa after using FIreCode for a long time. I think the greater/less than or equal to ligatures could use some more spacing.

**Comment by okonet** [comment]
We agreed to update the ligatures for `<=` and `>=` to take 2 spaces and match the width of `==` ligature.

**Comment by joshmosh** [comment]
@okonet Thank you!

**Comment by MarcusSterz** [comment]
Added. Will be available in 1.802.

**Comment by bebraw** [comment]
Fixed in 1.802.
