### ISSUE TITLE
Create a separate build for Alternate / Stylistic set

### ISSUE THREAD

**Issue by vikky49** [MonoLisaFont/feedback#87]
Is it possible to create a separate build variants for the stylistic sets . For example we still can't use the alternative variants in the most popular IDE like IDEA / Intelli J

**Comment by okonet** [comment]
What alternative variants are you referring to? I’d suggest to poke JetBrains and ask for the better support of open type features instead. They have it in a tracker and afaik are already working on it.

**Comment by bebraw** [comment]
👍 for encouraging JetBrains to add better support for toggling OpenType features.

Doing a font build per each individual feature and their combinations would bloat the font zip a lot so I don't see that as a viable option.

I know there's tooling like https://fonttools.readthedocs.io/en/latest/subset/ for subsetting. To solve the problem at user space, you would have to find a tool similar to this that can take the stylistic sets you want and use those as replacements for the original glyphs. Most likely a developer from fontTools (author of subset) can help in figuring out how to do this.

**Comment by bebraw** [comment]
I found this: https://stackoverflow.com/a/14102908/228885 . It looks like [afdko](https://github.com/adobe-type-tools/afdko/) can replace glyphs so maybe that's the way to do this.

**Comment by vikky49** [comment]
Actually I used this tool 

https://github.com/twardoch/fonttools-opentype-feature-freezer

and then u can modify the font with your favorite alternatives like this 

❯ pyftfeatfreeze -n -v -f 'ZERO,ss01,ss04,ss06' <source-font.otf> <output-font.otf>
