### ISSUE TITLE
Best practice to use as webfont?

### ISSUE THREAD

**Issue by aquarhead** [MonoLisaFont/feedback#88]
I'm curious if for example you have a CDN already so I can just link to it directly within my website? Or do you expect everyone to basically host their own copy?

I'm also curious if I would violate your license by hosting it, and for example someone else download it and just use it without a license?

I'd appreciate any tips or help for setting up webfont, for example I'd like to use it in my about me page and blog, both are public projects on GitHub. So I wonder whether it's fine to just embed the font in git and reference the public github URL, and for example if I just need to include some attribute statement.

Thanks for the work BTW, I love using it so far.

**Comment by bebraw** [comment]
CDN is something we're considering implementing. How would you expect to consume it? I think we can make it so that you can select the features Google Fonts style for example.

As there's no CDN yet, I've seen people simply host the font on their site.

I might have an option for you, though. We use these resources internally:

* https://www.monolisa.dev/api/fonts/initial
* https://www.monolisa.dev/api/fonts/all

The CSS files contain the font in a md5 encoded format. If you need only basic weights, I believe `initial` might be enough. You could for example copy the CSS to your site and then refer to the font.

**Comment by aquarhead** [comment]
The `initial` link works great!

I do also use Google Fonts, providing a simliiar API sounds like an excellent idea :)

Feel free to close this issue, but consider adding a section in FAQ?

**Comment by davidpmccormick** [comment]
I'm also interested in using MonoLisa in code blocks on my site and still not sure what (if any) right I have to do so and/or what license I would need to have purchased. Couldn't find anything about it in the faqs.

**Comment by bebraw** [comment]
@davidpmccormick See https://www.monolisa.dev/license . The type of license you need depends on the context (private or commercial). If it's private use, then the complete version is the best bet as it comes with the variable font that's ideal for the web.

**Comment by davidpmccormick** [comment]
I think 'private' was throwing me off. Because it's on the web, so not really private, but personal.

I'll probably have to pony up for the complete version then. Thanks.

**Comment by ktym4a** [comment]
@bebraw If I have purchased Complete, can I use on my personal site (e.g. portfolio or blog site)?
Or if published on the web, is it not 'private'?

**Comment by bebraw** [comment]
@ktym4a Persona usage is fine. There's also a customization tool at `/orders` where you can choose which features to include. A commercial license would be needed if the font is used to as a part of a product on web.

**Comment by ktym4a** [comment]
@bebraw Thanks for letting me know! I had already purchased and in the process of creating a website to use.

**Comment by bebraw** [comment]
@ktym4a No problem. We've included concrete examples to the [eula](https://www.monolisa.dev/license) of commercial/non-commercial. If you want to include back to the site at a footer or so, that's appreciated but not absolutely needed.

**Comment by ktym4a** [comment]
@bebraw Thanks!
and Yes, I am doing that. (I will also create something like Uses page in the future and describe MonoLisa Font there as well.)
Actually one of the reasons I am creating this site is because I want many people to see/know MonoLisa Font.
https://ktym4a.me/
