### ISSUE TITLE
1.800 version weight issue

### ISSUE THREAD

**Issue by Eldair** [MonoLisaFont/feedback#89]
Hello,

This is how 1.800 looks like in vscode:
![image](https://user-images.githubusercontent.com/470003/123619495-8570ce80-d809-11eb-9237-77399a1ec245.png)

Unfortunately I didn't keep the previous version but there is some issue with this one.

**Comment by Eldair** [comment]
It can be seen here as well. Italic version looks like it has the same weight like the previous version but regular (and bold) are much thinner.
![image](https://user-images.githubusercontent.com/470003/123620330-645cad80-d80a-11eb-9048-fd38d46c2553.png)

**Comment by Eldair** [comment]
OTF files look ok.

otf left vs ttf right
![image](https://user-images.githubusercontent.com/470003/123620675-c74e4480-d80a-11eb-9b15-5a5716bee8d5.png)

**Comment by mWaltari** [comment]
For me also text seems to be way too thin, at least Windows fixed width TTF font.

![image](https://user-images.githubusercontent.com/4082975/123622177-9d9a1b00-d814-11eb-8f3d-956729e443e1.png)

![image](https://user-images.githubusercontent.com/4082975/123622238-ae4a9100-d814-11eb-9596-a7c65a5c76c8.png)

-Tee-

**Comment by carlomunguia** [comment]
I was just about to file a comment (thanks to everyone above) - this is an obvious Thin version of a font, not a Regular version, the fidelity dropped by 30% on my IDE. Please rectify & resubmit correction ◀️

**Comment by MarcusSterz** [comment]
Interesting. We will have a look into that.

**Comment by YoEight** [comment]
I don't want to sound pushy but when could we expect a fixed version?

Thanks for your time and work.

**Comment by bebraw** [comment]
@YoEight We're currently working on it.

**Comment by bebraw** [comment]
Fixed in 1.801. You can use the same download link to get the new version.
