### ISSUE TITLE
Using MonoLisa in a Windows command prompt

### ISSUE THREAD

**Issue by u01jmg3** [MonoLisaFont/feedback#90]
OS: Windows 10 Home (21H1) Build 19043.1055

---

Hello,

I would like to use the MonoLisa font in my Windows command prompt. However, there are several requirements before Windows will provide the font as one to choose.

See here: https://superuser.com/questions/1347724/how-can-i-add-additional-fonts-to-the-windows-console#answer-1381619

- How many of these requirements does MonoLisa pass?
- Is MonoLisa a "true" monospaced font (or is it a variable-pitch font underneath)?
- Is it possible to tweak MonoLisa so it can be used in a Windows command prompt?

(Fonts that are compatible: Fira Code, Fira Mono, Cascadia Mono)

Curious to know. Appreciate your time. 🏄🏻

**Comment by bebraw** [comment]
It would be great if anyone using Windows could comment on this one.

On a quick look, the requirements seem fairly strict and we won't change the font to fit them. That said, if it works there already then it's something good to document.

**Comment by okonet** [comment]
@bebraw maybe we could provide a sample font file to test?

**Comment by bebraw** [comment]
@u01jmg3 Can you send mail to info@monolisa.dev? I will respond with a light version to test against.

**Comment by u01jmg3** [comment]
I can already confirm that MonoLisa isn't compatible but I've no idea which rules MonoLisa passes/fails. I was hoping you could tell me and that it passed most of them!

The only guide I have as to why this might be relates to using PuTTY which is capable of determining what it calls fonts that are variable-pitch and those which are not for use in a remote terminal. The reason this is useful is it gives a similar (ish) list of fonts that the Windows command prompt offers.

---

On the left is a snippet of the fonts that can be chosen under the Windows command prompt. (For info, I have 29 fonts to choose from out of 100+ installed on my machine so Windows is fussy).

On the right is PuTTY with variable-pitch fonts enabled. This is under its Window → Appearance settings for choosing a terminal font. This is why I think it is comparable.

In both, MonoLisa is not available.

<img width="862" alt="fonts" src="https://user-images.githubusercontent.com/1266205/123862275-0cb06600-d920-11eb-86d5-f36e31de2472.png">

**Comment by bebraw** [comment]
@u01jmg3 Ok, thanks for the info. I think our font designer can comment on the specific criteria. I've listed them before so when he has time he can comment on each.

1. The font must be a fixed-pitch font.
2. The font cannot be an italic font.
3. If it is a TrueType font, it must be FF_MODERN.
4. If it is not a TrueType font, it must contain the OEM_CHARSET.
5. The font cannot have a negative A or C space.

It seems likely we don't match at least one of the criteria.

**Comment by renkejr-pkwy** [comment]
Microsoft has added support for other fonts, including MonoLisa to the latest Command Prompt and Windows Terminal (1.9).  Windows Terminal may be required to enable the option in Command Prompt.

![image](https://user-images.githubusercontent.com/28737570/125803971-acfea99c-bf46-45e3-a954-5b824e12e4d0.png)

**Comment by bebraw** [comment]
Ok, that's good news. Let's close this then as there's nothing to fix.

**Comment by u01jmg3** [comment]
@renkejr-pkwy: thanks for the tip! It looks like you need the Windows Insider Program Dev Channel build version of Windows as described [in this Windows blog post](https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-9-release/) before it will work because I already have Windows Terminal 1.10 and I don't see MonoLisa listed as a font choice.

---

> _I think our font designer can comment on the specific criteria. I've listed them before so when he has time he can comment on each._

@bebraw: I guess this won't happen?

**Comment by bebraw** [comment]
@u01jmg3 I asked him personally and he told me it would be tricky to meet the criteria. Now that support is being added on Windows side, is there something specific to do?

**Comment by u01jmg3** [comment]
Nope - great that Windows is finally bringing more control over fonts / choice of terminal. As you said before, would be good to document. Appreciate your time.

**Comment by renkejr-pkwy** [comment]
@u01jmg3 I am **not** running Windows Insider.  I just downloaded Window Terminal 1.9 and Windows Terminal Preview 1.10 from the github [release page](https://github.com/microsoft/terminal/releases).

**Comment by u01jmg3** [comment]
@renkejr-pkwy: any ideas why I wouldn't be seeing the same thing? What version of MonoLisa are you using? What build of Windows 10 are you using? I'm on 19043.1110.

---

On the left I have my cmd properties open and on the right is Windows Terminal **Preview** 1.10.1933.0. I also have Windows Terminal 1.9.1942.0 installed but no joy. Not sure how these could enhance cmd.exe

<img width="562" alt="no-monolisa" src="https://user-images.githubusercontent.com/1266205/125840469-250a6949-b816-4fbd-9cce-d568742a9b6d.png">

**Comment by renkejr-pkwy** [comment]
@u01jmg3 MonoLisa 1.801 personal TTF on Windows 10 Pro 20H2 (19042.928).  I have the same Windows Terminal and Windows Terminal Preview versions.

**Comment by u01jmg3** [comment]
I just installed the Windows Feature Experience Pack 120.2212.3920.0 but again, MonoLisa does not show up as a font to choose.

I'm running Home rather than Pro so maybe that could be the difference.

**Comment by grpnpraveen** [comment]
I am also facing the same issue , I think there is no fix that I know about but fyi,the command prompt is in the MonoLisa font inside vscode.
