### ISSUE TITLE
1.801 !== ligature issue

### ISSUE THREAD

**Issue by Eldair** [MonoLisaFont/feedback#91]
Hello,

!== ligature 'broke' with the latest version (1.800 and 1.801). In previous version all three dashes were spaced evenly (same as === ligature).

This is how it looks at 14px size on 1440p screen (27") - vscode on windows. 
![image](https://user-images.githubusercontent.com/470003/123671096-32653e80-d83e-11eb-8eb4-9f257c4993c9.png)

**Comment by Eldair** [comment]
Hi, any news on this?

**Comment by okonet** [comment]
We are looking at it...

**Comment by MarcusSterz** [comment]
This is a tricky one since !== is using === as a component. Not clear why this happens.

**Comment by bebraw** [comment]
Fixed in 1.802.
