### ISSUE TITLE
Spotty ligature support with Hyper terminal

### ISSUE THREAD

**Issue by tbremer** [MonoLisaFont/feedback#94]
Ligature support within [Hyper Terminal](https://github.com/vercel/hyper) seems limited in some capacity. Attached are two screen grabs the first is MonoLisa as you can see most ligatures do not work, however, `[|`, `{|`, and `#?`  appear as expected. The second screen grab is Fira Code, not a font I normally use, but I knew it had ligatures.

The application is Electron based, so I assume it uses Chrome, however the render-er is a Canvas element, so perhaps there is something there?

macOS version: 10.15.7

**Edit:** I have added additional screenshot of Google Chrome rendering MonoLisa fine within a Canvas element. So, this might be an issue with the Hyper application. [Link to Codepen](https://codepen.io/tbremer/pen/d25bc07b54d5a06ce31d554b7f8775b0) (this assume MonoLisa is installed on your system).

![MonoLisa](https://user-images.githubusercontent.com/2998575/128388386-2e77decf-fa99-4ad3-be08-2ec6fc1fbb54.png)

![Fira Code](https://user-images.githubusercontent.com/2998575/128388407-9a1a11fc-2e0a-47d5-a202-b68b751e77c4.png)

![Google Chrome](https://user-images.githubusercontent.com/2998575/128389742-36856b25-5e25-4930-959d-23e37dd7e66b.png)

**Comment by bebraw** [comment]
[|, {|, and #? are from the `calt` set. The not rendering ones are from `liga`.

Is there a way to enable specific font features in hyper? I would expect similar setup as in VS Code (explained at https://www.monolisa.dev/faq).

**Comment by bebraw** [comment]
@tbremer Another question. Do ligatures work for you in VS Code and other environments?

**Comment by tbremer** [comment]
VS Code handles ligatures fine.

As for specific features, that _might_ be possible in Hyper, but I could not find an immediate way to enable them. They offer the ability to pass CSS into the Terminal to affect it's rendering, so I chose this overly generic / brute force option to try and get the ligatures to render.
```css
* { font-feature-settings: "liga" 1, "dlig" 1, "onum" 1, "lnum" 1, "tnum" 1, "zero" 1, "frac" 1, "sups" 1, "subs" 1, "smcp" 1, "c2sc" 1, "case" 1, "hlig" 1, "calt" 1, "swsh" 1, "hist" 1, "ss**" 1, "kern" 1, "locl" 1, "rlig" 1, "medi" 1, "init" 1, "isol" 1, "fina" 1, "mark" 1, "mkmk" 1; }```

However, as I dug more into the issue I found that they use a package called [font-ligatures](https://github.com/princjef/font-ligatures) that I _believe_ detects what code point/range the necessary characters are at (that is probably an over simplification of what that package actually does ☺️).

**Comment by bebraw** [comment]
It looks like there's no way we can fix this at the font itself. We've split the ligatures to `calt` and `liga` groups on purpose as `calt` applies only spacing changes and `liga` can replace entire characters.

To enable ligatures in Hyper, some change would be needed on their side. Sadly there doesn't seem to be enough customizability available.
