### ISSUE TITLE
False accents and ligatures

### ISSUE THREAD

**Issue by gsabater** [MonoLisaFont/feedback#97]
Looks like sometimes, grave accents `` ` ``, are represented as accented letters.
for example, the code for ``await this.$axios.post(`sites`, body)``
is printed as 
![image](https://user-images.githubusercontent.com/4948172/132512124-301fc3e8-e406-4d50-a5b4-12d2f21bcbc9.png)

This happens on vscode with theme gruvbox material dark, but the theme has nothing to do with this
I have been looking other issues and I haven't found anything similar to this.

**Comment by bebraw** [comment]
#53 was an earlier issue like this.

Which version are you using? Can you provide OS/editor as well? Do you see the behavior at monolisa.dev site?

**Comment by gsabater** [comment]
Hello @bebraw 

* According to the file explorer, the font version is 1.7
* On your site I dont see the issue
* OS windows 10, editor VSCODE latest

**Comment by bebraw** [comment]
@gsabater Let's keep this open.

The problem in the past was that we weren't able to reproduce it. Are you using otf or ttf? Can you see the behavior in the terminal and other editors too?

**Comment by bebraw** [comment]
For reference, it's preferable to use ttf under Windows as it renders better than otf there.

**Comment by gsabater** [comment]
I can confirm that i'm using ttf format of the monolisa regular v1.7
On sublime text i have the same issue

![image](https://user-images.githubusercontent.com/4948172/132544191-80d63606-3539-42c4-8173-932c990f9e2f.png)

**Comment by gsabater** [comment]
On the console (at least cmder) i dont have this issue.
I have checked and changed all settings and everything works good
![image](https://user-images.githubusercontent.com/4948172/132544631-0936c4ea-425e-48c6-908c-fa94fe005613.png)

**Comment by gsabater** [comment]
On the vscode terminal which I THINK uses the same vscode settings for font and theme colors, the characters work as expected as well. The terminal is powershell
![image](https://user-images.githubusercontent.com/4948172/132545361-832ff2a3-19aa-4a0c-a696-39bb98b75752.png)

**Comment by gsabater** [comment]
I have rescued an old 1.6 version of the font and the problems are not there, maybe something was introduced in an update?

**Comment by bebraw** [comment]
@gsabater Just out of curiosity, it might be worth trying VS Code and Sublime with the OTF version. If that works, then that restricts the issue to TTF only.

**Comment by bebraw** [comment]
> I have rescued an old 1.6 version of the font and the problems are not there, maybe something was introduced in an update?

Yeah, sounds like a regression.

**Comment by gsabater** [comment]
> @gsabater Just out of curiosity, it might be worth trying VS Code and Sublime with the OTF version. If that works, then that restricts the issue to TTF only.

I'm sorry but i don't have access to those files

**Comment by bebraw** [comment]
@gsabater Just to confirm, did you see the issue in 1.801 as well? Was that the first version where you encountered the problem? Just check as you were speaking about 1.6 and 1.7.

**Comment by gsabater** [comment]
@bebraw  I have seen the problem on the 1.7 but not on the 1.6.
I only have those versions of the font

**Comment by bebraw** [comment]
@gsabater You should be able to access 1.801 through your download link after purchase. Can you send your purchase id to info@monolisa.dev so I can resend the link?

**Comment by gsabater** [comment]
Hello @bebraw , I'm sorry but i don't have access to any download links as I haven't purchased the font. I just wanted to provide feedback.

**Comment by bebraw** [comment]
No worries. Likely we should wait someone to test this against 1.801 then to see if the issue was fixed already. It's definitely interesting 1.6 works and 1.7 doesn't. Something must have changed in between.

**Comment by gsabater** [comment]
Perfect, just @ me if you need me to do any test or help in any way

**Comment by tommarien** [comment]
Just tested it on Win10 running latest vscode 1.60.1 and font version 1.801

![code](https://user-images.githubusercontent.com/1032545/133386902-e0251bd2-0a8a-42e7-8d7e-7711f48b2075.png)

**Comment by bebraw** [comment]
@tommarien Ok, thanks for the info!

Let's close as `wontfix`.
