### ISSUE TITLE
Feedback on Script Variant

### ISSUE THREAD

**Issue by cmconnelly** [MonoLisaFont/feedback#98]
I voted via the link in the email announcing 1.802, but I was hoping there would be an option to say a bit more than yes or no, so I'm making one here.  :)

I don't use the script SS, but that's mostly because my editor-of-choice (GNU Emacs) doesn't support stylistic sets at this time.  Having looked at it in action in TextEdit, however, I like some of the chanacters, but some feel "too noisy" to me.

In particular, the lowercase d, g, h, i, k, m, n, p, u, w, x, and y all feel like they work well, whereas the more flashy characters, lowercase e, f, i, j, l, r, s, and z, feel like they break up the rhythm of the type, and thus make it more difficult to read without being distracted by those characters.

The f, j, l, r, and s are the most jarring, in part, I think, because it seems like the spacing between them and surrounding characters isn't quite right.  (Of course all the characters take up the same space, in this monospace font, but because of the changed forms it feels like some of them have a larger gap on one side or the other.  In a proportional font, you might be able to just tweak the kerning, but that's obviously not possible here.)

I think the most problematic characters are the r, the s, and the f.  It feels like none of these characters start on the baseline, so they don't feel as well anchored as they might otherwise.  I can see that the r and the s are meant to feel like they're flowed into from the terminal of the e and i (and t, and maybe some others), but the lowercase a doesn't have the same upcurving terminal, so an "as" or "ar" pair looks weird.

The lowercase s feels like it's squashed—the very tip of the first stroke ends at the x-height of letters without ascenders (e.g., o, p, a, u) so the height of the curve is less than that of those other letters.  Ideally the body of the s should be as tall as the other characters, and that first stroke just end a bit higher (maybe at the same height as, say, the ascender of the h or b, but it would probably need a bit of experimentation).

I think that the issue with the lowercase f is almost the opposite—it has a loop like a descender, but that loop is set just below the baseline, so it feels a bit out of place.  As a result, its bar is also lower than that of the h.  I also think that its bar is a bit longer than it should be, so it makes the character seem wider. 

The lowercase r has the same issues as the s with its first stroke, but I think that whereas the top of the s isn't tall enough, the bar of the r is too tall and flat; if it curved down a bit from the peak of the first stroke, it would look more like an r to me.  (Right now, I think it looks a bit like a weirdly tilted π rather than an r.)

The lowercase l is almost okay, but it feels like it's wider than it should be, maybe because the opening stroke starts above the baseline, and the cross point is even higher, so it feels shorter and fatter

I hope that this feedback is useful rather than annoying.  I can also do some visual mockups if my descriptions aren't clear; just ask!

**Comment by MarcusSterz** [comment]
Thank you for your thoughts on our script variant and sorry for replying so late. We had some pressing issues to tackle in the meantime.
You are absolutely right that there are problematic letters. Trying to make a monospaced font look handwritten is difficult and there is no 100% perfection since there are combinations that will look awkward—some of them you mentioned already.
When I look into the script letters again I will take your feedback into consideration!
