### ISSUE TITLE
Powerline issue on Alacritty and other GPU-rendered terminals 

### ISSUE THREAD

**Issue by YoEight** [MonoLisaFont/feedback#99]
Greetings!

![Screenshot from 2021-09-26 10-47-30](https://user-images.githubusercontent.com/144545/134800944-fb6b56e5-6931-4147-8527-591987b64c80.png)

I got issues with those characters in particular: '◣', '◢'. This is not a regression, I had the issue before 1.8002. I specifically said GPU-rendered issue because I don't have that issue with gnome-terminal for example. Those characters are aligned correctly there.

Font version: 1.8002
OS: Linux

Thanks for your time!

**Comment by YoEight** [comment]
Turns out I got also this issue with KDE Konsole terminal.

**Comment by bebraw** [comment]
We decided to keep the issue open for now to track its prevalence. The problem is that we cannot fix this on our end at the font.
